import { getState, update } from "../core/store.js";
import { closeModal, openModal } from "../ui/modals.js";
import { toast } from "../ui/notifications.js";

const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

export function removedCards(state=getState()){return[...(state.metadata?.removedCards||[])].sort((a,b)=>Date.parse(b.removedAt)-Date.parse(a.removedAt))}

export function removeVaultCards(ids){const unique=[...new Set(ids)].filter(id=>getState().items?.[id]),removed=[];if(!unique.length)return removed;update(save=>{save.metadata.removedCards||=[];for(const id of unique){const item=save.items[id];if(!item)continue;save.metadata.removedCards=save.metadata.removedCards.filter(entry=>entry.id!==id);save.metadata.removedCards.push({id,item:JSON.parse(JSON.stringify(item)),title:item.title||"Untitled card",wing:item.wing||"unknown",removedAt:new Date().toISOString()});delete save.items[id];removed.push(id)}const removedSet=new Set(removed);if(Array.isArray(save.metadata.artworkApprovals))save.metadata.artworkApprovals=save.metadata.artworkApprovals.filter(entry=>!removedSet.has(entry.itemId));const daily=save.preferences?.dailyDriver;if(daily){daily.hiddenCards=(daily.hiddenCards||[]).filter(id=>!removedSet.has(id));daily.dismissedRecommendations=(daily.dismissedRecommendations||[]).filter(id=>!removedSet.has(id))}save.metadata.removedCards=save.metadata.removedCards.slice(-500)});return removed}

export function restoreVaultCard(id){let restored=false;update(save=>{const index=(save.metadata.removedCards||[]).findIndex(entry=>entry.id===id);if(index<0||save.items[id])return;const [entry]=save.metadata.removedCards.splice(index,1);save.items[id]=entry.item;restored=true});return restored}

export function openRemoveCardsDialog(ids,title,onChanged=()=>{}){const items=[...new Set(ids)].map(id=>getState().items?.[id]).filter(Boolean);if(!items.length)return false;const label=title||items[0].title||"this card";openModal({title:`REMOVE ${items.length>1?`${items.length} CARDS`:"CARD"}`,body:`<div class="remove-card-confirm"><span class="eyebrow">VAULT RECORD REMOVAL // RECOVERABLE</span><h3>${esc(label)}</h3><p>${items.length>1?`${items.length} related cards will be removed from the active library.`:"This card will be removed from the active library."} Progress, metadata, and artwork links leave the active view with it.</p><p><b>Original files on C: or D: will not be moved or deleted.</b></p></div>`,actions:[{label:"KEEP CARD",handler:()=>closeModal()},{label:`REMOVE ${items.length>1?"CARDS":"CARD"}`,primary:true,handler:()=>{const count=removeVaultCards(items.map(item=>item.id)).length;closeModal();onChanged();toast("CARD REMOVED",`${count} card${count===1?"":"s"} moved to Removed Cards. Original files were untouched.`)}}]});return true}

export function openRemovedCardsDialog(onChanged=()=>{}){const entries=removedCards();openModal({title:"REMOVED CARDS",body:`<div class="removed-card-list">${entries.map(entry=>`<article><span><b>${esc(entry.title)}</b><small>${esc(String(entry.wing).toUpperCase())} · REMOVED ${new Date(entry.removedAt).toLocaleString()}</small></span><button class="button" data-restore-vault-card="${esc(entry.id)}">RESTORE</button></article>`).join("")||`<div class="empty"><b>NO REMOVED CARDS.</b></div>`}</div>`,actions:[{label:"CLOSE",primary:true,handler:()=>closeModal()}]});const root=document.querySelector("#modal-root");root.querySelector(".modal__body").onclick=event=>{const id=event.target.closest("[data-restore-vault-card]")?.dataset.restoreVaultCard;if(!id)return;if(restoreVaultCard(id)){closeModal();onChanged();toast("CARD RESTORED","The card is back in its original Vault wing.")}};return true}

export function renderRemovedCardsButton(state=getState()){const count=removedCards(state).length;return count?`<button class="removed-cards-button" data-removed-cards><b>${count}</b><span>REMOVED<br>CARDS</span></button>`:""}
