import { emit } from "../core/events.js";
import { getState, update } from "../core/store.js";
import { closeModal, openModal } from "../ui/modals.js";
import { toast } from "../ui/notifications.js";
import { mountComicStrip } from "./comicReaderModes.js";

const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const readingMeta=item=>item.bookMeta||item.comicMeta||{};
async function externalOpen(path){const response=await fetch("./__vault/reading/open",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"open-reading-file"},body:JSON.stringify({path})});if(!response.ok)throw new Error("The file could not be opened externally.")}

function epubDocument(html,{fontSize,theme,layout}){
  const paper=theme==="night"?"#151711":"#f1e4c7",ink=theme==="night"?"#ded7bd":"#30281d",heading=theme==="night"?"#e0b45d":"#6b4922",pageWidth=layout==="single"?"calc(100vw - clamp(84px,10vw,172px))":"calc((100vw - clamp(152px,18vw,284px))/2)";
  const bodyMatch=String(html||"").match(/<body\b[^>]*>([\s\S]*?)<\/body>/i),content=(bodyMatch?bodyMatch[1]:String(html||"")).trim(),plain=content.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim(),visible=plain||/<(?:img|svg|image)\b/i.test(content)?content:`<div class="vault-empty-section"><b>THIS EPUB SECTION HAS NO VISIBLE CONTENT.</b><p>Use Next Page to continue to the next section.</p></div>`;
  return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html{scroll-behavior:auto!important}</style><style>
  :root{color-scheme:${theme==="night"?"dark":"light"}}*{box-sizing:border-box!important}html{width:100%!important;height:100%!important;margin:0!important;overflow-x:auto!important;overflow-y:hidden!important;background:${paper}!important;color:${ink}!important;scroll-behavior:smooth;scrollbar-width:none}html::-webkit-scrollbar{display:none}body{width:auto!important;min-width:100%!important;height:100%!important;margin:0!important;padding:clamp(34px,5vh,68px) clamp(42px,5vw,86px) 70px!important;overflow:visible!important;background:${paper}!important;color:${ink}!important;column-width:${pageWidth}!important;column-count:auto!important;column-gap:clamp(68px,8vw,132px)!important;column-fill:auto!important;font-family:Georgia,"Times New Roman",serif!important;font-size:${fontSize}px!important;line-height:1.62!important;text-align:left!important}body>*{max-width:100%!important;margin-top:0!important;color:${ink}!important;-webkit-text-fill-color:${ink}!important;opacity:1!important;visibility:visible!important;background-color:transparent!important}p,li,blockquote,dd,dt,span,div{max-width:100%!important;font-size:1rem!important;line-height:1.62!important;white-space:normal!important;color:${ink}!important;-webkit-text-fill-color:${ink}!important;orphans:3;widows:3}p{text-indent:1.2em;margin:.15em 0 .68em!important}h1,h2,h3,h4,h5,h6{break-after:avoid;break-inside:avoid;max-width:100%!important;color:${heading}!important;-webkit-text-fill-color:${heading}!important;line-height:1.24!important;text-align:center!important}h1{font-size:1.75rem!important}h2{font-size:1.45rem!important}h3{font-size:1.2rem!important}img,svg,video,table{display:block!important;max-width:100%!important;max-height:75vh!important;height:auto!important;margin:0 auto!important;break-inside:avoid;object-fit:contain!important;opacity:1!important;visibility:visible!important}a{color:${heading}!important;-webkit-text-fill-color:${heading}!important}pre{max-width:100%!important;white-space:pre-wrap!important;overflow-wrap:anywhere!important}.vault-empty-section{display:grid;place-items:center;align-content:center;height:70vh;text-align:center;color:${heading}!important}.vault-empty-section p{text-indent:0!important}</style></head><body>${visible}</body></html>`;
}

function mountEpubPage(html,settings){
  const parsed=new DOMParser().parseFromString(epubDocument(html,settings),"text/html"),host=document.createElement("div"),shadow=host.attachShadow({mode:"open"});
  host.className="vault-reader-epub";
  const sourceStyles=[...parsed.head.querySelectorAll("style")].map(style=>style.textContent||"").join("\n").replaceAll("html::-webkit-scrollbar",".vault-epub-viewport::-webkit-scrollbar").replaceAll("html{",".vault-epub-viewport{").replaceAll("body>*",".vault-epub-flow>*").replaceAll("body{",".vault-epub-flow{");
  shadow.innerHTML=`<style>:host{display:block;width:100%;height:100%;min-width:0;background:transparent}.vault-epub-viewport{position:relative;width:100%!important;height:100%!important;overflow:hidden!important}.vault-epub-flow{position:relative;max-width:none!important}${sourceStyles}</style><div class="vault-epub-viewport"><div class="vault-epub-flow">${parsed.body.innerHTML}</div></div>`;
  return host;
}

export async function openEmbeddedReader(itemId,onChanged=()=>{}){
  const item=getState().items[itemId],data=item&&readingMeta(item),path=item?.sourcePath||data?.sourcePath;
  if(!item||!path)return toast("LOCAL FILE NEEDED","This record does not have a matched ebook or comic file.");
  // A book already part-read is resumed. Page 1 of an untouched file is not.
  emit("READING_OPENED",{itemId,wing:item.wing,resumed:Number(data?.page||data?.lastPage||0)>1&&item.status!=="completed",meta:{title:item.title}});
  openModal({title:`OPENING ${item.title}`,body:`<div class="vault-ai-progress"><span class="eyebrow">VAULT READER // LOCAL FILE</span><h3>PREPARING BOOK…</h3><div class="vault-ai-progress__bar"><i></i></div><p>No reading content leaves this computer.</p></div>`});
  try{
    const response=await fetch("./__vault/reading/manifest",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"reading-manifest"},body:JSON.stringify({path})}),manifest=await response.json().catch(()=>({}));
    if(!response.ok)throw new Error("This file could not be prepared for the embedded reader.");
    if(manifest.externalOnly){await externalOpen(path);closeModal();return toast("OPENED IN EXTERNAL READER",manifest.format)}
    let index=Math.max(0,Math.min(Number(data.readerProgress||0),Math.max(0,Number(manifest.pageCount||1)-1))),spread=0,maxSpreads=1,pendingLastSpread=false,started=Date.now(),activeSeconds=0,activeSince=document.visibilityState==="visible"?performance.now():0,finished=false;
    const comicArchive=["CBZ","CBR","CB7","CBT"].includes(manifest.format);let fontSize=Math.max(15,Math.min(26,Number(data.readerFontSize||18))),layout=["single","spread","continuous","webtoon"].includes(data.readerLayout)?data.readerLayout:(comicArchive?"single":"spread"),theme=data.readerTheme==="night"?"night":"paper",divider=data.readerDivider!==false,imageFit=["page","width","height","original"].includes(data.readerImageFit)?data.readerImageFit:"width",direction=data.readerDirection==="rtl"?"rtl":"ltr";
    const author=(item.authors||[]).join(", ")||item.creator||"LOCAL ARCHIVE";
    const shell=`<div class="vault-reader" data-reader-layout="${layout}" data-reader-theme="${theme}" data-reader-divider="${divider?"on":"off"}" data-reader-image-fit="${imageFit}" data-reader-direction="${direction}">
      <header class="vault-reader__top"><button data-reader-library aria-label="Close reader">← <b>LIBRARY</b></button><div class="vault-reader__identity"><h2>${esc(item.title)}</h2><span>${esc(author)}</span></div><div class="vault-reader__chapter"><span data-reader-label>CHAPTER</span><i><b data-reader-progress-bar></b></i><strong data-reader-percent>0%</strong></div><div class="vault-reader__tools"><button data-reader-toc title="Contents and bookmarks" aria-label="Contents and bookmarks">☷</button><button data-reader-search title="Search this chapter" aria-label="Search this chapter">⌕</button><button data-reader-bookmark><span>▮</span> BOOKMARK</button><button data-reader-text><span>Tt</span> TEXT</button><button data-reader-fullscreen title="Fullscreen" aria-label="Fullscreen">⛶</button></div></header>
      <section class="vault-reader__settings" data-reader-settings hidden><label>TEXT SIZE <input type="range" min="15" max="26" value="${fontSize}" data-reader-font-size><b data-reader-font-label>${fontSize}px</b></label><button data-reader-theme="paper" class="${theme==="paper"?"active":""}">PAPER</button><button data-reader-theme="night" class="${theme==="night"?"active":""}">NIGHT</button><span class="vault-reader__mode-controls"><button data-reader-mode="single" class="${layout==="single"?"active":""}">ONE PAGE</button><button data-reader-mode="spread" class="${layout==="spread"?"active":""}">TWO PAGE</button><button data-reader-mode="continuous" class="${layout==="continuous"?"active":""}">SCROLL</button>${comicArchive?`<button data-reader-mode="webtoon" class="${layout==="webtoon"?"active":""}">WEBTOON</button>`:""}</span><span class="vault-reader__fit-controls"><button data-reader-fit="page" class="${imageFit==="page"?"active":""}">FIT PAGE</button><button data-reader-fit="width" class="${imageFit==="width"?"active":""}">FIT WIDTH</button><button data-reader-fit="height" class="${imageFit==="height"?"active":""}">FIT HEIGHT</button><button data-reader-fit="original" class="${imageFit==="original"?"active":""}">ORIGINAL</button></span>${comicArchive?`<button data-reader-direction-toggle class="${direction==="rtl"?"active":""}">${direction==="rtl"?"MANGA RTL":"LEFT TO RIGHT"}</button>`:""}<button data-reader-divider-toggle class="${divider?"active":""}">CENTER LINE ${divider?"ON":"OFF"}</button></section>
      <aside class="vault-reader__drawer" data-reader-drawer hidden><header><div><span>BOOK NAVIGATION</span><h3>CONTENTS</h3></div><button data-reader-drawer-close aria-label="Close contents">×</button></header><div class="vault-reader__drawer-body"><section><h4>CHAPTERS</h4><div class="vault-reader__toc">${(manifest.pages||[]).map(page=>`<button data-reader-chapter="${page.index}"><span>${String(page.index+1).padStart(2,"0")}</span><b>${esc(page.label||`Chapter ${page.index+1}`)}</b></button>`).join("")}</div></section><section><h4>SAVED BOOKMARKS</h4><div class="vault-reader__bookmarks" data-reader-bookmarks></div></section></div></aside>
      <main class="vault-reader__screen"><button class="vault-reader__drawer-tab" data-reader-toc aria-label="Open contents">☷</button><div class="vault-reader__book" data-reader-book><div class="vault-reader__gutter" aria-hidden="true"></div><div data-reader-stage></div><span class="vault-reader__page-number left" data-reader-page-left></span><span class="vault-reader__page-number right" data-reader-page-right></span></div></main>
      <footer class="vault-reader__bottom"><button data-reader-prev>◀◀ <b>PREVIOUS PAGE</b></button><div class="vault-reader__position"><span data-reader-count></span><input type="range" min="0" max="${Math.max(0,Number(manifest.pageCount||1)-1)}" value="${index}" aria-label="Chapter position" data-reader-range><small data-reader-spread-label></small></div><button data-reader-next><b>NEXT PAGE</b> ▶▶</button><button data-reader-layout title="Toggle one or two pages" aria-label="Toggle one or two pages"><span>▣</span></button></footer>
    </div>`;
    const tickReadingClock=()=>{if(!activeSince)return;activeSeconds+=(performance.now()-activeSince)/1000;activeSince=0};const visibilityClock=()=>{if(document.visibilityState==="visible"){if(!activeSince&&!finished)activeSince=performance.now()}else tickReadingClock()};document.addEventListener("visibilitychange",visibilityClock);
    let checkpointTimer,readerObserver,stripController,resizeObserver;const finish=()=>{if(finished)return;tickReadingClock();finished=true;clearInterval(checkpointTimer);readerObserver?.disconnect();resizeObserver?.disconnect();stripController?.destroy();document.removeEventListener("visibilitychange",visibilityClock);const seconds=Math.max(0,Math.round(activeSeconds)),minutes=Math.round(seconds/6)/10;update(save=>{const target=save.items[itemId],meta=target&&readingMeta(target);if(!meta)return;const readerPercent=manifest.pageCount?Math.round((index+1)/manifest.pageCount*100):meta.readerPercent||0;meta.readerProgress=index;meta.readerPercent=readerPercent;meta.readerFontSize=fontSize;meta.readerLayout=layout;meta.readerTheme=theme;meta.readerDivider=divider;meta.readerImageFit=imageFit;meta.readerDirection=direction;meta.readingSessions||=[];meta.readingSessions.push({startedAt:new Date(started).toISOString(),endedAt:new Date().toISOString(),seconds,minutes,source:"embedded_reader",format:manifest.format});meta.totalReadingSeconds=Number(meta.totalReadingSeconds??Math.round(Number(meta.totalReadingMinutes||0)*60))+seconds;meta.totalReadingMinutes=Math.round(meta.totalReadingSeconds/6)/10;if(target.bookMeta){target.bookMeta.status=target.bookMeta.status==="planned"?"reading":target.bookMeta.status;target.bookMeta.percent=Math.max(Number(target.bookMeta.percent||0),readerPercent);if(Number(target.bookMeta.pageCount)>0)target.bookMeta.currentPage=Math.max(Number(target.bookMeta.currentPage||0),Math.round(Number(target.bookMeta.pageCount)*readerPercent/100))}else if(target.comicMeta&&manifest.pageCount){target.comicMeta.readThrough=Math.max(Number(target.comicMeta.readThrough||0),index+1)}});onChanged()};
    openModal({title:"VAULT READER",body:shell});
    const root=document.querySelector("#modal-root"),reader=root.querySelector(".vault-reader"),stage=root.querySelector("[data-reader-stage]"),count=root.querySelector("[data-reader-count]"),range=root.querySelector("[data-reader-range]"),label=root.querySelector("[data-reader-label]"),spreadLabel=root.querySelector("[data-reader-spread-label]");
    const persistPosition=()=>update(save=>{const target=save.items[itemId],meta=target&&readingMeta(target);if(meta){meta.readerProgress=index;meta.readerPercent=manifest.pageCount?Math.round((index+1)/manifest.pageCount*100):0;meta.readerSpread=spread;meta.readerLayout=layout;meta.readerDirection=direction;meta.readerCheckpointAt=new Date().toISOString()}});checkpointTimer=setInterval(persistPosition,15000);readerObserver=new MutationObserver(()=>{if(!reader.isConnected)finish()});readerObserver.observe(root,{childList:true,subtree:true});
    const updateChrome=()=>{const scrollingLayout=layout==="continuous"||layout==="webtoon",percent=manifest.pageCount?Math.round((index+(spread+1)/Math.max(1,maxSpreads))/manifest.pageCount*100):0;count.textContent=manifest.pageCount?`${index+1}${comicArchive&&layout==="spread"&&index+1<manifest.pageCount?`–${index+2}`:""} / ${manifest.pageCount}`:manifest.format;range.value=String(index);label.textContent=manifest.pages?.[index]?.label||`CHAPTER ${index+1}`;root.querySelector("[data-reader-percent]").textContent=`${percent}%`;root.querySelector("[data-reader-progress-bar]").style.width=`${percent}%`;spreadLabel.textContent=scrollingLayout?(layout==="webtoon"?"WEBTOON SCROLL":"CONTINUOUS SCROLL"):maxSpreads>1?`SPREAD ${spread+1} OF ${maxSpreads}`:manifest.format;root.querySelector("[data-reader-page-left]").textContent=layout==="spread"?String(comicArchive?index+1:index*2+spread*2+1):String(index+spread+1);root.querySelector("[data-reader-page-right]").textContent=layout==="spread"?String(comicArchive?Math.min(index+2,manifest.pageCount):index*2+spread*2+2):"";const prevLabel=root.querySelector("[data-reader-prev] b"),nextLabel=root.querySelector("[data-reader-next] b"),epub=manifest.format==="EPUB";if(prevLabel)prevLabel.textContent=epub&&spread===0&&index>0?"PREVIOUS CHAPTER":"PREVIOUS PAGE";if(nextLabel)nextLabel.textContent=epub&&spread>=maxSpreads-1&&index<Number(manifest.pageCount||1)-1?"NEXT CHAPTER":"NEXT PAGE";root.querySelector("[data-reader-prev]").disabled=index===0&&spread===0;root.querySelector("[data-reader-next]").disabled=index>=Number(manifest.pageCount||1)-1&&spread>=maxSpreads-1;const bookmarks=readingMeta(getState().items[itemId])?.readerBookmarks||[];root.querySelector("[data-reader-bookmark]").classList.toggle("active",bookmarks.some(mark=>Number(mark.index)===index&&Number(mark.spread||0)===spread));root.querySelector("[data-reader-bookmarks]").innerHTML=bookmarks.length?bookmarks.map((mark,position)=>`<article><button data-reader-bookmark-open="${position}"><b>${esc(mark.label||`Chapter ${Number(mark.index)+1}`)}</b><small>PAGE ${Number(mark.index)+1}</small></button><button data-reader-bookmark-rename="${position}" title="Rename bookmark">✎</button><button data-reader-bookmark-remove="${position}" title="Remove bookmark">×</button></article>`).join(""):`<p>NO BOOKMARKS SAVED</p>`;root.querySelectorAll("[data-reader-chapter]").forEach(button=>button.classList.toggle("active",Number(button.dataset.readerChapter)===index))};
    const frameParts=frame=>frame?.shadowRoot?{scrolling:frame.shadowRoot.querySelector(".vault-epub-viewport"),body:frame.shadowRoot.querySelector(".vault-epub-flow")}:{scrolling:frame?.contentDocument?.scrollingElement,body:frame?.contentDocument?.body};
    const positionFrame=frame=>{const {scrolling,body}=frameParts(frame),viewport=Math.floor(frame?.clientWidth||0);if(!scrolling||!body||viewport<160){frame._readerMeasureTimer=setTimeout(()=>{if(frame.isConnected)positionFrame(frame)},80);return false}clearTimeout(frame._readerMeasureTimer);if(layout==="continuous"){scrolling.style.setProperty("overflow-y","auto","important");scrolling.style.setProperty("overflow-x","hidden","important");body.style.columnWidth="auto";body.style.columnCount="1";body.style.width="100%";body.style.height="auto";body.style.minHeight="100%";spread=0;maxSpreads=1;frame.dataset.readerSpreads="1";frame.dataset.readerSpread="0";frame.dataset.readerReady="true";updateChrome();return true}const gap=Math.max(48,Math.min(96,Math.round(viewport*.055))),side=Math.max(42,Math.min(86,Math.round(viewport*.045))),pages=layout==="spread"?2:1,columnWidth=Math.max(260,Math.floor((viewport-side*2-gap*(pages-1))/pages));body.style.columnGap=`${gap}px`;body.style.columnWidth=`${columnWidth}px`;const contentWidth=Math.max(scrolling.scrollWidth,body.scrollWidth||0),stride=Math.max(1,pages*(columnWidth+gap)),maxLeft=Math.max(0,contentWidth-viewport);maxSpreads=Math.max(1,Math.floor(maxLeft/stride)+1+(maxLeft%stride>2?1:0));if(pendingLastSpread){spread=maxSpreads-1;pendingLastSpread=false}else spread=Math.max(0,Math.min(spread,maxSpreads-1));frame.dataset.readerContentWidth=String(contentWidth);frame.dataset.readerStride=String(stride);frame.dataset.readerMaxLeft=String(maxLeft);frame.dataset.readerSpreads=String(maxSpreads);frame.dataset.readerSpread=String(spread);scrolling.scrollTop=0;scrolling.scrollLeft=Math.min(maxLeft,Math.round(spread*stride));frame.dataset.readerReady="true";updateChrome();return true};
    const fetchReaderPage=async pageIndex=>{const response=await fetch("./__vault/reading/page",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"reading-page"},body:JSON.stringify({path,index:pageIndex})}),page=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Reader page ${pageIndex+1} is unavailable.`);return page};
    const render=async(targetSpread=0)=>{stripController?.destroy();stripController=null;pendingLastSpread=targetSpread==="last";spread=pendingLastSpread?0:Math.max(0,Number(targetSpread||0));updateChrome();if(manifest.format==="PDF"){stage.innerHTML=`<iframe class="vault-reader-pdf" src="${esc(manifest.contentUrl)}" title="${esc(item.title)}"></iframe>`;return}if(comicArchive&&(layout==="continuous"||layout==="webtoon")){spread=0;maxSpreads=1;stripController=mountComicStrip({stage,pageCount:manifest.pageCount,startIndex:index,fetchPage:fetchReaderPage,mode:layout,direction,onIndex:pageIndex=>{index=pageIndex;persistPosition();updateChrome()},onError:error=>toast("PAGE LOAD PAUSED",error.message)});persistPosition();updateChrome();return}stage.innerHTML="<div class=\"vault-reader-loading\">TURNING PAGE…</div>";const page=await fetchReaderPage(index);if(page.kind==="image"){const second=comicArchive&&layout==="spread"&&index+1<Number(manifest.pageCount||0)?await fetchReaderPage(index+1):null;stage.innerHTML=`<div class="vault-reader-image-spread${second?" is-spread":""}"><img class="vault-reader-image" src="${page.dataUrl}" alt="Page ${index+1}">${second?`<img class="vault-reader-image" src="${second.dataUrl}" alt="Page ${index+2}">`:""}</div>`}else if(page.kind==="html"){const frame=mountEpubPage(page.html,{fontSize,theme,layout});stage.replaceChildren(frame);setTimeout(()=>{if(frame.isConnected)positionFrame(frame)},120)}else stage.innerHTML=`<pre class="vault-reader-text">${esc(page.text||"")}</pre>`;persistPosition();updateChrome()};
    const turnTo=(frame,target)=>{const {scrolling}=frameParts(frame);if(!frame||!scrolling)return false;spread=Math.max(0,Math.min(Number(target||0),Number(frame.dataset.readerSpreads||1)-1));maxSpreads=Number(frame.dataset.readerSpreads||1);frame.dataset.readerSpread=String(spread);scrolling.scrollLeft=Math.min(Number(frame.dataset.readerMaxLeft||0),Math.round(spread*Number(frame.dataset.readerStride||frame.clientWidth)));scrolling.scrollTop=0;persistPosition();updateChrome();return true};
    const showReaderError=error=>{stage.innerHTML=`<div class="vault-reader-error"><span>READER DIAGNOSTIC</span><b>THIS PAGE COULD NOT BE DISPLAYED</b><p>${esc(manifest.format)} · ${esc(manifest.pages?.[index]?.label||`Page ${index+1}`)}</p><small>${esc(error?.message||"The local file returned unreadable page data.")}</small><div><button data-reader-retry>RETRY PAGE</button><button data-reader-open-external>OPEN EXTERNALLY</button></div></div>`;stage.querySelector("[data-reader-retry]").onclick=()=>render().catch(showReaderError);stage.querySelector("[data-reader-open-external]").onclick=()=>externalOpen(path).catch(openError=>toast("OPEN FAILED",openError.message));updateChrome()};
    const previous=()=>{if(stripController){stripController.previous();return}const frame=stage.querySelector(".vault-reader-epub");if(frame&&frame.dataset.readerReady!=="true")return;if(frame){spread=Number(frame.dataset.readerSpread||0);maxSpreads=Number(frame.dataset.readerSpreads||1)}if(spread>0){turnTo(frame,spread-1);return}if(index>0){index=Math.max(0,index-(comicArchive&&layout==="spread"?2:1));render(manifest.format==="EPUB"?"last":0).catch(showReaderError)}};
    const next=()=>{if(stripController){stripController.next();return}const frame=stage.querySelector(".vault-reader-epub");if(frame&&frame.dataset.readerReady!=="true")return;if(frame){spread=Number(frame.dataset.readerSpread||0);maxSpreads=Number(frame.dataset.readerSpreads||1)}if(spread<maxSpreads-1){turnTo(frame,spread+1);return}if(index<Number(manifest.pageCount||1)-1){index=Math.min(Number(manifest.pageCount||1)-1,index+(comicArchive&&layout==="spread"?2:1));render().catch(showReaderError)}};
    root.querySelector("[data-reader-prev]").onclick=previous;root.querySelector("[data-reader-next]").onclick=next;range.oninput=()=>{index=Number(range.value);if(stripController)stripController.goTo(index,{behavior:"auto"});else render().catch(showReaderError)};
    root.querySelector("[data-reader-library]").onclick=()=>{persistPosition();finish();closeModal()};root.querySelector("[data-close]").onclick=()=>{persistPosition();finish();closeModal()};
    root.querySelector("[data-reader-text]").onclick=()=>{const panel=root.querySelector("[data-reader-settings]");panel.hidden=!panel.hidden};
    root.querySelector("[data-reader-font-size]").oninput=event=>{fontSize=Number(event.target.value);root.querySelector("[data-reader-font-label]").textContent=`${fontSize}px`;clearTimeout(reader._fontTimer);reader._fontTimer=setTimeout(()=>render().catch(error=>toast("READER PAUSED",error.message)),160)};
    root.querySelectorAll("button[data-reader-theme]").forEach(button=>button.onclick=event=>{event.stopPropagation();theme=button.dataset.readerTheme;reader.dataset.readerTheme=theme;root.querySelectorAll("button[data-reader-theme]").forEach(value=>value.classList.toggle("active",value===button));render().catch(error=>toast("READER PAUSED",error.message))});
    root.querySelectorAll("button[data-reader-fit]").forEach(button=>button.onclick=event=>{event.stopPropagation();imageFit=button.dataset.readerFit;reader.dataset.readerImageFit=imageFit;root.querySelectorAll("button[data-reader-fit]").forEach(value=>value.classList.toggle("active",value===button));update(save=>{const meta=readingMeta(save.items[itemId]);if(meta)meta.readerImageFit=imageFit});stage.querySelector(".vault-reader-image-spread")?.scrollTo({top:0,left:0})});
    const setReaderMode=mode=>{layout=mode;reader.dataset.readerLayout=layout;root.querySelectorAll("[data-reader-mode]").forEach(value=>value.classList.toggle("active",value.dataset.readerMode===layout));render().catch(showReaderError)};root.querySelectorAll("[data-reader-mode]").forEach(button=>button.onclick=event=>{event.stopPropagation();setReaderMode(button.dataset.readerMode)});root.querySelector("button[data-reader-layout]").onclick=event=>{event.stopPropagation();const modes=comicArchive?["single","spread","continuous","webtoon"]:["single","spread","continuous"],position=modes.indexOf(layout);setReaderMode(modes[(position+1)%modes.length])};
    root.querySelector("[data-reader-direction-toggle]")?.addEventListener("click",event=>{direction=direction==="rtl"?"ltr":"rtl";reader.dataset.readerDirection=direction;event.currentTarget.classList.toggle("active",direction==="rtl");event.currentTarget.textContent=direction==="rtl"?"MANGA RTL":"LEFT TO RIGHT";persistPosition();if(stripController)render().catch(showReaderError)});
    root.querySelector("[data-reader-divider-toggle]").onclick=event=>{event.stopPropagation();divider=!divider;reader.dataset.readerDivider=divider?"on":"off";event.currentTarget.classList.toggle("active",divider);event.currentTarget.textContent=`CENTER LINE ${divider?"ON":"OFF"}`;update(save=>{const meta=readingMeta(save.items[itemId]);if(meta)meta.readerDivider=divider})};
    root.querySelector("[data-reader-bookmark]").onclick=()=>{let active=false;update(save=>{const meta=readingMeta(save.items[itemId]);meta.readerBookmarks||=[];const found=meta.readerBookmarks.findIndex(mark=>Number(mark.index)===index&&Number(mark.spread||0)===spread);if(found>=0)meta.readerBookmarks.splice(found,1);else{meta.readerBookmarks.push({index,spread,label:manifest.pages?.[index]?.label||`Chapter ${index+1}`,createdAt:new Date().toISOString()});active=true}});updateChrome();toast(active?"BOOKMARK ADDED":"BOOKMARK REMOVED",label.textContent)};
    const drawer=root.querySelector("[data-reader-drawer]");root.querySelectorAll("[data-reader-toc]").forEach(button=>button.onclick=()=>{drawer.hidden=false;updateChrome()});root.querySelector("[data-reader-drawer-close]").onclick=()=>drawer.hidden=true;
    drawer.onclick=event=>{const chapter=event.target.closest("[data-reader-chapter]")?.dataset.readerChapter;if(chapter!==undefined){index=Number(chapter);drawer.hidden=true;return render().catch(showReaderError)}const remove=event.target.closest("[data-reader-bookmark-remove]")?.dataset.readerBookmarkRemove;if(remove!==undefined){update(save=>{readingMeta(save.items[itemId]).readerBookmarks?.splice(Number(remove),1)});updateChrome();return}const rename=event.target.closest("[data-reader-bookmark-rename]")?.dataset.readerBookmarkRename;if(rename!==undefined){const marks=readingMeta(getState().items[itemId])?.readerBookmarks||[],name=prompt("Bookmark name:",marks[Number(rename)]?.label||"")?.trim();if(name)update(save=>{const mark=readingMeta(save.items[itemId]).readerBookmarks?.[Number(rename)];if(mark)mark.label=name});updateChrome();return}const bookmarkPosition=event.target.closest("[data-reader-bookmark-open]")?.dataset.readerBookmarkOpen;if(bookmarkPosition!==undefined){const mark=(readingMeta(getState().items[itemId])?.readerBookmarks||[])[Number(bookmarkPosition)];if(!mark)return;index=Number(mark.index||0);drawer.hidden=true;return render(Number(mark.spread||0)).catch(showReaderError)}};
    root.querySelector("[data-reader-search]").onclick=()=>{const query=prompt("Search this chapter for:")?.trim();if(!query)return;const frame=stage.querySelector(".vault-reader-epub"),text=frame?.shadowRoot?.querySelector(".vault-epub-flow")?.innerText||stage.querySelector("iframe")?.contentDocument?.body?.innerText||stage.textContent||"";toast(text.toLowerCase().includes(query.toLowerCase())?"FOUND IN THIS CHAPTER":"NOT FOUND IN THIS CHAPTER",query)};
    root.querySelector("[data-reader-fullscreen]").onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await reader.requestFullscreen()}catch{toast("FULLSCREEN UNAVAILABLE","Windows could not switch display modes.")}};
    root.querySelector(".modal-backdrop").addEventListener("click",event=>{if(event.target.classList.contains("modal-backdrop")){persistPosition();finish()}},true);
    const book=root.querySelector("[data-reader-book]");book.addEventListener("click",event=>{if(stripController||event.target.closest("button,input,a")||event.detail===0)return;const bounds=book.getBoundingClientRect(),ratio=(event.clientX-bounds.left)/Math.max(1,bounds.width);if(ratio<.22)previous();else if(ratio>.78)next()});
    resizeObserver=new ResizeObserver(()=>{clearTimeout(reader._resizeTimer);reader._resizeTimer=setTimeout(()=>{if(stripController)stripController.recenter();else{const frame=stage.querySelector(".vault-reader-epub");if(frame)positionFrame(frame)}},140)});resizeObserver.observe(book);
    const keys=event=>{if(!reader.isConnected){document.removeEventListener("keydown",keys,true);return}if(event.key==="Escape"){persistPosition();finish()}else if(event.key==="ArrowLeft"){event.preventDefault();direction==="rtl"?next():previous()}else if(event.key==="ArrowRight"){event.preventDefault();direction==="rtl"?previous():next()}};document.addEventListener("keydown",keys,true);
    await render().catch(showReaderError);return true;
  }catch(error){openModal({title:"EMBEDDED READER PAUSED",body:`<p>${esc(error.message)}</p><p>You can still open this file in its normal Windows reader.</p>`,actions:[{label:"OPEN EXTERNALLY",primary:true,handler:async()=>{try{await externalOpen(path);closeModal()}catch(openError){toast("OPEN FAILED",openError.message)}}},{label:"CLOSE",handler:()=>closeModal()}]});return false}
}
