import { categorizeHalloweenEntry } from "./halloweenCategories.js";

const withCategories = entry => ({
  ...entry,
  categories: categorizeHalloweenEntry(entry)
});

const movie = (title, year, tags = [], requires = []) => withCategories({
  kind: "movie", title, year, tags, requires
});
const show = (title, year, tags = [], requires = []) => withCategories({
  kind: "show", format: "series", title, year, tags, requires
});
const special = (series, title, year, tags = []) => withCategories({
  kind: "show", format: "special", series, title: `${series} — ${title}`, year,
  tags: ["special", ...tags], requires: []
});

export const HALLOWEEN_MOVIES = [
  // Foundational / classic horror.
  movie("The Cabinet of Dr. Caligari", 1920, ["classic","gothic"]),
  movie("Nosferatu", 1922, ["classic","vampire"]),
  movie("Häxan", 1922, ["classic","occult"]),
  movie("The Phantom of the Opera", 1925, ["classic","gothic"]),
  movie("Dracula", 1931, ["classic","vampire"]),
  movie("Frankenstein", 1931, ["classic","monster"]),
  movie("The Mummy", 1932, ["classic","monster"]),
  movie("The Invisible Man", 1933, ["classic","monster"]),
  movie("Bride of Frankenstein", 1935, ["classic","monster"], [{ title: "Frankenstein", year: 1931 }]),
  movie("The Wolf Man", 1941, ["classic","werewolf"]),
  movie("Cat People", 1942, ["classic","supernatural"]),
  movie("I Walked with a Zombie", 1943, ["classic","zombie"]),
  movie("House on Haunted Hill", 1959, ["classic","haunted"]),
  movie("The Tingler", 1959, ["classic","camp"]),
  movie("Black Sunday", 1960, ["classic","witch"]),
  movie("Psycho", 1960, ["classic","slasher"]),
  movie("Carnival of Souls", 1962, ["classic","surreal"]),
  movie("The Innocents", 1961, ["classic","haunted"]),
  movie("The Haunting", 1963, ["classic","haunted"]),
  movie("The Masque of the Red Death", 1964, ["classic","gothic"]),
  movie("Rosemary's Baby", 1968, ["occult","classic"]),
  movie("Night of the Living Dead", 1968, ["zombie","classic"]),
  movie("The Wicker Man", 1973, ["folk","classic"]),
  movie("Don't Look Now", 1973, ["supernatural","classic"]),
  movie("The Exorcist", 1973, ["possession","classic"]),
  movie("Black Christmas", 1974, ["slasher","classic"]),
  movie("The Texas Chain Saw Massacre", 1974, ["slasher","classic"]),
  movie("Jaws", 1975, ["creature","classic"]),
  movie("Carrie", 1976, ["supernatural","classic"]),
  movie("Suspiria", 1977, ["witch","giallo"]),
  movie("Dawn of the Dead", 1978, ["zombie","classic"]),
  movie("Invasion of the Body Snatchers", 1978, ["sci-fi","body-horror"]),
  movie("Phantasm", 1979, ["surreal","franchise"]),
  movie("Alien", 1979, ["sci-fi","creature"]),

  // 1980s video-store horror.
  movie("The Fog", 1980, ["ghost","carpenter"]),
  movie("The Changeling", 1980, ["haunted","ghost"]),
  movie("The Howling", 1981, ["werewolf"]),
  movie("An American Werewolf in London", 1981, ["werewolf","fun"]),
  movie("The Evil Dead", 1981, ["cabin","franchise"]),
  movie("The Thing", 1982, ["creature","sci-fi","body-horror"]),
  movie("Creepshow", 1982, ["anthology","fun"]),
  movie("Poltergeist", 1982, ["haunted","fun"]),
  movie("Videodrome", 1983, ["body-horror","wtf"]),
  movie("Christine", 1983, ["carpenter","supernatural"]),
  movie("A Nightmare on Elm Street", 1984, ["slasher","franchise"]),
  movie("Gremlins", 1984, ["creature","fun","holiday"]),
  movie("The Return of the Living Dead", 1985, ["zombie","fun","punk"]),
  movie("Re-Animator", 1985, ["lovecraft","fun","gore"]),
  movie("Fright Night", 1985, ["vampire","fun"]),
  movie("Day of the Dead", 1985, ["zombie"]),
  movie("Lifeforce", 1985, ["sci-fi","vampire","wtf"]),
  movie("House", 1985, ["haunted","fun"]),
  movie("Chopping Mall", 1986, ["slasher","sci-fi","fun"]),
  movie("The Fly", 1986, ["body-horror"]),
  movie("Night of the Creeps", 1986, ["alien","zombie","fun"]),
  movie("Little Shop of Horrors", 1986, ["musical","creature","fun"]),
  movie("Critters", 1986, ["creature","fun"]),
  movie("From Beyond", 1986, ["lovecraft","body-horror"]),
  movie("The Lost Boys", 1987, ["vampire","fun"]),
  movie("Hellraiser", 1987, ["supernatural","franchise"]),
  movie("Prince of Darkness", 1987, ["occult","carpenter"]),
  movie("Near Dark", 1987, ["vampire"]),
  movie("The Monster Squad", 1987, ["monster","fun"]),
  movie("Pumpkinhead", 1988, ["creature","folk"]),
  movie("Child's Play", 1988, ["slasher","doll","franchise"]),
  movie("Killer Klowns from Outer Space", 1988, ["alien","camp","fun"]),
  movie("Brain Damage", 1988, ["body-horror","camp"]),
  movie("The Blob", 1988, ["creature","body-horror"]),
  movie("Beetlejuice", 1988, ["ghost","comedy","fun"]),
  movie("Society", 1989, ["body-horror","wtf"]),
  movie("Pet Sematary", 1989, ["supernatural"]),
  movie("The 'Burbs", 1989, ["comedy","fun"]),
  movie("Shocker", 1989, ["slasher","supernatural"]),

  // 1990s.
  movie("Tremors", 1990, ["creature","fun"]),
  movie("Arachnophobia", 1990, ["creature","fun"]),
  movie("Jacob's Ladder", 1990, ["psychological","surreal"]),
  movie("Misery", 1990, ["psychological"]),
  movie("Candyman", 1992, ["supernatural","slasher"]),
  movie("Dead Alive", 1992, ["zombie","gore","fun"]),
  movie("Army of Darkness", 1992, ["evil-dead","fun"]),
  movie("The People Under the Stairs", 1991, ["fun","social"]),
  movie("Split Second", 1992, ["creature","sci-fi"]),
  movie("Body Bags", 1993, ["anthology","fun"]),
  movie("Leprechaun", 1993, ["creature","camp","franchise"]),
  movie("Cronos", 1993, ["vampire","international"]),
  movie("In the Mouth of Madness", 1994, ["lovecraft","carpenter"]),
  movie("Cemetery Man", 1994, ["zombie","surreal","fun"]),
  movie("Brainscan", 1994, ["tech","slasher"]),
  movie("Wes Craven's New Nightmare", 1994, ["meta","slasher"]),
  movie("Tales from the Hood", 1995, ["anthology","social"]),
  movie("Demon Knight", 1995, ["demons","fun"]),
  movie("Scream", 1996, ["slasher","meta","franchise"]),
  movie("The Craft", 1996, ["witch","teen"]),
  movie("From Dusk Till Dawn", 1996, ["vampire","fun"]),
  movie("The Frighteners", 1996, ["ghost","fun"]),
  movie("Event Horizon", 1997, ["space","cosmic"]),
  movie("Mimic", 1997, ["creature"]),
  movie("Anaconda", 1997, ["creature","camp"]),
  movie("Deep Rising", 1998, ["creature","fun"]),
  movie("The Faculty", 1998, ["alien","teen","fun"]),
  movie("Urban Legend", 1998, ["slasher","teen"]),
  movie("Bride of Chucky", 1998, ["slasher","camp","fun"]),
  movie("Cube", 1997, ["sci-fi","trap"]),
  movie("Wishmaster", 1997, ["supernatural","camp"]),
  movie("Idle Hands", 1999, ["comedy","teen","fun"]),
  movie("Lake Placid", 1999, ["creature","fun"]),
  movie("Ravenous", 1999, ["cannibal","dark-comedy"]),
  movie("The Blair Witch Project", 1999, ["found-footage","folk"]),
  movie("Sleepy Hollow", 1999, ["gothic","fun"]),
  // 2000s.
  movie("Ginger Snaps", 2000, ["werewolf","teen"]),
  movie("Final Destination", 2000, ["death","franchise"]),
  movie("American Psycho", 2000, ["psychological","dark-comedy"]),
  movie("The Cell", 2000, ["surreal","psychological"]),
  movie("Session 9", 2001, ["psychological","haunted"]),
  movie("Frailty", 2001, ["psychological","religious"]),
  movie("The Others", 2001, ["ghost","gothic"]),
  movie("Dog Soldiers", 2002, ["werewolf","action"]),
  movie("28 Days Later", 2002, ["zombie","apocalypse"]),
  movie("The Ring", 2002, ["curse","supernatural"]),
  movie("May", 2002, ["psychological","weird"]),
  movie("Cabin Fever", 2002, ["infection","gross"]),
  movie("House of 1000 Corpses", 2003, ["grindhouse","slasher"]),
  movie("Dawn of the Dead", 2004, ["zombie","action"]),
  movie("Shaun of the Dead", 2004, ["zombie","comedy","fun"]),
  movie("Saw", 2004, ["trap","franchise"]),
  movie("Shutter", 2004, ["ghost","international"]),
  movie("The Descent", 2005, ["creature","cave"]),
  movie("Hostel", 2005, ["gore"]),
  movie("Slither", 2006, ["creature","comedy","gross"]),
  movie("Behind the Mask: The Rise of Leslie Vernon", 2006, ["mockumentary","slasher","fun"]),
  movie("Black Sheep", 2006, ["creature","comedy","gross"]),
  movie("The Mist", 2007, ["creature","cosmic"]),
  movie("Trick 'r Treat", 2007, ["halloween","anthology","fun"]),
  movie("[REC]", 2007, ["found-footage","infection"]),
  movie("Paranormal Activity", 2007, ["found-footage","ghost"]),
  movie("Drag Me to Hell", 2009, ["curse","fun"]),
  movie("Orphan", 2009, ["thriller","twist"]),
  movie("Triangle", 2009, ["time-loop","sci-fi","psychological"]),
  movie("Jennifer's Body", 2009, ["demon","teen","comedy"]),
  movie("Zombieland", 2009, ["zombie","comedy","fun"]),
  movie("Dead Snow", 2009, ["zombie","comedy","gore"]),

  // 2010s.
  movie("Tucker and Dale vs. Evil", 2010, ["comedy","slasher","fun"]),
  movie("Insidious", 2010, ["supernatural","franchise"]),
  movie("The Cabin in the Woods", 2011, ["meta","comedy","fun"]),
  movie("Sinister", 2012, ["supernatural","found-footage"]),
  movie("The Bay", 2012, ["found-footage","creature"]),
  movie("V/H/S", 2012, ["found-footage","anthology"]),
  movie("You're Next", 2011, ["home-invasion","fun"]),
  movie("The Conjuring", 2013, ["supernatural","franchise"]),
  movie("Oculus", 2013, ["haunted-object","supernatural"]),
  movie("Creep", 2014, ["found-footage","psychological"]),
  movie("What We Do in the Shadows", 2014, ["mockumentary","vampire","comedy"]),
  movie("It Follows", 2014, ["curse","supernatural"]),
  movie("The Guest", 2014, ["thriller","fun"]),
  movie("Housebound", 2014, ["haunted","comedy","fun"]),
  movie("The Taking of Deborah Logan", 2014, ["found-footage","possession"]),
  movie("The Final Girls", 2015, ["slasher","meta","comedy"]),
  movie("Krampus", 2015, ["holiday","creature","fun"]),
  movie("Green Room", 2015, ["survival","punk"]),
  movie("The Witch", 2015, ["folk","witch"]),
  movie("The Invitation", 2015, ["cult","slow-burn"]),
  movie("Train to Busan", 2016, ["zombie","international"]),
  movie("The Autopsy of Jane Doe", 2016, ["supernatural","mystery"]),
  movie("Hush", 2016, ["home-invasion"]),
  movie("Better Watch Out", 2016, ["holiday","dark-comedy"]),
  movie("Get Out", 2017, ["social","psychological"]),
  movie("Happy Death Day", 2017, ["slasher","time-loop","fun"]),
  movie("Terrified", 2017, ["supernatural","international"]),
  movie("Upgrade", 2018, ["sci-fi","body-horror","fun"]),
  movie("Hereditary", 2018, ["occult","family"]),
  movie("Mandy", 2018, ["psychedelic","revenge","wtf"]),
  movie("Overlord", 2018, ["zombie","war","fun"]),
  movie("Gonjiam: Haunted Asylum", 2018, ["found-footage","international"]),
  movie("Ready or Not", 2019, ["comedy","survival","fun"]),
  movie("Doctor Sleep", 2019, ["supernatural"]),
  movie("Crawl", 2019, ["creature","survival"]),
  movie("Us", 2019, ["social","surreal"]),
  movie("Scary Stories to Tell in the Dark", 2019, ["monster","teen"]),
  movie("The Lighthouse", 2019, ["psychological","surreal"]),
  movie("Color Out of Space", 2019, ["lovecraft","body-horror"]),
  movie("One Cut of the Dead", 2017, ["zombie","comedy","meta"]),
  movie("Deathgasm", 2015, ["metal","comedy","gore"]),
  movie("Grabbers", 2012, ["creature","comedy","fun"]),
  movie("Final Prayer", 2013, ["found-footage","folk"]),
  movie("Freaks of Nature", 2015, ["comedy","creature","fun"]),
  movie("You Might Be the Killer", 2018, ["slasher","comedy","meta"]),

  // 2020s.
  movie("Host", 2020, ["found-footage","ghost"]),
  movie("The Invisible Man", 2020, ["thriller","sci-fi"]),
  movie("Freaky", 2020, ["slasher","comedy","fun"]),
  movie("Possessor", 2020, ["sci-fi","body-horror"]),
  movie("Anything for Jackson", 2020, ["occult","dark-comedy"]),
  movie("Psycho Goreman", 2020, ["creature","comedy","gore"]),
  movie("Malignant", 2021, ["wtf","giallo","fun"]),
  movie("Werewolves Within", 2021, ["werewolf","comedy","fun"]),
  movie("The Sadness", 2021, ["infection","gore","international"]),
  movie("Barbarian", 2022, ["wtf","creature"]),
  movie("Deadstream", 2022, ["found-footage","comedy","fun"]),
  movie("Smile", 2022, ["curse","supernatural"]),
  movie("X", 2022, ["slasher"]),
  movie("Pearl", 2022, ["psychological","slasher"]),
  movie("Bodies Bodies Bodies", 2022, ["comedy","slasher"]),
  movie("Fresh", 2022, ["dark-comedy","cannibal"]),
  movie("Hellbender", 2021, ["witch","indie"]),
  movie("Incantation", 2022, ["found-footage","international"]),
  movie("Talk to Me", 2022, ["possession","teen"]),
  movie("When Evil Lurks", 2023, ["possession","international"]),
  movie("Evil Dead Rise", 2023, ["possession","franchise"], [
    { title: "The Evil Dead", year: 1981 },
    { title: "Evil Dead II", year: 1987 },
    { title: "Army of Darkness", year: 1992 },
    { title: "Evil Dead", year: 2013 }
  ]),
  movie("Renfield", 2023, ["vampire","comedy","fun"]),
  movie("M3GAN", 2022, ["doll","sci-fi","fun"]),
  movie("No One Will Save You", 2023, ["alien","sci-fi"]),
  movie("Cobweb", 2023, ["creature","haunted"]),
  movie("Late Night with the Devil", 2023, ["found-footage","possession","fun"]),
  movie("Abigail", 2024, ["vampire","comedy","fun"]),
  movie("The Substance", 2024, ["body-horror","wtf"]),
  movie("Oddity", 2024, ["supernatural","mystery"]),
  movie("Longlegs", 2024, ["occult","crime"]),
  movie("Smile 2", 2024, ["curse"], [{ title: "Smile", year: 2022 }]),
  movie("Terrifier 3", 2024, ["slasher","gore"], [
    { title: "Terrifier", year: 2016 },
    { title: "Terrifier 2", year: 2022 }
  ]),
  movie("Heretic", 2024, ["psychological"]),
  movie("Nosferatu", 2024, ["vampire","gothic"]),
  movie("Companion", 2025, ["sci-fi","dark-comedy"]),
  movie("Sinners", 2025, ["vampire","period"]),
  movie("Weapons", 2025, ["mystery","supernatural"]),
  movie("Good Boy", 2025, ["supernatural"]),
  movie("The Monkey", 2025, ["curse","dark-comedy"]),
  movie("Heart Eyes", 2025, ["slasher","romance","fun"]),
  movie("Clown in a Cornfield", 2025, ["slasher"]),
  movie("Bring Her Back", 2025, ["occult"]),
  movie("Dangerous Animals", 2025, ["shark","thriller"]),
  movie("Together", 2025, ["body-horror","relationship"]),
  movie("The Long Walk", 2025, ["dystopian","horror"]),
  movie("Resident Evil", 2026, ["zombie","sci-fi"]),
  movie("Teenage Sex and Death at Camp Miasma", 2026, ["slasher","meta"]),
  movie("Leviticus", 2026, ["monster","queer"]),
  movie("Hokum", 2026, ["haunted","folk"]),
  movie("Backrooms", 2026, ["found-footage","liminal"]),
  movie("Colony", 2026, ["horror","recent"]),
  movie("Hope", 2026, ["horror","recent"]),
  movie("Primate", 2026, ["creature","recent"]),
  movie("28 Years Later: The Bone Temple", 2026, ["zombie","recent"], [
    { title: "28 Days Later", year: 2002 },
    { title: "28 Weeks Later", year: 2007 },
    { title: "28 Years Later", year: 2025 }
  ]),
  movie("Deathgasm II: Goremageddon", 2026, ["metal","comedy","gore"], [{ title: "Deathgasm", year: 2015 }]),

  // International / extreme / weird.
  movie("Ringu", 1998, ["international","curse"]),
  movie("Ju-On: The Grudge", 2002, ["international","ghost"]),
  movie("Pulse", 2001, ["international","tech","ghost"]),
  movie("Dark Water", 2002, ["international","ghost"]),
  movie("Noroi: The Curse", 2005, ["found-footage","international"]),
  movie("Audition", 1999, ["international","psychological"]),
  movie("The Host", 2006, ["international","creature"]),
  movie("The Wailing", 2016, ["international","occult"]),
  movie("The Medium", 2021, ["found-footage","international"]),
  movie("Satan's Slaves", 2017, ["international","supernatural"]),
  movie("Impetigore", 2019, ["international","folk"]),
  movie("The Queen of Black Magic", 2019, ["international","witch"]),
  movie("Tigers Are Not Afraid", 2017, ["international","ghost"]),
  movie("The Orphanage", 2007, ["international","ghost"]),
  movie("Veronica", 2017, ["international","possession"]),
  movie("Raw", 2016, ["body-horror","international"]),
  movie("Titane", 2021, ["body-horror","wtf","international"]),
  movie("Inside", 2007, ["extreme","international"]),
  movie("High Tension", 2003, ["extreme","international"]),
  movie("Martyrs", 2008, ["extreme","international"]),
  movie("Let the Right One In", 2008, ["vampire","international"]),
  movie("Rare Exports", 2010, ["holiday","creature","international"]),
  movie("Goodnight Mommy", 2014, ["psychological","international"]),
  movie("Speak No Evil", 2022, ["psychological","international"]),

  // Found footage / mockumentary deep bench.
  movie("The Last Broadcast", 1998, ["found-footage"]),
  movie("Lake Mungo", 2008, ["found-footage","ghost"]),
  movie("Grave Encounters", 2011, ["found-footage","haunted"]),
  movie("Hell House LLC", 2015, ["found-footage","haunted"]),
  movie("As Above, So Below", 2014, ["found-footage","occult"]),
  movie("The Visit", 2015, ["found-footage","thriller"]),
  movie("Butterfly Kisses", 2018, ["found-footage","urban-legend"]),
  movie("Savageland", 2015, ["mockumentary","zombie"]),
  movie("Horror in the High Desert", 2021, ["found-footage","cryptid"]),
  movie("The Tunnel", 2011, ["found-footage","creature"]),
  movie("Afflicted", 2013, ["found-footage","vampire"]),
  movie("Exists", 2014, ["found-footage","bigfoot"]),
  movie("Trollhunter", 2010, ["found-footage","creature","fun"]),

  // Creature/B-movie/Syfy candy.
  movie("Splinter", 2008, ["creature","body-horror"]),
  movie("Feast", 2005, ["creature","gore","fun"]),
  movie("The Relic", 1997, ["creature"]),
  movie("Eight Legged Freaks", 2002, ["creature","comedy","fun"]),
  movie("Underwater", 2020, ["creature","sci-fi"]),
  movie("Sea Fever", 2019, ["creature","sci-fi"]),
  movie("Sputnik", 2020, ["creature","sci-fi"]),
  movie("Nope", 2022, ["creature","sci-fi"]),
  movie("Sting", 2024, ["creature","spider"]),
  movie("Arcadian", 2024, ["creature","post-apocalypse"]),
  movie("Mega Shark vs. Giant Octopus", 2009, ["syfy","creature","camp"]),
  movie("Boa vs. Python", 2004, ["syfy","creature","camp"]),
  movie("Mansquito", 2005, ["syfy","creature","camp"]),
  movie("Frankenfish", 2004, ["syfy","creature","camp"]),
  movie("Snakehead Terror", 2004, ["syfy","creature","camp"]),
  movie("Dinoshark", 2010, ["syfy","creature","camp"]),
  movie("Piranhaconda", 2012, ["syfy","creature","camp"]),
  movie("Mega Python vs. Gatoroid", 2011, ["syfy","creature","camp"]),
  movie("Sharktopus", 2010, ["syfy","creature","camp"]),
  movie("Ghost Shark", 2013, ["syfy","creature","camp"]),
  movie("Jersey Shore Shark Attack", 2012, ["syfy","creature","camp"]),
  movie("Lavalantula", 2015, ["syfy","creature","camp"]),
  movie("2 Lava 2 Lantula!", 2016, ["syfy","creature","camp"], [{ title: "Lavalantula", year: 2015 }]),
  movie("RoboShark", 2015, ["syfy","creature","camp"]),
  movie("Arachnoquake", 2012, ["syfy","creature","camp"]),
  movie("Bermuda Tentacles", 2014, ["syfy","creature","camp"]),
  movie("Battledogs", 2013, ["syfy","werewolf","camp"]),
  movie("Zombeavers", 2014, ["creature","comedy","camp"]),

  // Family-spooky / Halloween candy.
  movie("The Addams Family", 1991, ["family","gothic","comedy"]),
  movie("Addams Family Values", 1993, ["family","gothic","comedy"], [{ title: "The Addams Family", year: 1991 }]),
  movie("Hocus Pocus", 1993, ["family","witch","comedy"]),
  movie("Casper", 1995, ["family","ghost"]),
  movie("Ernest Scared Stupid", 1991, ["family","creature","comedy"]),
  movie("The Witches", 1990, ["family","witch"]),
  movie("The Nightmare Before Christmas", 1993, ["family","animation","musical"]),
  movie("Halloweentown", 1998, ["family","witch"]),
  movie("Tower of Terror", 1997, ["family","ghost"]),
  movie("Under Wraps", 1997, ["family","mummy"]),
  movie("Mom's Got a Date with a Vampire", 2000, ["family","vampire"]),
  movie("Phantom of the Megaplex", 2000, ["family","mystery"]),
  movie("Monster House", 2006, ["family","animation","haunted"]),
  movie("Coraline", 2009, ["family","animation","dark-fantasy"]),
  movie("ParaNorman", 2012, ["family","animation","zombie"]),
  movie("Frankenweenie", 2012, ["family","animation","monster"]),
  movie("Goosebumps", 2015, ["family","monster","comedy"]),
  movie("The House with a Clock in Its Walls", 2018, ["family","witch"]),
  movie("Hubie Halloween", 2020, ["family","comedy","halloween"]),
  movie("Nightbooks", 2021, ["family","witch"]),
  movie("The Curse of Bridge Hollow", 2022, ["family","halloween","comedy"]),
  movie("We Have a Ghost", 2023, ["family","ghost","comedy"]),
  movie("Haunted Mansion", 2023, ["family","ghost","comedy"]),

  // Camp / horror-comedy / musicals / weird fun.
  movie("The Rocky Horror Picture Show", 1975, ["musical","camp"]),
  movie("Elvira: Mistress of the Dark", 1988, ["comedy","camp"]),
  movie("Death Becomes Her", 1992, ["comedy","body-horror","camp"]),
  movie("Repo! The Genetic Opera", 2008, ["musical","gore","camp"]),
  movie("Detention", 2011, ["slasher","comedy","wtf"]),
  movie("Cooties", 2014, ["zombie","comedy"]),
  movie("Scouts Guide to the Zombie Apocalypse", 2015, ["zombie","comedy","fun"]),
  movie("The Babysitter", 2017, ["slasher","comedy","fun"]),
  movie("Mayhem", 2017, ["infection","comedy","action"]),
  movie("Bloodsucking Bastards", 2015, ["vampire","comedy"]),
  movie("Little Monsters", 2019, ["zombie","comedy","fun"]),
  movie("Extra Ordinary", 2019, ["ghost","comedy","fun"]),
  movie("Villains", 2019, ["dark-comedy","crime"]),
  movie("Satanic Panic", 2019, ["occult","comedy","fun"]),
  movie("Boys from County Hell", 2020, ["vampire","comedy"]),
  movie("Scare Me", 2020, ["comedy","storytelling"]),
  movie("Vicious Fun", 2020, ["slasher","comedy","fun"]),
  movie("The Wolf of Snow Hollow", 2020, ["werewolf","dark-comedy"]),
  movie("Scare Package", 2019, ["anthology","comedy","fun"]),
  movie("The Mortuary Collection", 2019, ["anthology","fun"]),
  movie("Onyx the Fortuitous and the Talisman of Souls", 2023, ["occult","comedy","fun"]),
  movie("Destroy All Neighbors", 2024, ["comedy","gore","music"]),

  // Giallo / slashers / body horror deep bench.
  movie("Blood and Black Lace", 1964, ["giallo"]),
  movie("A Bay of Blood", 1971, ["giallo","slasher"]),
  movie("Deep Red", 1975, ["giallo"]),
  movie("Tenebrae", 1982, ["giallo"]),
  movie("Phenomena", 1985, ["giallo","supernatural"]),
  movie("Opera", 1987, ["giallo"]),
  movie("Tourist Trap", 1979, ["slasher","weird"]),
  movie("My Bloody Valentine", 1981, ["slasher"]),
  movie("The Burning", 1981, ["slasher"]),
  movie("The Prowler", 1981, ["slasher"]),
  movie("Pieces", 1982, ["slasher","camp"]),
  movie("April Fool's Day", 1986, ["slasher","mystery"]),
  movie("StageFright", 1987, ["slasher","giallo"]),
  movie("Intruder", 1989, ["slasher"]),
  movie("Maniac Cop", 1988, ["slasher","supernatural"]),
  movie("Scanners", 1981, ["body-horror","sci-fi"]),
  movie("The Brood", 1979, ["body-horror"]),
  movie("Dead Ringers", 1988, ["body-horror","psychological"]),
  movie("Tetsuo: The Iron Man", 1989, ["body-horror","wtf","international"])
];
export const HALLOWEEN_SHOWS = [
  // Full horror / supernatural series.
  show("The Twilight Zone", 1959, ["anthology","classic"]),
  show("The Outer Limits", 1963, ["anthology","sci-fi"]),
  show("Tales from the Darkside", 1983, ["anthology"]),
  show("Tales from the Crypt", 1989, ["anthology","fun"]),
  show("Monsters", 1988, ["anthology","creature"]),
  show("Are You Afraid of the Dark?", 1990, ["anthology","family"]),
  show("Goosebumps", 1995, ["anthology","family"]),
  show("Eerie, Indiana", 1991, ["family","weird"]),
  show("The X-Files", 1993, ["monster","sci-fi"]),
  show("Buffy the Vampire Slayer", 1997, ["vampire","fun"]),
  show("Angel", 1999, ["vampire","supernatural"]),
  show("Millennium", 1996, ["occult","crime"]),
  show("American Gothic", 1995, ["supernatural","southern-gothic"]),
  show("Masters of Horror", 2005, ["anthology"]),
  show("Fear Itself", 2008, ["anthology"]),
  show("Dead Set", 2008, ["zombie"]),
  show("Harper's Island", 2009, ["slasher","mystery"]),
  show("Todd and the Book of Pure Evil", 2010, ["comedy","gore","fun"]),
  show("Being Human", 2008, ["supernatural","comedy"]),
  show("American Horror Story", 2011, ["anthology"]),
  show("Hannibal", 2013, ["psychological","crime"]),
  show("Bates Motel", 2013, ["psychological"]),
  show("Penny Dreadful", 2014, ["gothic","monster"]),
  show("Salem", 2014, ["witch"]),
  show("The Strain", 2014, ["vampire","creature"]),
  show("Scream", 2015, ["slasher"]),
  show("Ash vs Evil Dead", 2015, ["comedy","gore","fun"], [
    { title: "The Evil Dead", year: 1981 },
    { title: "Evil Dead II", year: 1987 },
    { title: "Army of Darkness", year: 1992 }
  ]),
  show("Channel Zero", 2016, ["anthology","weird"]),
  show("Stan Against Evil", 2016, ["comedy","monster","fun"]),
  show("Santa Clarita Diet", 2017, ["zombie","comedy","fun"]),
  show("The Exorcist", 2016, ["possession"], [{ title: "The Exorcist", year: 1973 }]),
  show("Slasher", 2016, ["slasher","anthology"]),
  show("Castle Rock", 2018, ["stephen-king","supernatural"]),
  show("The Haunting of Hill House", 2018, ["haunted","family"]),
  show("The Terror", 2018, ["historical","supernatural"]),
  show("Chilling Adventures of Sabrina", 2018, ["witch","teen"]),
  show("Marianne", 2019, ["witch","international"]),
  show("Creepshow", 2019, ["anthology","fun"]),
  show("Evil", 2019, ["supernatural","procedural"]),
  show("NOS4A2", 2019, ["supernatural"]),
  show("What We Do in the Shadows", 2019, ["vampire","comedy","fun"]),
  show("Wellington Paranormal", 2018, ["comedy","mockumentary","fun"]),
  show("Servant", 2019, ["psychological","supernatural"]),
  show("Midnight Mass", 2021, ["religious","vampire"]),
  show("Brand New Cherry Flavor", 2021, ["witch","wtf"]),
  show("Yellowjackets", 2021, ["survival","psychological"]),
  show("Archive 81", 2022, ["occult","mystery"]),
  show("Guillermo del Toro's Cabinet of Curiosities", 2022, ["anthology"]),
  show("From", 2022, ["monster","mystery"]),
  show("Interview with the Vampire", 2022, ["vampire","gothic"]),
  show("The Fall of the House of Usher", 2023, ["gothic","supernatural"]),
  show("The Last of Us", 2023, ["infection","apocalypse"]),
  show("Parasyte: The Grey", 2024, ["creature","international"]),
  show("Gyeongseong Creature", 2023, ["creature","international"]),
  show("The Summer Hikaru Died", 2025, ["anime","supernatural"]),
  show("Kingdom", 2019, ["zombie","international"]),
  show("All of Us Are Dead", 2022, ["zombie","international"]),
  show("Hellbound", 2021, ["supernatural","international"]),
  show("The Returned", 2012, ["supernatural","international"]),
  show("In the Flesh", 2013, ["zombie","drama"]),
  show("Crazyhead", 2016, ["demon","comedy","fun"]),
  show("Truth Seekers", 2020, ["ghost","comedy","fun"]),
  show("Reginald the Vampire", 2022, ["vampire","comedy"]),
  show("Chucky", 2021, ["slasher","franchise"], [
    { title: "Child's Play", year: 1988 },
    { title: "Child's Play 2", year: 1990 },
    { title: "Child's Play 3", year: 1991 },
    { title: "Bride of Chucky", year: 1998 },
    { title: "Seed of Chucky", year: 2004 },
    { title: "Curse of Chucky", year: 2013 },
    { title: "Cult of Chucky", year: 2017 }
  ]),
  show("Crystal Lake", 2026, ["slasher","franchise"]),
  show("Carrie", 2026, ["stephen-king","supernatural"]),
  show("The Terror: Devil in Silver", 2026, ["horror","recent"]),
  show("Something Very Bad Is Going to Happen", 2026, ["horror","recent"]),
  show("Haunted Hotel", 2026, ["horror","recent"]),
  show("The East Palace", 2026, ["horror","recent"]),
  show("Widow's Bay", 2026, ["horror","recent"]),

  // Animated / anime horror.
  show("Castlevania", 2017, ["animation","vampire"]),
  show("Castlevania: Nocturne", 2023, ["animation","vampire"], [
    { kind: "show", title: "Castlevania", year: 2017 }
  ]),
  show("Devilman Crybaby", 2018, ["anime","demon"]),
  show("Junji Ito Maniac: Japanese Tales of the Macabre", 2023, ["anime","anthology"]),
  show("Uzumaki", 2024, ["anime","cosmic"]),
  show("Higurashi: When They Cry", 2006, ["anime","mystery","gore"]),
  show("Another", 2012, ["anime","curse"]),
  show("Shiki", 2010, ["anime","vampire"]),
  show("Parasyte: The Maxim", 2014, ["anime","body-horror"]),
  show("Chainsaw Man", 2022, ["anime","demon","gore"]),
  show("DAN DA DAN", 2024, ["anime","supernatural","fun"]),
  show("The Grimm Variations", 2024, ["anime","anthology"]),
  show("Akuma Kun", 2023, ["anime","supernatural"]),

  // Older / cult / comedy / zombie television.
  show("Night Gallery", 1969, ["anthology","classic"]),
  show("Kolchak: The Night Stalker", 1974, ["monster","classic"]),
  show("Friday the 13th: The Series", 1987, ["cursed-object","anthology"]),
  show("Freddy's Nightmares", 1988, ["anthology","slasher"]),
  show("Poltergeist: The Legacy", 1996, ["supernatural"]),
  show("The Hunger", 1997, ["anthology","gothic"]),
  show("Nightmares & Dreamscapes", 2006, ["anthology","stephen-king"]),
  show("Scream Queens", 2015, ["slasher","comedy","camp"]),
  show("iZombie", 2015, ["zombie","comedy"]),
  show("Preacher", 2016, ["supernatural","dark-comedy"]),
  show("Z Nation", 2014, ["zombie","comedy","fun"]),
  show("The Walking Dead", 2010, ["zombie","apocalypse"]),
  show("Fear the Walking Dead", 2015, ["zombie","apocalypse"]),
  show("Black Summer", 2019, ["zombie","apocalypse"]),
  show("Helix", 2014, ["infection","sci-fi"]),
  show("Fortitude", 2015, ["mystery","horror"]),
  show("Lovecraft Country", 2020, ["lovecraft","monster"]),
  show("Swamp Thing", 2019, ["creature","gothic"]),
  show("The Order", 2019, ["occult","werewolf"]),
  show("October Faction", 2020, ["monster","family"]),
  show("Chapelwaite", 2021, ["gothic","vampire"]),
  show("Them", 2021, ["anthology","supernatural"]),
  show("The Outsider", 2020, ["stephen-king","supernatural"]),
  show("The Third Day", 2020, ["folk","psychological"]),
  show("The Baby", 2022, ["dark-comedy","supernatural"]),
  show("Red Rose", 2022, ["tech","supernatural"]),
  show("Cassandra", 2025, ["sci-fi","horror"]),
  show("Dead Ringers", 2023, ["body-horror","psychological"]),
  show("Swarm", 2023, ["psychological","dark-comedy"]),
  show("Teacup", 2024, ["creature","mystery"]),
  show("Grotesquerie", 2024, ["occult","crime"]),
  show("Hysteria!", 2024, ["satanic-panic","comedy"]),
  show("The Bondsman", 2025, ["demon","comedy","fun"]),
  show("Revival", 2026, ["horror","recent"]),

  // Family-spooky / animated series.
  show("Courage the Cowardly Dog", 1999, ["animation","family","monster"]),
  show("Over the Garden Wall", 2014, ["animation","family","folk"]),
  show("R.L. Stine's The Haunting Hour", 2010, ["anthology","family"]),
  show("Creeped Out", 2017, ["anthology","family"]),
  show("Yamishibai: Japanese Ghost Stories", 2013, ["anime","anthology"]),
  show("Mieruko-chan", 2021, ["anime","ghost","comedy"]),
  show("Dark Gathering", 2023, ["anime","ghost"]),
  show("Mononoke", 2007, ["anime","supernatural"]),
  show("Housing Complex C", 2022, ["anime","cosmic"])
];

export const HALLOWEEN_SPECIALS = [
  special("The Simpsons", "Treehouse of Horror", 1990, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror II", 1991, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror III", 1992, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror IV", 1993, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror V", 1994, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror VI", 1995, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror VII", 1996, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror VIII", 1997, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror IX", 1998, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror X", 1999, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XI", 2000, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XII", 2001, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XIII", 2002, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XIV", 2003, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XV", 2004, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XVI", 2005, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XVII", 2006, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XVIII", 2007, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XIX", 2008, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XX", 2009, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXI", 2010, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXII", 2011, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXIII", 2012, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXIV", 2013, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXV", 2014, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXVI", 2015, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXVII", 2016, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXVIII", 2017, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXIX", 2018, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXX", 2019, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXXI", 2020, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXXII", 2021, ["animation","anthology","fun"]),
  special("The Simpsons", "Not It", 2022, ["animation","horror","fun"]),
  special("The Simpsons", "Treehouse of Horror XXXIII", 2022, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXXIV", 2023, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXXV", 2024, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror Presents: Simpsons Wicked This Way Comes", 2024, ["animation","anthology","fun"]),
  special("The Simpsons", "Treehouse of Horror XXXVI", 2025, ["animation","anthology","fun"]),
  special("Community", "Epidemiology", 2010, ["zombie","comedy","fun"]),
  special("Bob's Burgers", "The Hauntening", 2015, ["animation","comedy","fun"]),
  special("Bob's Burgers", "Full Bars", 2012, ["animation","comedy"]),
  special("Bob's Burgers", "Fort Night", 2013, ["animation","comedy"]),
  special("Bob's Burgers", "Tina and the Real Ghost", 2014, ["animation","ghost","comedy"]),
  special("Bob's Burgers", "The Wolf of Wharf Street", 2017, ["animation","comedy"]),
  special("Boy Meets World", "And Then There Was Shawn", 1998, ["slasher","comedy"]),
  special("South Park", "Korn's Groovy Pirate Ghost Mystery", 1999, ["animation","comedy"]),
  special("Hey Arnold!", "Arnold's Halloween", 1997, ["animation","family"]),
  special("SpongeBob SquarePants", "Scaredy Pants", 1999, ["animation","family"]),
  special("Regular Show", "Terror Tales of the Park", 2011, ["animation","anthology"]),
  special("Gravity Falls", "Summerween", 2012, ["animation","monster","family"]),
  special("Invader Zim", "Halloween Spectacular of Spooky Doom", 2001, ["animation","weird"]),
  special("Psych", "This Episode Sucks", 2011, ["vampire","comedy"]),
  special("Brooklyn Nine-Nine", "Halloween", 2014, ["comedy"]),
  special("Parks and Recreation", "Halloween Surprise", 2012, ["comedy"]),
  special("The Office", "Halloween", 2005, ["comedy"]),
  special("Modern Family", "Halloween", 2010, ["comedy"]),
  special("American Horror Story: Murder House", "Halloween, Part 1", 2011, ["ghost"]),
  special("American Horror Story: Murder House", "Halloween, Part 2", 2011, ["ghost"]),
  special("American Horror Story: Coven", "Fearful Pranks Ensue", 2013, ["witch"]),
  special("American Horror Story: Coven", "Burn, Witch. Burn!", 2013, ["witch"]),
  special("American Horror Story: Freak Show", "Edward Mordrake, Part 1", 2014, ["ghost"]),
  special("American Horror Story: Freak Show", "Edward Mordrake, Part 2", 2014, ["ghost"]),

  // Classic / family / animated Halloween specials.
  special("Peanuts", "It's the Great Pumpkin, Charlie Brown", 1966, ["animation","family","classic"]),
  special("Garfield", "Garfield's Halloween Adventure", 1985, ["animation","family"]),
  special("Dr. Seuss", "Halloween Is Grinch Night", 1977, ["animation","family"]),
  special("Toy Story", "Toy Story of Terror!", 2013, ["animation","family"]),
  special("Shrek", "Scared Shrekless", 2010, ["animation","family","comedy"]),
  special("The Muppets", "Muppets Haunted Mansion", 2021, ["family","ghost","comedy"]),
  special("Marvel Studios", "Werewolf by Night", 2022, ["werewolf","monster"]),
  special("LEGO Star Wars", "Terrifying Tales", 2021, ["animation","family","comedy"]),
  special("The Halloween Tree", "The Halloween Tree", 1993, ["animation","family"]),
  special("SpongeBob SquarePants", "The Legend of Boo-Kini Bottom", 2017, ["animation","family"]),
  special("Adventure Time", "The Creeps", 2011, ["animation","mystery"]),
  special("Adventure Time", "No One Can Hear You", 2011, ["animation","creepy"]),
  special("Regular Show", "Terror Tales of the Park II", 2012, ["animation","anthology"]),
  special("Regular Show", "Terror Tales of the Park III", 2013, ["animation","anthology"]),
  special("Regular Show", "Terror Tales of the Park IV", 2014, ["animation","anthology"]),
  special("Regular Show", "Terror Tales of the Park V", 2015, ["animation","anthology"]),
  special("Regular Show", "Terror Tales of the Park VI", 2016, ["animation","anthology"]),
  special("Gravity Falls", "Little Gift Shop of Horrors", 2014, ["animation","anthology"]),
  special("Rocko's Modern Life", "Sugar-Frosted Frights", 1995, ["animation","family"]),
  special("Rugrats", "Candy Bar Creep Show", 1992, ["animation","family"]),
  special("Rugrats", "Ghost Story", 1999, ["animation","family"]),
  special("Hey Arnold!", "Headless Cabbie", 1999, ["animation","ghost"]),
  special("Recess", "Terrifying Tales of Recess", 2001, ["animation","anthology"]),
  special("King of the Hill", "Hilloween", 1997, ["animation","comedy"]),

  // Sitcom / comedy Halloween.
  special("Roseanne", "Boo!", 1989, ["comedy"]),
  special("Home Improvement", "The Haunting of Taylor House", 1992, ["comedy"]),
  special("Freaks and Geeks", "Tricks and Treats", 1999, ["comedy","teen"]),
  special("That '70s Show", "Too Old to Trick or Treat, Too Young to Die", 2000, ["comedy"]),
  special("Superstore", "Halloween Theft", 2016, ["comedy"]),
  special("New Girl", "Halloween", 2012, ["comedy"]),
  special("Happy Endings", "Spooky Endings", 2011, ["comedy"]),
  special("Scream Queens", "Pumpkin Patch", 2015, ["slasher","comedy"]),

  // Standalone horror-series episodes that work as one-night picks.
  special("Buffy the Vampire Slayer", "Halloween", 1997, ["vampire","monster"]),
  special("Buffy the Vampire Slayer", "Fear, Itself", 1999, ["demon","halloween"]),
  special("Buffy the Vampire Slayer", "All the Way", 2001, ["vampire","halloween"]),
  special("Supernatural", "It's the Great Pumpkin, Sam Winchester", 2008, ["witch","halloween"]),
  special("The X-Files", "Squeeze", 1993, ["monster"]),
  special("The X-Files", "Home", 1996, ["monster","disturbing"]),
  special("Doctor Who", "Blink", 2007, ["monster","time"]),
  special("The Simpsons", "Halloween of Horror", 2015, ["animation","halloween"]),
  special("Bob's Burgers", "Nightmare on Ocean Avenue Street", 2018, ["animation","comedy"]),
  special("Bob's Burgers", "Heartbreak Hotel-oween", 2020, ["animation","comedy"]),
  special("Bob's Burgers", "Teen-a-Witch", 2016, ["animation","witch","comedy"])
];

export const HALLOWEEN_CATALOG = [
  ...HALLOWEEN_MOVIES,
  ...HALLOWEEN_SHOWS,
  ...HALLOWEEN_SPECIALS
];
