import { emit } from "../core/events.js";
import { getState, update } from "../core/store.js";
import { closeModal, openModal } from "../ui/modals.js";
import { toast } from "../ui/notifications.js";

const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const moviePath=item=>item?.sourcePath||(item?.sourcePaths||[])[0]||"";

export async function openMoviePlayer(movieId,onChanged=()=>{}){
  const movie=getState().items[movieId],path=moviePath(movie),profile=getState().preferences.dailyDriver?.movieProfile||"you",profileRecord={...(profile==="you"?{status:movie?.status,playbackSeconds:movie?.playbackSeconds,playbackPercent:movie?.playbackPercent,watchSeconds:movie?.watchSeconds,durationSeconds:movie?.durationSeconds}:{}),...(movie?.movieMeta?.profiles?.[profile]||{})};if(!movie||!path)return false;
  // Opening the player is not watching it: the session is recorded on the first
  // frame that plays, once. A film already part-watched is resumed, not started.
  const resumed=Number(profileRecord.playbackSeconds||0)>30&&profileRecord.status!=="completed";
  let startRecorded=false;const recordStart=()=>{if(startRecorded)return;startRecorded=true;emit("MOVIE_PLAYBACK_STARTED",{itemId:movieId,wing:"movies",resumed,meta:{title:movie.title}})};
  if(globalThis.vaultNative?.openPlayer){
    const closed=event=>{const result=event.detail||{};if(result.kind!=="movie"||result.movieId!==movieId)return;window.removeEventListener("vault-native-player-closed",closed);update(save=>{const item=save.items[movieId];if(!item)return;item.movieMeta||={};item.movieMeta.profiles||={};const prior=profile==="you"?item:item.movieMeta.profiles[profile]||{},current=Math.max(Number(prior.playbackSeconds||0),Number(result.currentSeconds||0)),duration=Math.max(Number(prior.durationSeconds||0),Number(result.durationSeconds||0)),watchSeconds=Number(prior.watchSeconds||0)+Number(result.sessionSeconds||0),playbackPercent=result.durationSeconds?Math.round(Number(result.currentSeconds||0)/Number(result.durationSeconds)*100):Number(prior.playbackPercent||0),status=result.completed||playbackPercent>=90?"completed":current>0?"in_progress":prior.status||"backlog",changes={playbackSeconds:current,durationSeconds:duration,watchSeconds,playbackPercent,status,lastOpenedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(status==="completed")changes.completedAt=prior.completedAt||new Date().toISOString();item.movieMeta.profiles[profile]={...(item.movieMeta.profiles[profile]||{}),...changes};if(profile==="you")Object.assign(item,changes)});onChanged()};
    window.addEventListener("vault-native-player-closed",closed);recordStart();globalThis.vaultNative.openPlayer(JSON.stringify({kind:"movie",movieId,title:movie.title,path,resumeSeconds:Number(profileRecord.playbackSeconds||0),profile}));return true;
  }
  openModal({title:"PREPARING VAULT PLAYER",body:`<div class="vault-ai-progress"><span class="eyebrow">LOCAL MOVIE // NOTHING LEAVES THIS COMPUTER</span><h3>OPENING ${esc(movie.title)}…</h3><div class="vault-ai-progress__bar"><i></i></div><p>The Vault remembers actual watch time and marks watched at 90%.</p></div>`});
  try{
    const response=await fetch("./__vault/media/token",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"media-token"},body:JSON.stringify({path})}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error("This movie could not be prepared for embedded playback.");
    const saved=Number(profileRecord.playbackSeconds||0),canResume=saved>=30;
    let startCompatibility=async()=>{};
    openModal({title:movie.title,body:`<div class="vault-tv-terminal" data-tv-terminal><div class="vault-tv-terminal__lights"><i></i><i></i><i></i><span>VAULT MOVIE LINK // ${esc(payload.format)} // ${esc(profile.toUpperCase())}</span><label>SPEED <select data-movie-speed><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></label><button data-movie-player-size="large">LARGE</button><button data-movie-player-size="max">MAX</button></div><div class="vault-tv-terminal__screen"><video data-vault-movie-video controls ${canResume?"":"autoplay"} preload="metadata" src="${esc(payload.contentUrl)}"></video>${canResume?`<div class="vault-tv-resume" data-movie-resume><span>PLAYBACK RECORD FOUND</span><b>${Math.floor(saved/60)}:${String(Math.floor(saved%60)).padStart(2,"0")}</b><div><button data-movie-resume-play>RESUME</button><button data-movie-start-over>START OVER</button></div></div>`:""}</div><div class="vault-tv-terminal__footer"><span data-movie-player-state>READY</span><b>VAULT-TEC CINEMA TERMINAL</b><span data-movie-player-clock>0:00 / --:--</span></div></div><p class="muted">Fullscreen shows only the movie. The terminal border returns when you exit fullscreen.</p>`,actions:[{label:profileRecord.status==="completed"?"MARK UNWATCHED":"MARK WATCHED",handler:()=>{setWatched(profileRecord.status!=="completed");onChanged()}},{label:"PLAY COMPATIBILITY MODE",handler:()=>startCompatibility()},{label:"CLOSE PLAYER",primary:true,handler:()=>{finish();closeModal()}}]});
    const root=document.querySelector("#modal-root"),terminal=root.querySelector("[data-tv-terminal]"),modal=terminal.closest(".modal"),video=root.querySelector("[data-vault-movie-video]"),stateLabel=root.querySelector("[data-movie-player-state]"),clock=root.querySelector("[data-movie-player-clock]");let accounted=0,playingSince=0,closed=false,compatibilityToken="",compatibilityOffset=0,sourceDuration=Number(profileRecord.durationSeconds||movie.durationSeconds||0),hls=null,compatibilityStarting=false;
    const setSize=size=>{modal.style.width="";modal.style.height="";modal.dataset.tvSize=size;localStorage.setItem("vaultTvPlayerSize",size)};terminal.querySelectorAll("[data-movie-player-size]").forEach(button=>button.onclick=()=>setSize(button.dataset.moviePlayerSize));setSize(localStorage.getItem("vaultTvPlayerSize")||"large");
    const absoluteTime=()=>Math.max(0,Number(video.currentTime||0)+compatibilityOffset),knownDuration=()=>Math.max(sourceDuration,compatibilityOffset+Math.max(0,Number.isFinite(video.duration)?video.duration:0));
    const format=value=>{value=Math.max(0,Math.floor(Number(value)||0));return`${Math.floor(value/60)}:${String(value%60).padStart(2,"0")}`},updateClock=()=>clock.textContent=`${format(absoluteTime())} / ${knownDuration()?format(knownDuration()):"--:--"}`;
    const stopClock=()=>{if(!playingSince)return;accounted+=Math.max(0,(Date.now()-playingSince)/1000);playingSince=0},startClock=()=>{if(!video.paused&&!playingSince)playingSince=Date.now()};
    const writeProfile=(item,changes)=>{item.movieMeta||={};item.movieMeta.profiles||={};const record=item.movieMeta.profiles[profile]={...(item.movieMeta.profiles[profile]||{}),...changes,updatedAt:new Date().toISOString()};if(profile==="you")Object.assign(item,changes);return record};
    const setWatched=watched=>update(save=>{const item=save.items[movieId];if(!item)return;const changes={status:watched?"completed":"backlog"};if(watched)changes.completedAt=item.movieMeta?.profiles?.[profile]?.completedAt||new Date().toISOString();else changes.completedAt=null;writeProfile(item,changes)});
    const save=()=>{stopClock();const current=absoluteTime(),duration=knownDuration();update(store=>{const item=store.items[movieId];if(!item)return;const prior=profile==="you"?item:item.movieMeta?.profiles?.[profile]||{},playbackPercent=duration>0?Math.round(current/duration*100):Number(prior.playbackPercent||0),status=playbackPercent>=90?"completed":current>0?"in_progress":prior.status||"backlog",changes={playbackSeconds:current,durationSeconds:Math.max(Number(prior.durationSeconds||0),duration),playbackPercent,watchSeconds:Number(prior.watchSeconds||0)+Math.round(accounted),status,lastOpenedAt:new Date().toISOString()};if(status==="completed")changes.completedAt=prior.completedAt||new Date().toISOString();writeProfile(item,changes)});accounted=0;startClock();onChanged()};
    const finish=()=>{if(closed)return;closed=true;save();hls?.destroy();if(compatibilityToken)fetch("./__vault/media/compat/stop",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"media-compat-stop"},body:JSON.stringify({token:compatibilityToken})}).catch(()=>{})};
    root.querySelector("[data-movie-speed]").onchange=event=>video.playbackRate=Number(event.target.value)||1;root.querySelector("[data-movie-resume-play]")?.addEventListener("click",()=>{video.currentTime=Math.min(saved,Math.max(0,Number(video.duration||saved)));root.querySelector("[data-movie-resume]")?.remove();video.play().catch(()=>{})});root.querySelector("[data-movie-start-over]")?.addEventListener("click",()=>{video.currentTime=0;root.querySelector("[data-movie-resume]")?.remove();video.play().catch(()=>{})});
    startCompatibility=async()=>{if(compatibilityStarting||compatibilityToken)return;compatibilityStarting=true;stateLabel.textContent="PREPARING LOCAL STREAM";const start=Math.floor(absoluteTime());if(Number.isFinite(video.duration))sourceDuration=Math.max(sourceDuration,compatibilityOffset+video.duration);video.onerror=null;video.pause();try{const response=await fetch("./__vault/media/compat/start",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"media-compat-start"},body:JSON.stringify({path,startSeconds:start})}),data=await response.json().catch(()=>({}));if(!response.ok||!data.playlistUrl)throw new Error();compatibilityToken=data.token;compatibilityOffset=Number(data.startSeconds||start);hls=new Hls({enableWorker:true,backBufferLength:90});hls.loadSource(data.playlistUrl);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{stateLabel.textContent="LOCAL COMPATIBILITY STREAM";video.play().catch(()=>{})});hls.on(Hls.Events.ERROR,(_event,detail)=>{if(detail.fatal){stateLabel.textContent="STREAM ERROR";toast("COMPATIBILITY STREAM PAUSED","The local conversion could not continue.")}})}catch{stateLabel.textContent="STREAM UNAVAILABLE";toast("COMPATIBILITY MODE COULD NOT START","The original movie file was not changed.",8000)}finally{compatibilityStarting=false}};
    video.onloadedmetadata=()=>{if(!compatibilityToken&&canResume)video.currentTime=Math.min(saved,Math.max(0,video.duration-1));if(!compatibilityToken&&Number.isFinite(video.duration))sourceDuration=video.duration;updateClock()};video.onplay=()=>{root.querySelector("[data-movie-resume]")?.remove();stateLabel.textContent=compatibilityToken?"LOCAL COMPATIBILITY STREAM":"PLAYING";recordStart();startClock()};video.onpause=()=>{stateLabel.textContent="PAUSED";save();updateClock()};video.ontimeupdate=()=>updateClock();video.onended=()=>{stateLabel.textContent="COMPLETE";if(!compatibilityToken||sourceDuration&&absoluteTime()/sourceDuration>=.9)setWatched(true);save();toast("MOVIE WATCHED",movie.title)};video.onerror=()=>startCompatibility();
    return true;
  }catch(error){openModal({title:"MOVIE PLAYER PAUSED",body:`<p>${esc(error.message)}</p>`,actions:[{label:"CLOSE",primary:true,handler:()=>closeModal()}]});return false}
}
