import { getState, update } from "../core/store.js";
import { beginPlaybackSession } from "./playbackLifecycle.js";
import { closeModal, openModal } from "../ui/modals.js";
import { toast } from "../ui/notifications.js";
import { openNativeTvPlayer } from "./nativeTvPlayback.js";
import { nextPlayableEpisode } from "./tvPlaybackState.js";

const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

/* Containers no browser will decode, whatever the codec inside them.
 *
 * These are not broken links — the file is there and the path is right — but
 * handing one to a <video> element produces a dead player, which is
 * indistinguishable from a broken link to anyone looking at it. There are 3,462
 * .avi episodes in this archive; the whole of Always Sunny season 3 is one.
 * .mkv and .mov are left off deliberately: they often do play, and the error
 * fallback still catches the ones that do not. */
export const NEEDS_TRANSCODE=new Set([".avi",".wmv",".rmvb",".flv",".divx",".vob",".mpg",".mpeg",".m2ts",".ts",".asf",".ogm"]);
const containerOf=value=>(String(value||"").match(/\.[^.\\/]+$/)||[""])[0].toLowerCase();

export async function openTvPlayer(showId,episodeId,onChanged=()=>{}){
  return openNativeTvPlayer(showId,episodeId,onChanged,openTvPlayer,openBrowserTvPlayer);
}

export async function openBrowserTvPlayer(showId,episodeId,onChanged=()=>{}){
  const show=getState().items[showId],episode=show?.episodes?.[episodeId],path=episode?.sourcePath;if(!show||!episode||!path)return false;
  // Opening the player is not watching it. The session is recorded on the first
  // frame that actually plays, and only once — `play` fires again on every unpause.
  let startRecorded=false;const recordStart=()=>{if(startRecorded)return;startRecorded=true;beginPlaybackSession(showId,episodeId,path)};
  if(globalThis.vaultNative?.openPlayer){
    const closed=event=>{const result=event.detail||{};if(result.kind!=="tv"||result.showId!==showId||result.episodeId!==episodeId)return;window.removeEventListener("vault-native-player-closed",closed);update(state=>{const targetShow=state.items[showId],target=targetShow?.episodes?.[episodeId];if(!target)return;target.playbackSeconds=Math.max(Number(target.playbackSeconds||0),Number(result.currentSeconds||0));target.durationSeconds=Math.max(Number(target.durationSeconds||0),Number(result.durationSeconds||0));target.totalWatchSeconds=Number(target.totalWatchSeconds||0)+Number(result.sessionSeconds||0);target.lastPlayedAt=new Date().toISOString();if(result.completed)target.status="completed";else if(Number(result.currentSeconds||0)>0&&target.status!=="completed")target.status="in_progress";const episodes=Object.values(targetShow.episodes||{}),done=episodes.filter(value=>value.status==="completed").length;targetShow.progress={completed:done,total:episodes.length};targetShow.status=done===episodes.length&&done?"completed":done||episodes.some(value=>value.status==="in_progress")?"in_progress":"backlog"});onChanged()};
    window.addEventListener("vault-native-player-closed",closed);recordStart();globalThis.vaultNative.openPlayer(JSON.stringify({kind:"tv",showId,episodeId,title:`${show.title} — S${String(episode.season).padStart(2,"0")}E${String(episode.number).padStart(2,"0")}`,path,resumeSeconds:Number(episode.playbackSeconds||0)}));return true;
  }
  openModal({title:"PREPARING VAULT PLAYER",body:`<div class="vault-ai-progress"><span class="eyebrow">LOCAL EPISODE // NOTHING LEAVES THIS COMPUTER</span><h3>OPENING ${esc(show.title)}…</h3><div class="vault-ai-progress__bar"><i></i></div><p>The Vault will remember actual watch time and mark watched at 90%.</p></div>`});
  try{
    // An episode can have more than one file on disk. Start on the primary unless it
    // is the one that went missing, and let the viewer switch copies while watching.
    const sources=[...new Set([path,...(episode.alternatePaths||[])])].filter(Boolean);
    let activeSource=episode.linkStatus==="missing"&&sources.length>1?sources[1]:sources[0];
    const tokenFor=async target=>{const response=await fetch("./__vault/media/token",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"media-token"},body:JSON.stringify({path:target})}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error("This episode could not be prepared for embedded playback.");return result};
    const payload=await tokenFor(activeSource);
    const code=`S${String(episode.season).padStart(2,"0")}E${String(episode.number).padStart(2,"0")}`,saved=episode.status==="completed"?0:Number(episode.playbackSeconds||0),canResume=saved>=30,ordered=Object.values(show.episodes||{}).sort((a,b)=>Number(a.season)-Number(b.season)||Number(a.number)-Number(b.number)),position=ordered.findIndex(value=>value.id===episodeId),nextEpisode=nextPlayableEpisode(show,episodeId);
    let manualUnwatched=false;const setWatched=watched=>{manualUnwatched=!watched;update(state=>{const targetShow=state.items[showId],target=targetShow?.episodes?.[episodeId];if(!target)return;target.status=watched?"completed":"backlog";if(watched)target.completedAt||=new Date().toISOString();else {delete target.completedAt;target.playbackSeconds=0;}const episodes=Object.values(targetShow.episodes||{}),done=episodes.filter(value=>value.status==="completed").length;targetShow.progress={completed:done,total:episodes.length};targetShow.status=done===episodes.length&&done?"completed":done?"in_progress":"backlog"});onChanged();toast(watched?"EPISODE WATCHED":"EPISODE UNWATCHED",`${show.title} · ${code}`)};
    let startCompatibility=async()=>{};
    const actions=[{label:episode.status==="completed"?"MARK UNWATCHED":"MARK WATCHED",handler:()=>setWatched(getState().items[showId]?.episodes?.[episodeId]?.status!=="completed")},{label:"PLAY COMPATIBILITY MODE",handler:()=>startCompatibility()},...(nextEpisode?[{label:`NEXT · S${String(nextEpisode.season).padStart(2,"0")}E${String(nextEpisode.number).padStart(2,"0")}`,handler:()=>{finish();closeModal();setTimeout(()=>openTvPlayer(showId,nextEpisode.id,onChanged),0)}}]:[]),{label:"CLOSE PLAYER",primary:true,handler:()=>{finish();closeModal()}}];
    openModal({title:`${show.title} — ${code}`,body:`<div class="vault-tv-terminal" data-tv-terminal><div class="vault-tv-terminal__lights"><i></i><i></i><i></i><span>VAULT VIDEO LINK // ${esc(payload.format)}</span><label>SPEED <select data-tv-speed><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></label><span data-tv-track-tools></span>${sources.length>1?`<label>COPY <select data-tv-source aria-label="Choose which file to play">${sources.map((source,index)=>`<option value="${index}" ${source===activeSource?"selected":""}>${esc(String(source).split(/[\\/]/).pop().slice(0,44))}</option>`).join("")}</select></label>`:""}<button data-tv-player-size="large">LARGE</button><button data-tv-player-size="max">MAX</button></div><div class="vault-tv-terminal__screen"><video data-vault-tv-video controls ${canResume?"":"autoplay"} preload="metadata" src="${esc(payload.contentUrl)}"></video>${canResume?`<div class="vault-tv-resume" data-tv-resume><span>PLAYBACK RECORD FOUND</span><b>${Math.floor(saved/60)}:${String(Math.floor(saved%60)).padStart(2,"0")}</b><div><button data-tv-resume-play>RESUME</button><button data-tv-start-over>START OVER</button></div></div>`:""}</div><div class="vault-tv-terminal__footer"><span data-tv-player-state>READY</span><b>VAULT-TEC ENTERTAINMENT TERMINAL</b><span data-tv-player-clock>0:00 / --:--</span></div></div><p class="muted">Fullscreen shows only the episode. The terminal border returns when you exit fullscreen.</p>`,actions});
    const root=document.querySelector("#modal-root"),terminal=root.querySelector("[data-tv-terminal]"),modal=terminal.closest(".modal"),video=root.querySelector("[data-vault-tv-video]");let lastSaved=0,accountedSeconds=0,watchedSessionSeconds=0,playingSince=0,closed=false,applyingSize=true,compatibilityToken="",compatibilityOffset=0,sourceDuration=Number(episode.durationSeconds||0),hls=null,compatibilityStarting=false;
    const storedMode=localStorage.getItem("vaultTvPlayerSize")||"large";
    const setSize=size=>{applyingSize=true;modal.style.width="";modal.style.height="";modal.dataset.tvSize=size;localStorage.setItem("vaultTvPlayerSize",size);requestAnimationFrame(()=>requestAnimationFrame(()=>{applyingSize=false}))};terminal.querySelectorAll("[data-tv-player-size]").forEach(button=>button.onclick=()=>setSize(button.dataset.tvPlayerSize));
    if(storedMode==="custom"){try{const savedSize=JSON.parse(localStorage.getItem("vaultTvPlayerDimensions")||"null");if(savedSize?.width&&savedSize?.height){modal.dataset.tvSize="custom";modal.style.width=`${Math.min(innerWidth*.96,Math.max(720,savedSize.width))}px`;modal.style.height=`${Math.min(innerHeight*.94,Math.max(520,savedSize.height))}px`;requestAnimationFrame(()=>requestAnimationFrame(()=>{applyingSize=false}))}else setSize("large")}catch{setSize("large")}}else setSize(storedMode==="max"?"max":"large");
    const observer=new ResizeObserver(()=>{if(applyingSize)return;const box=modal.getBoundingClientRect();if(box.width<700||box.height<500)return;modal.dataset.tvSize="custom";localStorage.setItem("vaultTvPlayerSize","custom");localStorage.setItem("vaultTvPlayerDimensions",JSON.stringify({width:Math.round(box.width),height:Math.round(box.height)}))});observer.observe(modal);
    const stopClock=()=>{if(!playingSince)return;watchedSessionSeconds+=(performance.now()-playingSince)/1000;playingSince=0};
    const startClock=()=>{if(!closed&&!playingSince&&!video.paused&&!video.ended)playingSince=performance.now()};
    const absoluteTime=()=>Math.max(0,Number(video.currentTime||0)+compatibilityOffset),knownDuration=()=>Math.max(sourceDuration,compatibilityOffset+Math.max(0,Number.isFinite(video.duration)?video.duration:0));
    const save=()=>{if(!video)return;stopClock();const current=absoluteTime(),duration=knownDuration(),session=Math.max(0,Math.floor(watchedSessionSeconds)),delta=Math.max(0,session-accountedSeconds);accountedSeconds=session;update(state=>{const target=state.items[showId]?.episodes?.[episodeId];if(!target)return;target.playbackSeconds=manualUnwatched?0:Math.max(0,Math.round(current));target.durationSeconds=Math.max(Number(target.durationSeconds||0),Math.round(duration));target.totalWatchSeconds=Number(target.totalWatchSeconds||0)+delta;delete target.lastSessionSeconds;target.lastPlayedAt=new Date().toISOString();if(!manualUnwatched&&duration&&current/duration>=.9){target.status="completed";target.completedAt||=new Date().toISOString();}else if(!manualUnwatched&&current>0&&target.status!=="completed")target.status="in_progress";const episodes=Object.values(state.items[showId].episodes||{}),done=episodes.filter(value=>value.status==="completed").length;state.items[showId].progress={completed:done,total:episodes.length};state.items[showId].status=done===episodes.length&&done?"completed":done||episodes.some(value=>value.status==="in_progress")?"in_progress":"backlog"});onChanged();startClock()};
    let closeObserver;const finish=()=>{if(closed)return;closed=true;stopClock();save();observer.disconnect();closeObserver?.disconnect();hls?.destroy();if(compatibilityToken)fetch("./__vault/media/compat/stop",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"media-compat-stop"},body:JSON.stringify({token:compatibilityToken})}).catch(()=>{})};
    root.querySelector("[data-close]")?.addEventListener("click",finish,{capture:true});root.querySelector(".modal-backdrop")?.addEventListener("click",event=>{if(event.target.classList.contains("modal-backdrop"))finish()},{capture:true});
    closeObserver=new MutationObserver(()=>{if(!terminal.isConnected)finish()});closeObserver.observe(root,{childList:true,subtree:true});
    const resumePanel=root.querySelector("[data-tv-resume]"),stateLabel=root.querySelector("[data-tv-player-state]"),clockLabel=root.querySelector("[data-tv-player-clock]"),formatTime=value=>{value=Math.max(0,Math.floor(Number(value)||0));return`${Math.floor(value/60)}:${String(value%60).padStart(2,"0")}`},updateStatus=()=>{if(clockLabel)clockLabel.textContent=`${formatTime(absoluteTime())} / ${knownDuration()?formatTime(knownDuration()):"--:--"}`};root.querySelector("[data-tv-speed]").onchange=event=>{video.playbackRate=Number(event.target.value)||1};
    root.querySelector("[data-tv-source]")?.addEventListener("change",async event=>{
      const target=sources[Number(event.target.value)]||sources[0],resume=absoluteTime();
      stateLabel.textContent="SWITCHING COPY";
      try{
        const next=await tokenFor(target);
        activeSource=target;hls?.destroy();hls=null;
        if(compatibilityToken){fetch("./__vault/media/compat/stop",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"media-compat-stop"},body:JSON.stringify({token:compatibilityToken})}).catch(()=>{});compatibilityToken="";compatibilityOffset=0}
        video.src=next.contentUrl;
        video.addEventListener("loadedmetadata",()=>{video.currentTime=Math.min(resume,Math.max(0,video.duration-1));video.play().catch(()=>{})},{once:true});
        stateLabel.textContent="COPY SWITCHED";
      }catch{stateLabel.textContent="COPY UNAVAILABLE";toast("COPY UNAVAILABLE","That file could not be opened. The episode record was not changed.")}
    });root.querySelector("[data-tv-resume-play]")?.addEventListener("click",()=>{video.currentTime=Math.min(saved,Math.max(0,Number(video.duration||saved)));resumePanel.remove();video.play().catch(()=>{})});root.querySelector("[data-tv-start-over]")?.addEventListener("click",()=>{video.currentTime=0;resumePanel.remove();video.play().catch(()=>{})});
    startCompatibility=async(forcedStart=null)=>{if(compatibilityStarting||(compatibilityToken&&forcedStart===null))return;if(compatibilityToken){hls?.destroy();await fetch("./__vault/media/compat/stop",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"media-compat-stop"},body:JSON.stringify({token:compatibilityToken})}).catch(()=>{});compatibilityToken="";}compatibilityStarting=true;stateLabel.textContent="PREPARING LOCAL STREAM";const start=forcedStart!==null?forcedStart:Math.floor(absoluteTime()||(!startRecorded?saved:0));if(Number.isFinite(video.duration))sourceDuration=Math.max(sourceDuration,compatibilityOffset+video.duration);video.onerror=null;video.pause();try{const response=await fetch("./__vault/media/compat/start",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"media-compat-start"},body:JSON.stringify({path:activeSource,startSeconds:start})}),data=await response.json().catch(()=>({}));if(!response.ok||!data.playlistUrl)throw new Error();compatibilityToken=data.token;compatibilityOffset=Number(data.startSeconds||start);hls=new Hls({enableWorker:true,backBufferLength:90});hls.loadSource(data.playlistUrl);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{stateLabel.textContent="LOCAL COMPATIBILITY STREAM";video.play().catch(()=>{})});hls.on(Hls.Events.ERROR,(_event,detail)=>{if(detail.fatal){stateLabel.textContent="STREAM ERROR";toast("COMPATIBILITY STREAM PAUSED","The local conversion could not continue.")}})}catch{stateLabel.textContent="STREAM UNAVAILABLE";toast("COMPATIBILITY MODE COULD NOT START","The original file and Vault record were not changed.",8000)}finally{compatibilityStarting=false}};
    const installTrackControls=()=>{const host=root.querySelector("[data-tv-track-tools]");if(!host)return;const textTracks=Array.from(video.textTracks||[]),audioTracks=Array.from(video.audioTracks||[]);host.innerHTML=`${textTracks.length?`<button data-tv-subtitles>CC OFF</button>`:""}${audioTracks.length>1?`<select data-tv-audio aria-label="Audio track">${audioTracks.map((track,index)=>`<option value="${index}">${esc(track.label||track.language||`AUDIO ${index+1}`)}</option>`).join("")}</select>`:""}`;let subtitle=-1;host.querySelector("[data-tv-subtitles]")?.addEventListener("click",event=>{subtitle=subtitle>=textTracks.length-1?-1:subtitle+1;textTracks.forEach((track,index)=>track.mode=index===subtitle?"showing":"disabled");event.currentTarget.textContent=subtitle<0?"CC OFF":`CC ${esc(textTracks[subtitle].label||textTracks[subtitle].language||subtitle+1)}`});host.querySelector("[data-tv-audio]")?.addEventListener("change",event=>audioTracks.forEach((track,index)=>track.enabled=index===Number(event.target.value)))};
    const showEnded=()=>{const screen=terminal.querySelector(".vault-tv-terminal__screen"),panel=document.createElement("div");panel.className="vault-tv-resume vault-tv-ended";panel.innerHTML=`<span>EPISODE ARCHIVED</span><b>${esc(code)}</b><div><button data-tv-replay>REPLAY</button>${nextEpisode?`<button data-tv-ended-next>NEXT EPISODE</button>`:""}</div>`;screen.append(panel);panel.querySelector("[data-tv-replay]").onclick=()=>{panel.remove();if(compatibilityToken)startCompatibility(0);else{video.currentTime=0;video.play().catch(()=>{})}};panel.querySelector("[data-tv-ended-next]")?.addEventListener("click",()=>{finish();closeModal();setTimeout(()=>openTvPlayer(showId,nextEpisode.id,onChanged),0)})};
    video.onloadedmetadata=()=>{if(!compatibilityToken&&canResume)video.currentTime=Math.min(saved,Math.max(0,video.duration-1));if(!compatibilityToken&&Number.isFinite(video.duration))sourceDuration=video.duration;installTrackControls();updateStatus()};video.onplay=()=>{root.querySelector("[data-tv-resume]")?.remove();stateLabel.textContent=compatibilityToken?"LOCAL COMPATIBILITY STREAM":"PLAYING";recordStart();startClock()};video.onpause=()=>{stateLabel.textContent="PAUSED";stopClock();save();updateStatus()};video.onwaiting=()=>{stateLabel.textContent="BUFFERING";stopClock()};video.onseeking=()=>{stateLabel.textContent="SEEKING";stopClock()};video.onseeked=()=>{stateLabel.textContent=video.paused?"PAUSED":"PLAYING";startClock();updateStatus()};video.ontimeupdate=()=>{updateStatus();if(Math.abs(absoluteTime()-lastSaved)>=15){lastSaved=absoluteTime();save()}};video.onended=()=>{stateLabel.textContent="COMPLETE";stopClock();save();if(!manualUnwatched&&(!compatibilityToken||sourceDuration&&absoluteTime()/sourceDuration>=.9)){setWatched(true);showEnded()}};video.onerror=()=>{stopClock();startCompatibility()};
    // Known-undecodable container: start the local stream now rather than load a
    // file that is certain to fail and wait for the error to come back.
    if(NEEDS_TRANSCODE.has(containerOf(activeSource)))startCompatibility();
    return true;
  }catch(error){openModal({title:"EMBEDDED PLAYBACK PAUSED",body:`<p>${esc(error.message)}</p><p>Your episode link and watch record were not changed.</p>`,actions:[{label:"CLOSE",primary:true,handler:()=>closeModal()}]});return false}
}
