"""Build a local TV episode-reference manifest from already-approved TVMaze show IDs."""

import json
from pathlib import Path
import re
import time
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[1]
SOURCES = [ROOT / "js" / "systems" / "bundledArtwork.js", ROOT / "js" / "systems" / "generatedTvArtwork.js"]
OUTPUT = ROOT / "js" / "systems" / "generatedTvCatalog.js"
REPORT = ROOT / "assets" / "artwork" / "library" / "owned-tv-catalog-report.json"
ENTRY = re.compile(r'(?P<id>tv_[a-z0-9_]+|"tv_[a-z0-9_]+")\s*:\s*\{[^\n}]*?"?sourceId"?\s*:\s*(?P<source>\d+)')


def source_map():
    found = {}
    for path in SOURCES:
        text = path.read_text(encoding="utf-8")
        for match in ENTRY.finditer(text):
            found[match.group("id").strip('"')] = int(match.group("source"))
    return found


def fetch_episodes(source_id):
    request = Request(f"https://api.tvmaze.com/shows/{source_id}/episodes?specials=1", headers={"User-Agent": "The-Vault-Personal-Archive/1.0"})
    with urlopen(request, timeout=25) as response:
        return json.loads(response.read().decode("utf-8"))


def main():
    sources = source_map()
    catalog, failures = {}, []
    for index, (item_id, source_id) in enumerate(sorted(sources.items())):
        try:
            episodes = fetch_episodes(source_id)
            regular = sum(1 for episode in episodes if episode.get("type") == "regular")
            specials = len(episodes) - regular
            catalog[item_id] = {"regularEpisodes": regular, "specials": specials, "totalEpisodes": len(episodes), "sourceId": source_id}
        except Exception as error:
            failures.append({"id": item_id, "sourceId": source_id, "reason": type(error).__name__})
        if index % 20 == 0:
            print(f"catalog {index + 1}/{len(sources)}")
        time.sleep(0.12)
    lines = ["// Generated by tools/sync_tv_catalog_totals.py.", "export const generatedTvCatalog = {"]
    for item_id, value in sorted(catalog.items()):
        lines.append(f"  {json.dumps(item_id)}: {json.dumps(value)},")
    lines.append("};\n")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    REPORT.write_text(json.dumps({"generatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "matchedSeries": len(catalog), "failures": failures}, indent=2), encoding="utf-8")
    print(f"matched={len(catalog)} failures={len(failures)}")


if __name__ == "__main__":
    main()
