import { createId } from "../core/ids.js";
import { localComicCollection, localComicDisplay } from "../systems/comicLocalCollections.js";
import { emit } from "../core/events.js";
import { getState, update } from "../core/store.js";
import { queueArtworkApproval } from "../systems/artworkApproval.js";
import { closeModal, openModal } from "../ui/modals.js";
import { toast } from "../ui/notifications.js";
import { escapeHtml as esc } from "../ui/safeHtml.js";
import { renderAtomicWingShell } from "../ui/atomicWingShell.js";
import { comicMonitoringEligible, ensureComicsMangaV2, renderComicsV2Shelves, renderComicV2SeriesPanels } from "./comicsMangaV2.js?v=20260831-v3";

const LEGACY_COLLECTIONS={collection_legacy_bok_manga_shelf:"manga",collection_legacy_bok_western_essentials:"comic"};
const READING=new Set(["planned","reading","cooking","paused","completed","dropped"]);
const PUBLICATION=new Set(["ongoing","hiatus","complete","cancelled","unknown"]);
const COMIC_FORMATS=new Set(["manga","comic","graphic_novel","webcomic"]);
const FORMATS=new Set(["manga","comic","graphic_novel","webcomic"]);
const UNITS=new Set(["chapters","issues","volumes","editions","simple"]);
const LANES=new Set(["official_english_chapters","original_chapters","english_volumes","original_volumes","comic_issues","collected_editions","manual"]);
const defaults={scope:"all",publication:"all",format:"all",sort:"new"};
const KINDLE_LIBRARY_URL="https://read.amazon.com/";
const COOKIE_MANGA_PACKAGE="chat.kijang.manga.cookie.browser";
const COOKIE_MANGA_PLAY_URL=`https://play.google.com/store/apps/details?id=${COOKIE_MANGA_PACKAGE}`;
let searchTimer=null,releaseCheckPromise=null,artworkBackfillPromise=null;

const artFor=item=>typeof item.artwork==="string"?item.artwork:item.artwork?.localPath||item.artwork?.url||"";
const initials=title=>String(title||"CM").split(/\s+/).slice(0,2).map(word=>word[0]).join("").toUpperCase();
const hue=title=>[...String(title||"")].reduce((sum,char)=>sum+char.charCodeAt(0),0)%360;
const metaFor=item=>item.comicMeta||{};
const comicCollectionName=key=>getState().metadata.comicsManga?.collectionAliases?.[key]||key.split(":").slice(2).join(":");
export function renameComicCollection(key,name){const clean=String(name||"").trim();if(!clean)return false;update(save=>{save.metadata.comicsManga||={};save.metadata.comicsManga.collectionAliases||={};save.metadata.comicsManga.collectionAliases[key]=clean});return true}
const prefsFor=(state=getState())=>({...defaults,...(state.metadata?.comicsManga?.preferences||{})});
const itemStatus=status=>status==="planned"?"backlog":status==="completed"?"completed":status==="dropped"?"dropped":"in_progress";
const safeUrl=value=>{try{const url=new URL(String(value||""));return["http:","https:"].includes(url.protocol)?url.href:""}catch{return""}};
const artworkUrl=value=>{const raw=String(value||"");return /^\.\/assets\/artwork\/[a-z0-9_.-]+$/i.test(raw)?raw:safeUrl(raw)};
const statusLabel=status=>({planned:"PLANNED",reading:"READING",cooking:"LETTING IT COOK",paused:"PAUSED",completed:"COMPLETED",dropped:"DROPPED"}[status]||"PLANNED");
const publicationLabel=status=>({ongoing:"ONGOING",hiatus:"ON HIATUS",complete:"PUBLICATION COMPLETE",cancelled:"CANCELLED",unknown:"STATUS UNKNOWN"}[status]||"STATUS UNKNOWN");
const laneLabel=lane=>({official_english_chapters:"OFFICIAL ENGLISH CHAPTERS",original_chapters:"ORIGINAL-LANGUAGE CHAPTERS",english_volumes:"ENGLISH VOLUMES",original_volumes:"ORIGINAL-LANGUAGE VOLUMES",comic_issues:"INDIVIDUAL COMIC ISSUES",collected_editions:"COLLECTED EDITIONS",manual:"MANUAL TRACKING"}[lane]||"MANUAL TRACKING");
const unitLabel=(meta,singular=false)=>{const value=UNITS.has(meta.progressUnit)?meta.progressUnit:"chapters";return singular?({chapters:"CHAPTER",issues:"ISSUE",volumes:"VOLUME",editions:"EDITION",simple:"WORK"}[value]):value.toUpperCase()};
const newCountFor=item=>{const meta=metaFor(item);if(meta.readingStatus==="planned")return 0;const explicit=(meta.releases||[]).filter(release=>release.status!=="read").length;if(explicit)return explicit;const latest=Number(meta.latestKnown||0),read=Number(meta.readThrough||0);return latest>read?Math.max(1,Math.ceil(latest-read)):0};

export function ensureComicsManga(){
  if(!document.querySelector("link[data-comics-manga-styles]")){const link=document.createElement("link");link.rel="stylesheet";link.href="./css/comics-manga.css?v=20260831-comics-v2-v3";link.dataset.comicsMangaStyles="";document.head.append(link)}
  const state=getState();if(Number(state.metadata?.comicsManga?.version||0)>=4){ensureComicsMangaV2();return}
  const targets=new Map(Object.entries(LEGACY_COLLECTIONS).flatMap(([collectionId,format])=>(state.collections?.[collectionId]?.itemIds||[]).map(id=>[id,format])));
  update(save=>{
    const startedAt=new Date().toISOString(),items=Object.values(save.items||{}).filter(item=>item.wing==="manga"||targets.has(item.id));
    for(const item of items){
      const format=FORMATS.has(item.comicMeta?.format)?item.comicMeta.format:targets.get(item.id)||(FORMATS.has(item.type)?item.type:"manga");
      const prior=item.comicMeta?.readingStatus||(item.status==="completed"?"completed":item.status==="in_progress"?"reading":"planned");
      item.legacy||={};if(item.wing!=="manga")item.legacy.originalWing||=item.wing;
      item.wing="manga";item.type=format==="manga"?"manga":"comic";item.owned=false;
      item.comicMeta={format,readingStatus:READING.has(prior)?prior:"planned",publicationStatus:"unknown",progressUnit:format==="manga"?"chapters":format==="graphic_novel"?"simple":"issues",readThrough:Number(item.progress?.completed||0),latestKnown:Number(item.progress?.total||0),releaseLane:format==="manga"?"official_english_chapters":"comic_issues",monitoring:["reading","cooking"].includes(prior),hidden:false,releases:[],sourceLedger:{},readingAccess:{kindleOwned:false,kindleUrl:"",webUrl:"",preferred:"auto"},importedAt:startedAt,legacySuggestion:item.legacy?.collectionId==="collection_legacy_man_next_reads_your_exact_taste",...(item.comicMeta||{})};
      item.comicMeta.readingAccess={kindleOwned:false,kindleUrl:"",webUrl:"",preferred:"auto",...(item.comicMeta.readingAccess||{})};
      item.status=itemStatus(item.comicMeta.readingStatus);
    }
    let onePiece=Object.values(save.items||{}).find(item=>item.wing==="manga"&&String(item.title||"").trim().toLowerCase()==="one piece");
    if(!onePiece){
      onePiece={id:"manga_one_piece",type:"manga",wing:"manga",title:"One Piece",creator:"Eiichiro Oda",publisher:"Shueisha / VIZ Media",year:1997,genres:["Manga","Adventure","Fantasy","Comedy"],description:"Monkey D. Luffy and the Straw Hat Pirates voyage across the Grand Line in search of the legendary One Piece.",status:"in_progress",owned:false,favorite:true,addedAt:startedAt};
      save.items[onePiece.id]=onePiece;
    }
    onePiece.wing="manga";onePiece.type="manga";onePiece.owned=false;onePiece.favorite=true;onePiece.status="in_progress";onePiece.artwork="./assets/artwork/manga_one_piece-viz-vol1.jpg";
    onePiece.comicMeta={...(onePiece.comicMeta||{}),format:"manga",readingStatus:"reading",publicationStatus:"ongoing",progressUnit:"chapters",readThrough:1191,latestKnown:1191,releaseLane:"official_english_chapters",monitoring:true,hidden:false,releases:[],featuredRank:1,lastReleaseLabel:"Chapter 1191 · August 23, 2026",lastCheckedAt:startedAt,artworkCredit:"VIZ Media · One Piece Vol. 1",sourceLedger:{...(onePiece.comicMeta?.sourceLedger||{}),primary:{name:"VIZ Shonen Jump",url:"https://www.viz.com/shonenjump/chapters/one-piece",checkedAt:startedAt},officialUrl:"https://www.viz.com/shonenjump/chapters/one-piece",externalId:"one-piece"},readingAccess:{kindleOwned:false,kindleUrl:"",webUrl:"https://www.viz.com/shonenjump/chapters/one-piece",preferred:"web",...(onePiece.comicMeta?.readingAccess||{})},addedBy:onePiece.comicMeta?.addedBy||"vault_seed",importedAt:onePiece.comicMeta?.importedAt||startedAt};
    save.metadata.comicsManga={version:4,startedAt,migratedRecords:items.length,seededRecords:["manga_one_piece"],preferences:{...defaults,...(save.metadata.comicsManga?.preferences||{})},lastCheckedAt:save.metadata.comicsManga?.lastCheckedAt||null,lastCheckStatus:save.metadata.comicsManga?.lastCheckStatus||"never"};
    save.metadata.readerServices={version:1,kindle:{libraryUrl:KINDLE_LIBRARY_URL,connectedAt:save.metadata.readerServices?.kindle?.connectedAt||null},cookieManga:{enabled:true,packageName:COOKIE_MANGA_PACKAGE,playStoreUrl:COOKIE_MANGA_PLAY_URL},...(save.metadata.readerServices||{})};
  });
  ensureComicsMangaV2();
}

export function applyComicArtworkFit(root=document){
  root.querySelectorAll(".comic-cover img,.comic-release-cover img,.comic-home-cover img,.comic-recommendation-cover img").forEach(img=>{
    const fit=()=>{
      const frame=img.parentElement;
      if(!frame||!img.naturalWidth||!img.naturalHeight)return;
      const sourceRatio=img.naturalWidth/img.naturalHeight;
      const frameRatio=(frame.clientWidth||2)/(frame.clientHeight||3);
      img.classList.toggle("comic-fit-contain",sourceRatio>1.05);
    };
    if(img.complete)fit();else img.addEventListener("load",fit,{once:true});
  });
}

export const allComics=(state=getState())=>Object.values(state.items||{}).filter(item=>item.wing==="manga"&&item.comicMeta);
export function setComicPreference(field,value){if(!Object.hasOwn(defaults,field))return;update(save=>{save.metadata.comicsManga.preferences={...defaults,...(save.metadata.comicsManga.preferences||{}),[field]:value}})}
export function resetComicPreferences(){update(save=>{save.metadata.comicsManga.preferences={...defaults}})}
export function toggleComicFavorite(itemId){if(!getState().items[itemId])return false;update(save=>{save.items[itemId].favorite=!save.items[itemId].favorite});return Boolean(getState().items[itemId].favorite)}
export function setComicOwned(itemId,owned){update(save=>{const item=save.items[itemId];if(item?.comicMeta)item.owned=Boolean(owned)});return Boolean(owned)}
export function hideComicCard(itemId,hidden=true){if(!getState().items[itemId]?.comicMeta)return false;update(save=>{save.items[itemId].comicMeta.hidden=Boolean(hidden)});return true}
export function setComicStatus(itemId,status){if(!READING.has(status)||!getState().items[itemId]?.comicMeta)return false;update(save=>{const item=save.items[itemId];item.comicMeta.readingStatus=status;item.status=itemStatus(status);item.comicMeta.monitoring=comicMonitoringEligible(item)});emit("COMIC_READING_STATUS_CHANGED",{itemId,wing:"manga",meta:{title:getState().items[itemId]?.title,status}});return true}
export function setComicField(itemId,field,value){
  if(!getState().items[itemId]?.comicMeta)return false;
  update(save=>{const meta=save.items[itemId].comicMeta;if(field==="publicationStatus"&&PUBLICATION.has(value))meta[field]=value;else if(field==="progressUnit"&&UNITS.has(value))meta[field]=value;else if(field==="releaseLane"&&LANES.has(value))meta[field]=value;else if(field==="monitoring"){meta.monitoring=value===true||value==="true"||value==="on";meta.monitoringOverride=meta.monitoring;}else if(field==="notes")meta.notes=String(value||"").slice(0,4000);else if(["readThrough","latestKnown"].includes(field)){meta[field]=Math.max(0,Number(value)||0);if(field==="readThrough"&&meta.readThrough>Number(meta.latestKnown||0))meta.latestKnown=meta.readThrough;if(field==="readThrough")(meta.releases||[]).forEach(release=>{if(Number(release.number||0)<=meta.readThrough)release.status="read"})}});return true;
}
export function openComicEditDialog(itemId,onChanged=()=>{}){
  const item=getState().items[itemId],meta=item?.comicMeta;if(!meta)return false;
  const genres=(item.genres||[]).filter(value=>!["manga","comics"].includes(String(value).toLowerCase())).join(", ");
  openModal({title:`EDIT SERIES — ${item.title}`,body:`<div class="comic-confirm-form"><div class="comic-field-grid"><label>TITLE<input data-comic-edit-field="title" value="${esc(item.title)}"></label><label>CREATOR<input data-comic-edit-field="creator" value="${esc(item.creator||"")}"></label><label>PUBLISHER<input data-comic-edit-field="publisher" value="${esc(item.publisher||"")}"></label><label>YEAR<input data-comic-edit-field="year" type="number" min="0" value="${Number(item.year||0)||""}"></label><label>FORMAT<select data-comic-edit-field="format">${[...COMIC_FORMATS].map(value=>`<option value="${value}" ${meta.format===value?"selected":""}>${value.replaceAll("_"," ").toUpperCase()}</option>`).join("")}</select></label><label>GENRES<input data-comic-edit-field="genres" value="${esc(genres)}"></label></div><label>DESCRIPTION<textarea data-comic-edit-field="description" rows="6">${esc(item.description||"")}</textarea></label><p class="muted">Manual edits are protected. Future refreshes may fill blanks, but will not silently replace these fields.</p></div>`,actions:[{label:"CANCEL",handler:()=>closeModal()},{label:"SAVE MANUAL EDITS",primary:true,handler:()=>{const root=document.querySelector("#modal-root"),value=field=>root.querySelector(`[data-comic-edit-field="${field}"]`)?.value?.trim()||"",changedAt=new Date().toISOString();update(save=>{const target=save.items[itemId],data=target?.comicMeta;if(!target||!data)return;target.title=value("title")||target.title;target.creator=value("creator");target.publisher=value("publisher");target.year=Number(value("year"))||null;target.genres=[...new Set([data.format==="manga"?"Manga":"Comics",...value("genres").split(",").map(entry=>entry.trim()).filter(Boolean)])].slice(0,12);target.description=value("description");const format=value("format");if(COMIC_FORMATS.has(format))data.format=format;data.metadataAuthority||={manualFields:[],fieldSources:{},conflicts:[],policyVersion:1};data.metadataAuthority.manualFields=[...new Set([...(data.metadataAuthority.manualFields||[]),"title","creator","publisher","year","genres","description","format"])];for(const field of data.metadataAuthority.manualFields)data.metadataAuthority.fieldSources[field]={source:"manual",checkedAt:changedAt};data.identityEditedAt=changedAt});closeModal();onChanged();toast("SERIES DETAILS SAVED","Manual fields are protected from automatic replacement.")}}]});return true;
}
export function markComicThroughLatest(itemId){const item=getState().items[itemId],latest=Number(item?.comicMeta?.latestKnown||0);if(!item?.comicMeta||latest<=0)return false;setComicField(itemId,"readThrough",latest);emit("COMIC_RELEASES_READ",{itemId,wing:"manga",meta:{title:item.title,through:latest}});return true}

const readingAccessFor=item=>({kindleOwned:false,kindleUrl:"",webUrl:"",preferred:"auto",...(metaFor(item).readingAccess||{})});
const sourceUrlFor=item=>safeUrl(readingAccessFor(item).webUrl||metaFor(item).sourceLedger?.officialUrl||metaFor(item).sourceLedger?.primary?.url);
function recordReaderOpen(itemId,service,url){
  const openedAt=new Date().toISOString();
  update(save=>{const meta=save.items[itemId]?.comicMeta;if(!meta)return;meta.readingAccess={kindleOwned:false,kindleUrl:"",webUrl:"",preferred:"auto",...(meta.readingAccess||{}),lastOpenedAt:openedAt,lastService:service,lastUrl:safeUrl(url)}});
  emit("COMIC_READER_OPENED",{itemId,wing:"manga",meta:{title:getState().items[itemId]?.title,service}});
}
function launchReader(itemId,service,url){const target=safeUrl(url);if(!target)return false;recordReaderOpen(itemId,service,target);window.open(target,"_blank","noopener,noreferrer");return true}

export function openKindleAccount(){
  update(save=>{save.metadata.readerServices||={};save.metadata.readerServices.kindle={...(save.metadata.readerServices.kindle||{}),libraryUrl:KINDLE_LIBRARY_URL,connectedAt:new Date().toISOString()}});
  window.open(KINDLE_LIBRARY_URL,"_blank","noopener,noreferrer");
  return true;
}

export function openPreferredComicReader(itemId){
  const item=getState().items[itemId];if(!item?.comicMeta)return{opened:false,reason:"missing_record"};
  const access=readingAccessFor(item),web=sourceUrlFor(item);
  if(access.preferred==="kindle"&&access.kindleOwned)return{opened:launchReader(itemId,"kindle",access.kindleUrl||KINDLE_LIBRARY_URL),service:"kindle"};
  if(web)return{opened:launchReader(itemId,"web",web),service:"web"};
  if(access.kindleOwned)return{opened:launchReader(itemId,"kindle",access.kindleUrl||KINDLE_LIBRARY_URL),service:"kindle"};
  return{opened:false,reason:"missing_source"};
}

async function fetchReaderHandoff(url){
  const response=await fetch("./__vault/reader/handoff",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"reader-handoff"},body:JSON.stringify({url})});
  if(!response.ok)throw new Error("Reader handoff is unavailable.");return response.json();
}

export function openComicReaderDialog(itemId,onChanged=()=>{}){
  const item=getState().items[itemId];if(!item?.comicMeta)return false;
  const access=readingAccessFor(item),web=sourceUrlFor(item);
  openModal({title:`READ / SOURCES — ${item.title}`,body:`<div class="comic-reader-dialog"><p>Choose where this title opens. The Vault stores links only and never stores your Amazon password.</p><div class="comic-reader-grid"><section class="comic-reader-service"><span class="eyebrow">KINDLE ACCOUNT</span><label class="comic-check-label"><input type="checkbox" data-reader-kindle-owned ${access.kindleOwned?"checked":""}> I OWN THIS TITLE ON KINDLE</label><label>DIRECT KINDLE BOOK LINK <input type="url" data-reader-kindle-url value="${esc(access.kindleUrl)}" placeholder="OPTIONAL — READ.AMAZON.COM LINK"></label><button class="button" data-reader-open-kindle>OPEN KINDLE ACCOUNT</button></section><section class="comic-reader-service"><span class="eyebrow">WEB READER</span><label>PRIMARY READING LINK <input type="url" data-reader-web-url value="${esc(web)}" placeholder="HTTPS://…"></label><label>PREFERRED READER <select data-reader-preferred><option value="auto" ${access.preferred==="auto"?"selected":""}>AUTOMATIC</option><option value="web" ${access.preferred==="web"?"selected":""}>WEB SOURCE</option><option value="kindle" ${access.preferred==="kindle"?"selected":""}>KINDLE</option></select></label><button class="button primary" data-reader-open-web>OPEN WEB SOURCE</button></section></div><section class="comic-reader-service comic-reader-cookie"><div><span class="eyebrow">COOKIEMANGA HANDOFF</span><p>Generate a local QR code for the saved web link, or open the same link in CookieManga on Android.</p></div><button class="button" data-reader-cookie>PREPARE PHONE HANDOFF</button><div class="comic-reader-qr" data-reader-qr hidden></div></section></div>`,actions:[{label:"SAVE READER SETTINGS",primary:true,handler:dialog=>{const webUrl=safeUrl(dialog.querySelector("[data-reader-web-url]").value),kindleUrl=safeUrl(dialog.querySelector("[data-reader-kindle-url]").value),kindleOwned=dialog.querySelector("[data-reader-kindle-owned]").checked,preferred=dialog.querySelector("[data-reader-preferred]").value;update(save=>{const meta=save.items[itemId]?.comicMeta;if(!meta)return;meta.readingAccess={...(meta.readingAccess||{}),kindleOwned,kindleUrl,webUrl,preferred:["auto","web","kindle"].includes(preferred)?preferred:"auto"}});closeModal();onChanged();toast("READER SETTINGS SAVED",item.title)}}]});
  const root=document.querySelector("#modal-root");
  root.querySelector("[data-reader-open-kindle]").onclick=()=>openKindleAccount();
  root.querySelector("[data-reader-open-web]").onclick=()=>{const url=safeUrl(root.querySelector("[data-reader-web-url]").value);if(!url)return toast("READING LINK NEEDED","Add a valid HTTPS web-reader link first.");launchReader(itemId,"web",url)};
  root.querySelector("[data-reader-cookie]").onclick=async()=>{const url=safeUrl(root.querySelector("[data-reader-web-url]").value),target=root.querySelector("[data-reader-qr]");if(!url)return toast("READING LINK NEEDED","Add a valid HTTPS web-reader link first.");target.hidden=false;target.innerHTML="<span>PREPARING LOCAL HANDOFF…</span>";try{const handoff=await fetchReaderHandoff(url);target.innerHTML=`<img src="${esc(handoff.qrDataUrl)}" alt="QR code for CookieManga reading link"><div><b>SCAN WITH YOUR PHONE</b><a class="button primary" href="${esc(handoff.cookieIntentUrl)}">OPEN IN COOKIEMANGA</a><a class="button" href="${esc(COOKIE_MANGA_PLAY_URL)}" target="_blank" rel="noreferrer">COOKIEMANGA APP</a></div>`}catch(error){target.innerHTML=`<span>${esc(error.message)}</span>`}};
  return true;
}

function cover(item,className="comic-cover"){const art=artFor(item);return`<i class="${className}" style="--comic-h:${hue(item.title)}">${art?`<img src="${esc(art)}" alt="Cover for ${esc(item.title)}">`:`<b>${esc(initials(item.title))}</b>`}</i>`}
function card(item){const meta=metaFor(item),fresh=newCountFor(item),hidden=Boolean(meta.hidden),creator=item.creator||"CREATOR UNKNOWN",details=[item.publisher,item.year,...(item.genres||[]).filter(value=>!["manga","comics"].includes(String(value).toLowerCase())).slice(0,2)].filter(Boolean).join(" · ");return`<article class="comic-card ${fresh?"has-new":""} ${item.owned?"is-owned":""}"><button class="comic-card__open" data-open-comic="${esc(item.id)}">${cover(item)}<span class="comic-card__copy"><b>${esc(item.title)}</b><small>${esc(statusLabel(meta.readingStatus))} · ${esc(String(meta.format||"manga").replaceAll("_"," ").toUpperCase())}${item.owned?" · PHYSICALLY OWNED":""}</small><small class="comic-card__creator">${esc(creator)}</small>${details?`<small class="comic-card__metadata">${esc(details)}</small>`:""}<em>${meta.progressUnit==="simple"?(meta.readThrough?"READ":"NOT READ"):`READ THROUGH ${unitLabel(meta,true)} ${Number(meta.readThrough||0)}${Number(meta.latestKnown||0)?` · LATEST ${Number(meta.latestKnown)}`:""}`}</em></span><span class="comic-publication ${meta.publicationStatus==="hiatus"?"hiatus":""}">${esc(publicationLabel(meta.publicationStatus))}</span>${fresh?`<strong class="comic-new-count">${fresh} NEW</strong>`:""}</button><div class="comic-card-cover-action"><button data-comic-artwork="${esc(item.id)}">CHANGE COVER</button></div><div class="comic-card-controls"><button class="comic-read" data-comic-read="${esc(item.id)}" title="Open preferred reader">▶</button><button class="comic-owned ${item.owned?"on":""}" data-comic-owned="${esc(item.id)}" data-comic-owned-value="${item.owned?"false":"true"}" title="${item.owned?"Remove from physical collection":"Mark physically owned"}">▣</button><button class="comic-favorite ${item.favorite?"on":""}" data-comic-favorite="${esc(item.id)}" title="Favorite">★</button>${hidden?`<button class="comic-restore" data-comic-hide="${esc(item.id)}" data-comic-hidden="false" title="Restore card">↶</button>`:`<button class="comic-hide" data-vault-remove="${esc(item.id)}" title="Remove card">×</button>`}</div></article>`}
function comicGroupCard(kind,name,list){const key=`__group__:${kind}:${name}`,display=comicCollectionName(key),ordered=[...list].sort((a,b)=>a.title.localeCompare(b.title)),artwork=artFor(ordered.find(item=>artFor(item))||ordered[0]),fresh=ordered.reduce((sum,item)=>sum+newCountFor(item),0),label=kind==="local"?"SERIES":kind==="creator"?"CREATOR":"TYPE";return`<article class="comic-card ${fresh?"has-new":""}"><button class="comic-card__open" data-open-comic="${esc(key)}">${cover({title:display,artwork})}<span class="comic-card__copy"><b>${esc(display)}</b><small>${label} COLLECTION</small><small>${ordered.length} SERIES TRACKED</small><em>${fresh?`${fresh} NEW RELEASES`:"OPEN COLLECTION"}</em></span><span class="comic-publication">${label}</span></button><div class="comic-card-cover-action"><button data-comic-collection-rename="${esc(key)}">RENAME COLLECTION</button></div></article>`}
function groupedComicShelf(items){const groups=new Map(),singles=[];for(const item of items){const name=localComicCollection(item);if(!name){singles.push(item);continue}if(!groups.has(name))groups.set(name,[]);groups.get(name).push(item)}return [...groups].map(([name,list])=>list.length>1?comicGroupCard("local",name,list):list.map(item=>card(localComicDisplay(item))).join("")).join("")+singles.map(card).join("")}

const recommendationState=(state=getState())=>state.metadata?.comicsManga?.recommendations||{items:[],dismissed:[]};
function recommendationCard(rec){rec.artwork||=safeUrl(rec.coverImageUrl);const item={title:rec.title,artwork:rec.artwork};return`<article class="comic-card comic-recommendation-card"><button class="comic-card__open" data-comic-recommendation="${esc(rec.id)}">${cover(item)}<span class="comic-card__copy"><b>${esc(rec.title)}</b><small>${esc(String(rec.format||"manga").replaceAll("_"," ").toUpperCase())} · ${esc(rec.creator||"CREATOR UNKNOWN")}</small><em>${esc(rec.matchReason||"RECOMMENDED FROM YOUR VAULT")}</em></span><span class="comic-publication ${rec.publicationStatus==="hiatus"?"hiatus":""}">${esc(publicationLabel(rec.publicationStatus))}</span></button><div class="comic-card-controls"><button class="comic-hide" data-comic-recommendation-dismiss="${esc(rec.id)}" title="Not for me">×</button></div></article>`}
export function dismissComicRecommendation(recId){update(save=>{const recs=save.metadata.comicsManga.recommendations||={items:[],dismissed:[]};const rec=recs.items.find(item=>item.id===recId);if(rec&&!recs.dismissed.includes(rec.title))recs.dismissed.push(rec.title);recs.items=recs.items.filter(item=>item.id!==recId)});return true}
export async function refreshComicRecommendations(){
  const state=getState(),records=allComics(state),existing=new Set(records.map(item=>item.title.toLowerCase())),prior=recommendationState(state);
  const broaderInterests=Object.values(state.items||{}).filter(item=>["books","tv","movies","games","music","youtube","podcasts"].includes(item.wing)&&(item.favorite||["completed","in_progress","watching","reading","playing"].includes(String(item.status||item.bookMeta?.readingStatus||item.gameMeta?.playStatus||"")))).map(item=>({title:item.title,wing:item.wing,favorite:Boolean(item.favorite),status:String(item.status||item.bookMeta?.readingStatus||item.gameMeta?.playStatus||""),genres:item.genres||[]})).slice(0,60);
  const library=records.map(item=>{const status=metaFor(item).readingStatus||"planned";return{title:item.title,creator:item.creator||"",format:metaFor(item).format||item.type,status,favorite:Boolean(item.favorite),tasteWeight:item.favorite?5:status==="completed"?5:status==="reading"?4:status==="cooking"?3:status==="paused"?2:status==="planned"?0:1,genres:item.genres||[]}}).sort((a,b)=>b.tasteWeight-a.tasteWeight);
  const response=await fetch("./__vault/comics/recommendations",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-recommendations"},body:JSON.stringify({library,broaderInterests,dismissed:prior.dismissed||[]})});
  if(!response.ok){const failure=await response.json().catch(()=>({}));throw new Error(response.status===429?"Recommendation search is busy. Try again shortly.":failure.detail||"Recommendations are unavailable right now.")}
  const payload=await response.json(),items=[];
  for(const candidate of payload.candidates||[]){if(existing.has(String(candidate.title).toLowerCase()))continue;const id=createId("comic_rec");let artwork="";try{const artResponse=await fetch("./__vault/comics/artwork/download",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-artwork-download"},body:JSON.stringify({itemId:id,imageUrl:safeUrl(candidate.coverImageUrl),pageUrl:safeUrl(candidate.coverSourceUrl)})});if(artResponse.ok)artwork=(await artResponse.json()).path}catch{}artwork||=safeUrl(candidate.coverImageUrl);items.push({id,...candidate,artwork})}
  update(save=>{save.metadata.comicsManga.recommendations={items:items.slice(0,8),dismissed:prior.dismissed||[],generatedAt:payload.generatedAt||new Date().toISOString()}});
  return{count:items.length};
}
function addRecommendationToVault(rec){
  const id=createId(rec.format==="manga"?"manga":"comic"),addedAt=new Date().toISOString(),format=FORMATS.has(rec.format)?rec.format:"manga",progressUnit=UNITS.has(rec.unitType)?rec.unitType:format==="manga"?"chapters":"issues";
  update(save=>{save.items[id]={id,type:format==="manga"?"manga":"comic",wing:"manga",title:rec.title,creator:rec.creator||"",publisher:rec.publisher||"",year:Number(rec.startYear||0)||null,genres:[...new Set([format==="manga"?"Manga":"Comics",...(rec.genres||[])])].slice(0,8),description:rec.description||"",status:"backlog",owned:false,favorite:false,artwork:"",addedAt,comicMeta:{format,readingStatus:"planned",publicationStatus:PUBLICATION.has(rec.publicationStatus)?rec.publicationStatus:"unknown",progressUnit,readThrough:0,latestKnown:Number(rec.totalUnits||0),releaseLane:LANES.has(rec.releaseLane)?rec.releaseLane:"manual",monitoring:false,hidden:false,releases:[],sourceLedger:{primary:rec.sourceUrl?{name:rec.sourceName||"Recommendation source",url:safeUrl(rec.sourceUrl),checkedAt:addedAt}:null,officialUrl:safeUrl(rec.officialUrl),externalId:String(rec.externalId||""),artwork:null},readingAccess:{kindleOwned:false,kindleUrl:"",webUrl:safeUrl(rec.officialUrl||rec.sourceUrl),preferred:"auto"},artworkKind:"",artworkPolicyVersion:3,addedBy:"vault_recommendation",importedAt:addedAt}};const recs=save.metadata.comicsManga.recommendations;if(recs)recs.items=recs.items.filter(item=>item.id!==rec.id)});
  if(rec.artwork)queueArtworkApproval({kind:"comic",itemId:id,target:"main",key:`comic:${id}:main`,title:rec.title,subtitle:"Recommendation cover candidate",path:rec.artwork,sourceName:rec.coverSourceName||"Published cover",sourceUrl:safeUrl(rec.coverSourceUrl||rec.sourceUrl)});
  ensureComicsMangaV2();emit("COMIC_RECOMMENDATION_ADDED",{itemId:id,wing:"manga",meta:{title:rec.title}});return id;
}
export function openComicRecommendationDialog(recId,onAdded=()=>{},onChanged=()=>{}){
  const rec=recommendationState().items.find(item=>item.id===recId);if(!rec)return false;const source=safeUrl(rec.officialUrl||rec.sourceUrl);
  openModal({title:`RECOMMENDATION — ${rec.title}`,body:`<div class="comic-recommendation-dossier">${cover({title:rec.title,artwork:rec.artwork},"comic-recommendation-cover")}<section><span class="eyebrow">SPOILER-FREE RECOMMENDATION DOSSIER</span><h2>${esc(rec.title)}</h2><p class="byline">${esc(rec.creator||"Creator unknown")} · ${esc(String(rec.format||"manga").replaceAll("_"," ").toUpperCase())}</p><div class="comic-dossier-genres">${(rec.genres||[]).map(genre=>`<span>${esc(genre)}</span>`).join("")}</div><h3>SUMMARY</h3><p>${esc(rec.description||"No verified summary was returned.")}</p><h3>WHY IT FITS YOUR VAULT</h3><p>${esc(rec.matchReason||"This recommendation reflects your active reading and favorites.")}</p>${source?`<a href="${esc(source)}" target="_blank" rel="noreferrer">VIEW VERIFIED SOURCE</a>`:""}</section></div>`,actions:[{label:"NOT FOR ME",handler:()=>{dismissComicRecommendation(recId);closeModal();onChanged()}},{label:"ADD AS PLANNED",primary:true,handler:()=>{const id=addRecommendationToVault(rec);closeModal();onAdded(id)}}]});return true;
}

export function getComicsMangaModel(search="",state=getState()){
  const prefs=prefsFor(state),q=search.trim().toLowerCase(),records=allComics(state);let visible=records.filter(item=>!q||`${item.title} ${item.creator||""} ${(item.genres||[]).join(" ")}`.toLowerCase().includes(q));
  if(prefs.scope==="hidden")visible=visible.filter(item=>metaFor(item).hidden);else{visible=visible.filter(item=>!metaFor(item).hidden);if(prefs.scope==="favorites")visible=visible.filter(item=>item.favorite);else if(prefs.scope==="owned")visible=visible.filter(item=>item.owned);else if(prefs.scope==="new")visible=visible.filter(item=>newCountFor(item)>0);else if(prefs.scope!=="all")visible=visible.filter(item=>metaFor(item).readingStatus===prefs.scope)}
  if(prefs.publication!=="all")visible=visible.filter(item=>metaFor(item).publicationStatus===prefs.publication);if(prefs.format!=="all")visible=visible.filter(item=>metaFor(item).format===prefs.format);
  visible.sort((a,b)=>prefs.sort==="title"?a.title.localeCompare(b.title):prefs.sort==="progress"?Number(metaFor(b).readThrough||0)-Number(metaFor(a).readThrough||0)||a.title.localeCompare(b.title):Number(metaFor(a).featuredRank||999)-Number(metaFor(b).featuredRank||999)||newCountFor(b)-newCountFor(a)||Number(b.favorite)-Number(a.favorite)||a.title.localeCompare(b.title));
  const newRecords=records.filter(item=>!metaFor(item).hidden&&newCountFor(item)>0).sort((a,b)=>newCountFor(b)-newCountFor(a));
  return{records,visible,newRecords,prefs,hiddenCount:records.filter(item=>metaFor(item).hidden).length,ownedCount:records.filter(item=>item.owned).length,missingArtworkCount:records.filter(item=>!artFor(item)).length,readingCount:records.filter(item=>metaFor(item).readingStatus==="reading").length,cookingCount:records.filter(item=>metaFor(item).readingStatus==="cooking").length,hiatusCount:records.filter(item=>metaFor(item).publicationStatus==="hiatus").length,totalNew:newRecords.reduce((sum,item)=>sum+newCountFor(item),0)};
}

export function renderComicsMangaWing(search=""){
  const model=getComicsMangaModel(search),{prefs}=model;
  const scopes=[["all","ALL"],["owned",`OWNED ${model.ownedCount}`],["reading","READING"],["cooking","LETTING IT COOK"],["planned","PLANNED"],["favorites","FAVORITES"],["recommended","RECOMMENDED"],["paused","PAUSED"],["completed","COMPLETED"],["dropped","DROPPED"],["new","NEW"],...(model.hiddenCount?[["hidden",`HIDDEN ${model.hiddenCount}`]]:[])];
  const recommendations=recommendationState().items.filter(rec=>!search||`${rec.title} ${rec.creator||""} ${(rec.genres||[]).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  const releaseShelf=model.newRecords.length?`<section class="comic-release-watch panel"><header><div><span class="eyebrow">RELEASE WATCH // UNREAD UNTIL MARKED</span><h2>${model.totalNew} NEW ${model.totalNew===1?"RELEASE":"RELEASES"}</h2></div><button class="button" data-comic-pref="scope" data-comic-value="new">VIEW ALL NEW</button></header><div class="comic-release-strip">${model.newRecords.slice(0,5).map(item=>`<button data-open-comic="${esc(item.id)}">${cover(item,"comic-release-cover")}<span><b>${esc(item.title)}</b><small>${newCountFor(item)} NEW ${unitLabel(metaFor(item))}</small><em>${esc(publicationLabel(metaFor(item).publicationStatus))}</em></span></button>`).join("")}</div></section>`:`<section class="comic-release-watch comic-release-watch--quiet panel"><div><span class="eyebrow">RELEASE WATCH</span><h2>NO UNREAD UPDATES</h2><p>New issues and chapters remain here until you mark them read.</p></div><button class="button" data-comic-check>CHECK FOR UPDATES</button></section>`;
  const operationShelves=renderComicsV2Shelves(model.records);return`<div class="comics-manga-wing"><section class="comic-command-deck"><div class="comic-archive-console panel"><span class="eyebrow">TRACKED, NOT OWNED // FLEXIBLE READING ARCHIVE</span><h2>COMICS / MANGA</h2><div class="comic-vitals"><span><b>${model.records.length}</b>TRACKED</span><span><b>${model.readingCount}</b>READING</span><span><b>${model.cookingCount}</b>COOKING</span><span class="new"><b>${model.totalNew}</b>NEW</span></div><div class="comic-command-actions"><button class="button primary" data-comic-add>+ ADD SERIES</button><button class="button" data-comic-metadata-repair>CORRECT ALL METADATA</button><button class="button" data-comic-check>CHECK FOR UPDATES</button><button class="button" data-kindle-connect>KINDLE ACCOUNT</button>${model.missingArtworkCount?`<button class="button comic-art-fill" data-comic-art-backfill>FILL ALL ART · ${model.missingArtworkCount}</button>`:""}</div></div>${releaseShelf}</section>
  ${operationShelves}<section class="comic-browser panel"><div class="comic-filter-row">${scopes.map(([value,label])=>`<button class="button ${prefs.scope===value?"primary":""}" data-comic-pref="scope" data-comic-value="${value}">${label}</button>`).join("")}</div><div class="comic-select-row"><label>FORMAT<select data-comic-select="format"><option value="all">ALL FORMATS</option>${[["manga","MANGA"],["comic","COMICS"],["graphic_novel","GRAPHIC NOVELS"],["webcomic","WEBCOMICS"]].map(([value,label])=>`<option value="${value}" ${prefs.format===value?"selected":""}>${label}</option>`).join("")}</select></label><label>PUBLICATION<select data-comic-select="publication"><option value="all">ALL PUBLICATION STATES</option>${[["ongoing","ONGOING"],["hiatus","ON HIATUS"],["complete","COMPLETE"],["cancelled","CANCELLED"],["unknown","UNKNOWN"]].map(([value,label])=>`<option value="${value}" ${prefs.publication===value?"selected":""}>${label}</option>`).join("")}</select></label><label>SORT<select data-comic-select="sort"><option value="new" ${prefs.sort==="new"?"selected":""}>NEW FIRST</option><option value="title" ${prefs.sort==="title"?"selected":""}>TITLE</option><option value="progress" ${prefs.sort==="progress"?"selected":""}>PROGRESS</option></select></label><span>${prefs.scope==="recommended"?recommendations.length:model.visible.length} SHOWN</span><button class="button" data-comic-reset>RESET</button></div></section>
  ${prefs.scope==="recommended"?`<section class="comic-poster-wall panel"><header><div><span class="eyebrow">GROUNDED IN FAVORITES + ACTIVE READING</span><h2>RECOMMENDED FOR YOU</h2></div><button class="button primary" data-comic-recommendations-refresh>${recommendations.length?"REFRESH RECOMMENDATIONS":"BUILD RECOMMENDATIONS"}</button></header>${recommendations.length?`<div class="comic-card-grid">${recommendations.map(recommendationCard).join("")}</div>`:`<div class="empty"><b>NO RECOMMENDATIONS PREPARED.</b>Build a spoiler-free edition from your current Vault activity.</div>`}</section>`:model.visible.length?`<section class="comic-poster-wall panel"><header><div><span class="eyebrow">YOUR READING RECORDS</span><h2>${prefs.scope==="cooking"?"LETTING IT COOK":prefs.scope==="hidden"?"HIDDEN CARDS":prefs.scope==="new"?"NEW RELEASES":"COMICS / MANGA ARCHIVE"}</h2></div><span>${model.visible.length} SERIES · SCROLL TO BROWSE</span></header><div class="comic-card-grid">${prefs.scope==="all"&&!search?groupedComicShelf(model.visible):model.visible.map(card).join("")}</div></section>`:`<div class="panel empty"><b>NO SERIES MATCH THIS SHELF.</b>Add a series or change the current filters.</div>`}</div>`;
}

export function renderComicsMangaShell(content,screen="catalog"){return renderAtomicWingShell({active:"manga",title:"COMICS / MANGA ARCHIVE",section:screen==="series"?"SERIES FILE":"RELEASE WATCH",content,footer:"TRACKED, NOT OWNED // VAULT FIRST"})}
export function renderComicSeriesPage(itemId){
  if(itemId.startsWith("__group__:")){const [,kind,...parts]=itemId.split(":"),name=parts.join(":"),display=comicCollectionName(itemId),list=allComics().filter(item=>kind==="local"?localComicCollection(item)===name:kind==="creator"?item.creator===name:kind==="publisher"?item.publisher===name:kind==="genre"?(item.genres||[]).includes(name):String(metaFor(item).format||item.type||"comic").replaceAll("_"," ").toUpperCase()===name).sort((a,b)=>a.title.localeCompare(b.title));if(!list.length)return`<div class="panel empty"><b>COMICS / MANGA COLLECTION NOT FOUND.</b></div>`;return`<div class="comic-series-page"><div class="comic-dossier-nav"><button class="comic-back" data-comic-back>← COMICS / MANGA</button><span>${kind.toUpperCase()} FILE // ${list.length} SERIES</span></div><section class="panel comic-poster-wall"><header><div><span class="eyebrow">CLEAN LIBRARY GROUP</span><h2>${esc(display)}</h2></div><button class="button" data-comic-collection-rename="${esc(itemId)}">RENAME COLLECTION</button><span>${list.reduce((sum,item)=>sum+newCountFor(item),0)} NEW</span></header><div class="comic-card-grid">${list.map(item=>card(localComicDisplay(item))).join("")}</div></section></div>`}
  const item=getState().items[itemId];if(!item?.comicMeta)return`<div class="panel empty"><b>COMICS / MANGA RECORD NOT FOUND.</b></div>`;
  const meta=metaFor(item),access=readingAccessFor(item),fresh=newCountFor(item),official=safeUrl(meta.sourceLedger?.officialUrl||meta.sourceLedger?.primary?.url),sourceName=meta.sourceLedger?.primary?.name||"NO VERIFIED SOURCE",genres=(item.genres||[]).filter(value=>String(value).toLowerCase()!=="manga"&&String(value).toLowerCase()!=="comics"),lastOpened=access.lastOpenedAt?new Date(access.lastOpenedAt).toLocaleDateString():"NEVER";
  const releases=(meta.releases||[]).slice().sort((a,b)=>Number(b.number||0)-Number(a.number||0)).slice(0,12);
  const volumes=(meta.volumes||[]).slice().sort((a,b)=>Number(a.number||0)-Number(b.number||0));
  const structureMode=meta.structure?.mode||"volumes_chapters",releaseLabel=structureMode==="issues_collections"?"ISSUE":structureMode==="editions"?"EDITION":structureMode==="seasons_chapters"?"SEASON":structureMode==="mixed"?"RELEASE":"VOLUME";
  const volumeShelf=volumes.length?`<div class="comic-volume-grid">${volumes.map(volume=>`<article class="comic-volume-card ${volume.read?"is-read":""}"><button class="comic-volume-art-pick" data-comic-volume-art="${Number(volume.number||0)}" data-comic-id="${esc(item.id)}" title="Choose artwork for ${releaseLabel} ${Number(volume.number||0)}">${candidateCover({title:volume.title,coverImageUrl:volume.artwork},"comic-volume-cover")}<span><b>${releaseLabel} ${Number(volume.number||0)}</b><small>${esc(volume.title||item.title)}</small><em>${volume.artwork?"CHANGE COVER":"FIND A COVER"}</em></span></button><button class="button ${volume.read?"":"primary"}" data-comic-volume-read="${Number(volume.number||0)}" data-comic-id="${esc(item.id)}">${volume.read?"MARK UNREAD":"MARK READ"}</button></article>`).join("")}</div>`:`<div class="empty"><b>NO ${releaseLabel} CARDS YET.</b>Build this shelf from verified release records or local files.</div>`;
  const v2Panels=renderComicV2SeriesPanels(item);
  const releaseRows=releases.length?releases.map(release=>`<article><b>${esc(unitLabel(meta,true))} ${esc(release.number??"—")}</b><span>${esc(release.label||release.date||"VERIFIED RELEASE")}</span><em class="${release.status==="read"?"read":""}">${release.status==="read"?"READ":"NEW"}</em></article>`).join(""):(Number(meta.latestKnown||0)?`<article><b>${unitLabel(meta,true)} ${Number(meta.latestKnown)}</b><span>${esc(meta.lastReleaseLabel||"LATEST VERIFIED RELEASE")}</span><em class="${fresh?"":"read"}">${fresh?"NEW":"READ"}</em></article>`:"");
  return`<div class="comic-series-page comic-dossier"><div class="comic-dossier-nav"><button class="comic-back" data-comic-back>← COMICS / MANGA</button><span>SERIES DOSSIER // ${esc(statusLabel(meta.readingStatus))}</span></div>
  <section class="comic-series-hero panel">${cover(item,"comic-series-cover")}<div class="comic-series-copy"><span class="eyebrow">${esc(String(meta.format).replaceAll("_"," ").toUpperCase())} // ${esc(publicationLabel(meta.publicationStatus))}</span><div class="comic-title-row"><h2>${esc(item.title)}</h2><button class="comic-favorite large ${item.favorite?"on":""}" data-comic-favorite="${esc(item.id)}" title="Favorite">★</button></div>${item.creator?`<p class="comic-creator">${esc(item.creator)}</p>`:""}<div class="comic-genre-line">${genres.length?genres.map(genre=>`<span>${esc(genre)}</span>`).join(""):"<span>GENRES NOT YET CATALOGED</span>"}</div><p>${esc(item.description||"A flexible reading record. Add progress and a verified source when you are ready.")}</p><div class="comic-series-actions"><button class="button primary" data-comic-read="${esc(item.id)}">READ LATEST</button><button class="button" data-comic-reader-manage="${esc(item.id)}">READ / SOURCES</button><button class="button comic-art-fill" data-comic-artwork="${esc(item.id)}">REPLACE COVER</button></div><div class="comic-series-stats"><span><b>${Number(meta.readThrough||0)}</b>READ THROUGH</span><span><b>${Number(meta.latestKnown||0)||"—"}</b>LATEST</span><span class="${fresh?"new":""}"><b>${fresh}</b>NEW</span><span><b>${meta.monitoring?"ON":"OFF"}</b>MONITOR</span></div>${fresh?`<div class="comic-update-alert"><span>${fresh} NEW ${unitLabel(meta)}</span><b>REMAINS NEW UNTIL YOU MARK IT READ</b><button class="button primary" data-comic-mark-latest="${esc(item.id)}">MARK THROUGH ${Number(meta.latestKnown||0)} READ</button></div>`:""}</div></section>
  <section class="panel comic-dossier-strip"><span><small>TYPE</small><b>${esc(String(meta.format||item.type).replaceAll("_"," ").toUpperCase())}</b></span><span><small>PUBLICATION</small><b>${esc(publicationLabel(meta.publicationStatus))}</b></span><span><small>CREATOR</small><b>${esc(item.creator||"UNKNOWN")}</b></span><span><small>PUBLISHER</small><b>${esc(item.publisher||"UNKNOWN")}</b></span><span><small>STARTED</small><b>${item.year||"UNKNOWN"}</b></span></section>
  <div class="comic-detail-grid"><section class="panel comic-control-panel"><header><span class="eyebrow">YOUR READING STATE</span><h3>READING CONTROL</h3></header><div class="comic-status-buttons">${["planned","reading","cooking","paused","completed","dropped"].map(status=>`<button class="button ${meta.readingStatus===status?"primary":""}" data-comic-status="${status}" data-comic-id="${esc(item.id)}">${statusLabel(status)}</button>`).join("")}</div><div class="comic-field-grid"><label>PROGRESS UNIT<select data-comic-field="progressUnit" data-comic-id="${esc(item.id)}">${[["chapters","CHAPTERS"],["issues","ISSUES"],["volumes","VOLUMES"],["editions","EDITIONS"],["simple","READ / UNREAD"]].map(([value,label])=>`<option value="${value}" ${meta.progressUnit===value?"selected":""}>${label}</option>`).join("")}</select></label><label>READ THROUGH<input type="number" min="0" step="0.1" value="${Number(meta.readThrough||0)}" data-comic-field="readThrough" data-comic-id="${esc(item.id)}"></label><label>LATEST KNOWN<input type="number" min="0" step="0.1" value="${Number(meta.latestKnown||0)}" data-comic-field="latestKnown" data-comic-id="${esc(item.id)}"></label><label>PUBLICATION<select data-comic-field="publicationStatus" data-comic-id="${esc(item.id)}">${["ongoing","hiatus","complete","cancelled","unknown"].map(value=>`<option value="${value}" ${meta.publicationStatus===value?"selected":""}>${publicationLabel(value)}</option>`).join("")}</select></label></div></section>
  <section class="panel comic-source-panel"><header><span class="eyebrow">READER + RELEASE MONITOR</span><h3>SOURCES</h3></header><div class="comic-source-vitals"><span><small>PRIMARY SOURCE</small><b>${esc(sourceName)}</b></span><span><small>PREFERRED READER</small><b>${esc(access.preferred==="auto"?"AUTOMATIC":access.preferred.toUpperCase())}</b></span><span><small>LAST OPENED</small><b>${esc(lastOpened)}</b></span></div><label>RELEASE LANE<select data-comic-field="releaseLane" data-comic-id="${esc(item.id)}">${[...LANES].map(value=>`<option value="${value}" ${meta.releaseLane===value?"selected":""}>${laneLabel(value)}</option>`).join("")}</select></label><div class="comic-monitor-state"><span><i class="${meta.monitoring?"on":""}"></i><b>${meta.monitoring?"MONITORING ENABLED":"MONITORING PAUSED"}</b><small>NOTHING IS MARKED READ AUTOMATICALLY</small></span><button class="button" data-comic-monitor="${esc(item.id)}" data-comic-monitor-value="${meta.monitoring?"false":"true"}">${meta.monitoring?"PAUSE":"ENABLE"}</button></div><button class="button primary" data-comic-reader-manage="${esc(item.id)}">MANAGE READING SOURCES</button>${meta.artworkCredit?`<small class="comic-art-credit">CURRENT ART · ${esc(meta.artworkCredit)}</small>`:""}${official?`<a class="button comic-official-link" href="${esc(official)}" target="_blank" rel="noreferrer">OPEN OFFICIAL SOURCE</a>`:`<button class="button" data-comic-rematch="${esc(item.id)}">FIND A VERIFIED SOURCE</button>`}</section></div>
  ${v2Panels}<section class="panel comic-volume-shelf"><header><div><span class="eyebrow">PUBLISHED VOLUMES // SOURCE ARTWORK</span><h3>VOLUME FILES</h3></div><button class="button primary" data-comic-volumes-refresh="${esc(item.id)}">${volumes.length?"REFRESH VOLUMES":"BUILD VOLUME CARDS"}</button></header>${volumeShelf}</section>
  <div class="comic-dossier-lower"><section class="panel comic-release-ledger"><header><div><span class="eyebrow">UNREAD UNTIL MARKED</span><h3>RELEASE HISTORY</h3></div><span>${fresh?`${fresh} NEW`:"CAUGHT UP"}</span></header>${releaseRows||`<div class="empty"><b>NO RELEASE HISTORY YET.</b>The Vault will build this ledger as verified updates arrive.</div>`}${fresh>1?`<p>${fresh-1} additional ${unitLabel(meta).toLowerCase()} are between your read point and the latest known release.</p>`:""}</section><section class="panel comic-notes-panel"><header><span class="eyebrow">PRIVATE // LOCAL VAULT DATA</span><h3>YOUR NOTES</h3></header><textarea data-comic-field="notes" data-comic-id="${esc(item.id)}" placeholder="WHY YOU ARE READING IT, WHERE YOU LEFT OFF, OR ANYTHING YOU WANT TO REMEMBER…">${esc(meta.notes||"")}</textarea><small>SAVED WHEN YOU LEAVE THIS FIELD.</small></section></div></div>`;
}

export async function refreshComicVolumes(itemId){
  const item=getState().items[itemId];if(!item?.comicMeta)throw new Error("Series record not found.");
  const response=await fetch("./__vault/comics/volumes",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-volumes"},body:JSON.stringify({itemId,title:item.title,creator:item.creator||""})});
  const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error("Published volume records could not be loaded right now.");
  const prior=new Map((item.comicMeta.volumes||[]).map(volume=>[Number(volume.number),volume]));
  update(save=>{const meta=save.items[itemId]?.comicMeta;if(!meta)return;meta.volumes=(payload.volumes||[]).map(volume=>({...prior.get(Number(volume.number)),...volume,artwork:prior.get(Number(volume.number))?.artwork||"",read:Boolean(prior.get(Number(volume.number))?.read)}));meta.volumesCheckedAt=payload.checkedAt});
  let queued=0;for(const volume of payload.volumes||[]){if(!volume.artwork||prior.get(Number(volume.number))?.artwork)continue;const id=queueArtworkApproval({kind:"comic_volume",itemId,target:String(volume.number),key:`comic_volume:${itemId}:${volume.number}`,title:`${item.title} · Volume ${volume.number}`,subtitle:volume.title||"Published volume cover",path:volume.artwork,sourceName:volume.sourceName||"Published volume source",sourceUrl:volume.sourceUrl||""});if(id)queued++}
  return{count:(payload.volumes||[]).length,artworkSaved:0,artworkQueued:queued};
}

export function toggleComicVolumeRead(itemId,number){let read=false;update(save=>{const volume=save.items[itemId]?.comicMeta?.volumes?.find(entry=>Number(entry.number)===Number(number));if(!volume)return;volume.read=!volume.read;read=volume.read});return read}

export async function openComicVolumeArtworkPicker(itemId,number,onChanged=()=>{}){
  const item=getState().items[itemId],volume=item?.comicMeta?.volumes?.find(entry=>Number(entry.number)===Number(number));if(!item||!volume)return false;
  openModal({title:`VOLUME ${number} COVER SEARCH`,body:`<div class="vault-ai-progress"><span class="eyebrow">PUBLISHED ARTWORK ONLY // NOTHING CHANGES YET</span><h3>FINDING 3–5 MATCHING COVERS…</h3><div class="vault-ai-progress__bar"><i></i></div><p>Checking book catalogs for ${esc(item.title)} Volume ${Number(number)}.</p></div>`});
  try{
    const response=await fetch("./__vault/comics/volume-covers",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-volume-covers"},body:JSON.stringify({itemId,title:item.title,creator:item.creator||"",number:Number(number)})});
    const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error("Cover choices could not be loaded right now.");const candidates=payload.candidates||[];
    if(!candidates.length){openModal({title:`VOLUME ${number} COVER SEARCH`,body:`<div class="empty"><b>NO CONFIDENT COVER OPTIONS FOUND.</b><p>The existing cover was kept. Try again later or after correcting the series metadata.</p></div>`,actions:[{label:"CLOSE",primary:true,handler:()=>closeModal()}]});return false}
    openModal({title:`CHOOSE VOLUME ${number} COVER`,body:`<div class="comic-volume-cover-options">${candidates.map((candidate,index)=>`<article><button data-volume-cover-choice="${index}"><img src="${esc(candidate.path)}" alt="Cover option ${index+1} for ${esc(item.title)} Volume ${Number(number)}"><span><b>OPTION ${index+1}</b><small>${esc(candidate.title||item.title)}</small><em>${esc(candidate.sourceName||"Published source")}</em></span></button>${safeUrl(candidate.sourceUrl)?`<a href="${esc(safeUrl(candidate.sourceUrl))}" target="_blank" rel="noreferrer">VERIFY SOURCE ↗</a>`:""}</article>`).join("")}</div><p class="muted">Choosing an option is the approval step. The card will not change until you click one.</p>`,actions:[{label:"KEEP CURRENT COVER",primary:true,handler:()=>closeModal()}]});
    const root=document.querySelector("#modal-root .modal__body");root.onclick=event=>{const button=event.target.closest("[data-volume-cover-choice]");if(!button)return;const candidate=candidates[Number(button.dataset.volumeCoverChoice)];if(!candidate)return;update(save=>{const target=save.items[itemId]?.comicMeta?.volumes?.find(entry=>Number(entry.number)===Number(number));if(target){target.artwork=candidate.path;target.sourceUrl=candidate.sourceUrl||target.sourceUrl;target.sourceName=candidate.sourceName||target.sourceName;target.artworkApprovedAt=new Date().toISOString()}});closeModal();onChanged();toast("VOLUME COVER APPROVED",`${item.title} · Volume ${number}`)};
    return true;
  }catch(error){openModal({title:"COVER SEARCH PAUSED",body:`<p>${esc(error.message)}</p><p>The current volume card was not changed.</p>`,actions:[{label:"CLOSE",primary:true,handler:()=>closeModal()}]});return false}
}

export async function openComicArtworkPicker(itemId,onChanged=()=>{}){
  const item=getState().items[itemId];if(!item?.comicMeta)return false;
  openModal({title:`${item.title} · COVER SEARCH`,body:`<div class="vault-ai-progress"><span class="eyebrow">PUBLISHED ARTWORK ONLY // NOTHING CHANGES YET</span><h3>FINDING 3–5 COVER OPTIONS…</h3><div class="vault-ai-progress__bar"><i></i></div><p>Verifying exact-series covers and caching previews locally.</p></div>`});
  try{
    const response=await fetch("./__vault/comics/artwork/options",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-artwork-options"},body:JSON.stringify({itemId,title:item.title,creator:item.creator||"",format:metaFor(item).format||item.type||"manga"})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error("Cover choices could not be loaded right now.");const options=payload.options||[];
    if(!options.length){openModal({title:"NO EXACT COVER OPTIONS FOUND",body:"<p>The current cover was kept. The Vault did not find a confident published match.</p>",actions:[{label:"CLOSE",primary:true,handler:()=>closeModal()}]});return false}
    openModal({title:`CHOOSE COVER — ${item.title}`,body:`<div class="comic-volume-cover-options comic-series-cover-options">${options.map((option,index)=>`<article><button data-comic-cover-choice="${index}"><img src="${esc(option.path)}" alt="Cover option ${index+1} for ${esc(item.title)}"><span><b>OPTION ${index+1}</b><small>${esc(option.label||item.title)}</small><em>${esc(option.sourceName||"Published source")}</em></span></button>${safeUrl(option.sourceUrl)?`<a href="${esc(safeUrl(option.sourceUrl))}" target="_blank" rel="noreferrer">VERIFY SOURCE ↗</a>`:""}</article>`).join("")}</div><p class="muted">Choosing an option is the approval step. The existing cover remains until you select one.</p>`,actions:[{label:"KEEP CURRENT COVER",primary:true,handler:()=>closeModal()}]});
    const root=document.querySelector("#modal-root .modal__body");root.onclick=event=>{const button=event.target.closest("[data-comic-cover-choice]");if(!button)return;const option=options[Number(button.dataset.comicCoverChoice)];if(!option)return;update(save=>{const target=save.items[itemId],meta=target?.comicMeta;if(!target||!meta)return;const approvedAt=new Date().toISOString();target.artwork=option.path;meta.artworkCredit=option.sourceName||"Published source";meta.artworkKind="published";meta.artworkAddedAt=approvedAt;meta.artworkOverride=true;meta.sourceLedger||={};meta.sourceLedger.artwork={name:option.sourceName||"Published source",url:safeUrl(option.sourceUrl),checkedAt:approvedAt,kind:"published"}});closeModal();onChanged();toast("COVER APPROVED",item.title)};return true;
  }catch(error){openModal({title:"COVER SEARCH PAUSED",body:`<p>${esc(error.message)}</p><p>The current cover was not changed.</p>`,actions:[{label:"CLOSE",primary:true,handler:()=>closeModal()}]});return false}
}

export function renderComicsHomeUpdates(state=getState()){
  const eligible=allComics(state).filter(item=>!metaFor(item).hidden&&newCountFor(item)>0&&(item.favorite||metaFor(item).readingStatus==="reading")).sort((a,b)=>newCountFor(b)-newCountFor(a)).slice(0,4);if(!eligible.length)return"";const total=eligible.reduce((sum,item)=>sum+newCountFor(item),0);
  return`<section class="atomic-section comic-home-updates"><div class="atomic-section__head"><div><span class="eyebrow">FAVORITES + ACTIVE READING ONLY</span><h2>${total} NEW COMICS / MANGA ${total===1?"RELEASE":"RELEASES"}</h2></div><button data-route="manga">OPEN RELEASE WATCH</button></div><div class="comic-home-grid">${eligible.map(item=>`<button data-route="manga/${encodeURIComponent(item.id)}">${cover(item,"comic-home-cover")}<span><b>${esc(item.title)}</b><small>${newCountFor(item)} NEW ${unitLabel(metaFor(item))}</small><em>VAULT RECORD →</em></span></button>`).join("")}</div></section>`;
}

async function searchOnline(query){const response=await fetch("./__vault/comics/search",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-search"},body:JSON.stringify({query})});if(!response.ok)throw new Error(response.status===503?"AI search is unavailable. You can still add this series manually.":`Search returned ${response.status}.`);return response.json()}
const normalizedComicTitle=value=>String(value||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const COMIC_METADATA_REFRESH_MS=7*24*60*60*1000;
const comicMetadataSignature=item=>JSON.stringify([normalizedComicTitle(item.title),normalizedComicTitle(item.creator),normalizedComicTitle(item.publisher),String(item.year||""),String(metaFor(item).format||""),String(metaFor(item).sourceLedger?.externalId||"")]);
export async function correctAllComicMetadata({onProgress=()=>{},force=false,control=null}={}){
  const all=allComics(),ledger=getState().metadata.comicsManga?.metadataRefresh?.items||{},now=Date.now(),records=all.filter(item=>{if(metaFor(item).metadataAuthority?.manualFields?.length)return false;const prior=ledger[item.id];return force||!prior||prior.status!=="updated"||prior.signature!==comicMetadataSignature(item)||now-Date.parse(prior.checkedAt||0)>=COMIC_METADATA_REFRESH_MS}),results=[];
  for(let index=0;index<records.length;index++){
    await (control||globalThis.__vaultActiveJobControl)?.checkpoint?.();
    const item=getState().items[records[index].id];if(!item?.comicMeta)continue;
    let status="failed",reason="No confident exact match";
    try{
      const query=[item.title,item.creator,item.publisher,item.year].filter(Boolean).join(" "),payload=await searchOnline(query),candidates=payload.candidates||[],wanted=normalizedComicTitle(item.title),exact=candidates.find(candidate=>normalizedComicTitle(candidate.title)===wanted||(candidate.alternateTitles||[]).some(title=>normalizedComicTitle(title)===wanted)),candidate=exact;
      if(candidate){
        update(save=>{const target=save.items[item.id],meta=target?.comicMeta;if(!target||!meta)return;const correctedAt=new Date().toISOString();target.title=String(candidate.title||target.title).trim();target.creator=String(candidate.creator||target.creator||"").trim();target.publisher=String(candidate.publisher||target.publisher||"").trim();target.year=Number(candidate.startYear||target.year||0)||null;if((candidate.genres||[]).length)target.genres=[...new Set([(candidate.format||meta.format)==="manga"?"Manga":"Comics",...candidate.genres])].slice(0,8);target.description=String(candidate.description||target.description||"").trim();meta.format=COMIC_FORMATS.has?.(candidate.format)?candidate.format:(candidate.format||meta.format);if(PUBLICATION.has(candidate.publicationStatus))meta.publicationStatus=candidate.publicationStatus;if(candidate.unitType)meta.progressUnit=candidate.unitType;if(candidate.releaseLane&&LANES.has(candidate.releaseLane))meta.releaseLane=candidate.releaseLane;if(Number(candidate.totalUnits)>0)meta.latestKnown=Math.max(Number(meta.readThrough||0),Number(candidate.totalUnits));meta.alternateTitles=(candidate.alternateTitles||[]).slice(0,6);meta.metadataCorrectedAt=correctedAt;meta.metadataConfidence=exact?"exact_title":"best_available";meta.sourceLedger||={};if(candidate.sourceUrl)meta.sourceLedger.primary={name:candidate.sourceName||"Verified catalog source",url:safeUrl(candidate.sourceUrl),checkedAt:correctedAt};if(candidate.officialUrl)meta.sourceLedger.officialUrl=safeUrl(candidate.officialUrl);if(candidate.externalId)meta.sourceLedger.externalId=String(candidate.externalId)});
        status="updated";reason=exact?"Exact title verified":"Best catalog match applied";
      }else if(candidates.length){update(save=>{save.metadata.comicsManga||={};const queue=save.metadata.comicsManga.metadataReview||=[];const prior=queue.find(entry=>entry.itemId===item.id&&entry.status==="pending"),record={itemId:item.id,title:item.title,status:"pending",candidates:candidates.slice(0,5).map(candidate=>({...candidate,coverImageUrl:"",remoteCoverImageUrl:""})),createdAt:new Date().toISOString()};if(prior)Object.assign(prior,record);else queue.push(record);save.metadata.comicsManga.metadataReview=queue});status="review";reason="Choose the exact series match"}
    }catch(error){reason=error.message||reason}
    results.push({itemId:item.id,title:item.title,status,reason});update(save=>{save.metadata.comicsManga||={};save.metadata.comicsManga.metadataRefresh||={items:{}};save.metadata.comicsManga.metadataRefresh.items||={};const current=save.items[item.id];save.metadata.comicsManga.metadataRefresh.items[item.id]={signature:comicMetadataSignature(current||item),checkedAt:new Date().toISOString(),status,message:reason}});onProgress({processed:index+1,total:records.length,libraryTotal:all.length,skipped:all.length-records.length,updated:results.filter(entry=>entry.status==="updated").length,failed:results.filter(entry=>entry.status!=="updated").length,title:item.title});
  }
  const completedAt=new Date().toISOString(),skipped=all.length-records.length;update(save=>{save.metadata.comicsManga||={};save.metadata.comicsManga.metadataRepair={completedAt,total:records.length,libraryTotal:all.length,skipped,updated:results.filter(entry=>entry.status==="updated").length,failed:results.filter(entry=>entry.status!=="updated").length,results};save.metadata.comicsManga.metadataRefresh||={items:{}};save.metadata.comicsManga.metadataRefresh.completedAt=completedAt});
  return{total:records.length,libraryTotal:all.length,skipped,updated:results.filter(entry=>entry.status==="updated").length,failed:results.filter(entry=>entry.status!=="updated").length,results,completedAt};
}

export function pendingComicMetadataReviews(){return(getState().metadata?.comicsManga?.metadataReview||[]).filter(entry=>entry.status==="pending")}
export function openComicMetadataReview(onChanged=()=>{}){
  const entry=pendingComicMetadataReviews()[0];if(!entry){toast("METADATA REVIEW CLEAR","No uncertain series matches are waiting.");return false}
  openModal({title:`VERIFY SERIES — ${entry.title}`,body:`<div class="comic-metadata-review"><p>The title was not exact enough for automatic correction. Choose the matching series or keep the current metadata.</p>${entry.candidates.map((candidate,index)=>`<article><button data-comic-metadata-choice="${index}"><b>${esc(candidate.title)}</b><small>${esc(candidate.creator||"CREATOR UNKNOWN")} · ${candidate.startYear||"YEAR UNKNOWN"} · ${esc(String(candidate.format||"unknown").replaceAll("_"," ").toUpperCase())}</small><em>${esc(candidate.publisher||candidate.sourceName||"PUBLISHER UNKNOWN")}</em><p>${esc(candidate.description||candidate.matchReason||"No summary available.")}</p></button>${safeUrl(candidate.sourceUrl)?`<a href="${esc(safeUrl(candidate.sourceUrl))}" target="_blank" rel="noreferrer">VERIFY SOURCE ↗</a>`:""}</article>`).join("")}</div>`,actions:[{label:"KEEP CURRENT / SKIP",handler:()=>{update(save=>{const target=save.metadata.comicsManga.metadataReview.find(record=>record.itemId===entry.itemId&&record.status==="pending");if(target){target.status="skipped";target.resolvedAt=new Date().toISOString()}});closeModal();onChanged();openComicMetadataReview(onChanged)}}]});
  const root=document.querySelector("#modal-root .modal__body");root.onclick=event=>{const button=event.target.closest("[data-comic-metadata-choice]");if(!button)return;const candidate=entry.candidates[Number(button.dataset.comicMetadataChoice)];if(!candidate)return;update(save=>{const item=save.items[entry.itemId],meta=item?.comicMeta;if(!item||!meta)return;const correctedAt=new Date().toISOString();item.title=String(candidate.title||item.title).trim();item.creator=String(candidate.creator||item.creator||"").trim();item.publisher=String(candidate.publisher||item.publisher||"").trim();item.year=Number(candidate.startYear||item.year||0)||null;if((candidate.genres||[]).length)item.genres=[...new Set([candidate.format==="manga"?"Manga":"Comics",...candidate.genres])].slice(0,8);item.description=String(candidate.description||item.description||"").trim();if(COMIC_FORMATS.has(candidate.format))meta.format=candidate.format;if(PUBLICATION.has(candidate.publicationStatus))meta.publicationStatus=candidate.publicationStatus;if(candidate.unitType)meta.progressUnit=candidate.unitType;if(candidate.releaseLane&&LANES.has(candidate.releaseLane))meta.releaseLane=candidate.releaseLane;if(Number(candidate.totalUnits)>0)meta.latestKnown=Math.max(Number(meta.readThrough||0),Number(candidate.totalUnits));meta.alternateTitles=(candidate.alternateTitles||[]).slice(0,6);meta.metadataCorrectedAt=correctedAt;meta.metadataConfidence="user_approved";meta.sourceLedger||={};if(candidate.sourceUrl)meta.sourceLedger.primary={name:candidate.sourceName||"Verified source",url:safeUrl(candidate.sourceUrl),checkedAt:correctedAt};if(candidate.officialUrl)meta.sourceLedger.officialUrl=safeUrl(candidate.officialUrl);const review=save.metadata.comicsManga.metadataReview.find(record=>record.itemId===entry.itemId&&record.status==="pending");if(review){review.status="approved";review.resolvedAt=correctedAt}});closeModal();onChanged();toast("METADATA MATCH APPROVED",candidate.title);openComicMetadataReview(onChanged)};return true
}
function candidateCover(candidate,className="comic-search-cover"){const image=artworkUrl(candidate.coverImageUrl);return`<i class="${className}" style="--comic-h:${hue(candidate.title)}">${image?`<img src="${esc(image)}" alt="Published cover for ${esc(candidate.title)}">`:`<b>${esc(initials(candidate.title))}</b>`}</i>`}
function resultCard(candidate,index){const genres=(candidate.genres||[]).slice(0,3).join(" · ");return`<button class="comic-search-result" data-comic-candidate="${index}">${candidateCover(candidate)}<span><b>${esc(candidate.title)}</b><small>${esc(String(candidate.format||"manga").replaceAll("_"," ").toUpperCase())} · ${candidate.startYear||"YEAR UNKNOWN"} · ${esc(publicationLabel(candidate.publicationStatus||"unknown"))}</small><em>${esc(candidate.creator||candidate.publisher||"CREATOR UNKNOWN")}</em>${genres?`<small>${esc(genres)}</small>`:""}<p>${esc(candidate.matchReason||candidate.description||"Possible series match")}</p></span><strong>${artworkUrl(candidate.coverImageUrl)?"COVER FOUND":"ART NEEDED"}<br>REVIEW →</strong></button>`}

export function openComicAddDialog(onAdded=()=>{}){
  const state=getState();openModal({title:"ADD COMICS / MANGA SERIES",body:`<div class="comic-add-dialog"><p>Search by title, alternate title, creator, publisher, or year. Suggestions begin after three characters; you confirm the exact record before it enters the Vault.</p><div class="comic-search-box"><input type="search" data-comic-search-query autocomplete="off" placeholder="START TYPING A SERIES TITLE"><button class="button primary" data-comic-search>SEARCH</button></div><div class="comic-search-status" data-comic-search-status>READY FOR A TITLE</div><div class="comic-search-results" data-comic-search-results></div><button class="button" data-comic-manual>ADD MANUALLY</button></div>`});
  const root=document.querySelector("#modal-root"),input=root.querySelector("[data-comic-search-query]"),results=root.querySelector("[data-comic-search-results]"),status=root.querySelector("[data-comic-search-status]");let candidates=[];
  const run=async()=>{const query=input.value.trim();if(query.length<3){status.textContent="TYPE AT LEAST THREE CHARACTERS";return}const local=allComics(state).filter(item=>item.title.toLowerCase().includes(query.toLowerCase())).slice(0,4);status.textContent="AI IS CHECKING TITLES, RUNS, CREATORS, AND RELEASE SOURCES…";results.innerHTML=local.map(item=>`<button class="comic-local-match" data-comic-existing="${esc(item.id)}"><b>${esc(item.title)}</b><span>ALREADY IN YOUR VAULT</span><strong>OPEN →</strong></button>`).join("");try{const response=await searchOnline(query);candidates=response.candidates||[];results.insertAdjacentHTML("beforeend",candidates.map(resultCard).join("")||`<div class="empty"><b>NO ONLINE MATCHES.</b>Try another title or add it manually.</div>`);status.textContent=`${candidates.length} ONLINE MATCH${candidates.length===1?"":"ES"} · CONFIRM BEFORE ADDING`}catch(error){status.textContent=error.message}};
  root.querySelector("[data-comic-search]").onclick=run;input.oninput=()=>{clearTimeout(searchTimer);if(input.value.trim().length>=3)searchTimer=setTimeout(run,700)};root.querySelector("[data-comic-manual]").onclick=()=>openManualComicDialog(onAdded);
  results.onclick=async event=>{const existing=event.target.closest("[data-comic-existing]")?.dataset.comicExisting;if(existing){closeModal();location.hash=`#/manga/${encodeURIComponent(existing)}`;return}const index=event.target.closest("[data-comic-candidate]")?.dataset.comicCandidate;if(index!=null&&candidates[index]){status.textContent="PREPARING METADATA AND A RECOGNIZABLE PUBLISHED COVER…";const prepared=await prepareCandidateForReview(candidates[index]);openCandidateConfirmDialog(prepared,onAdded)}};
}

async function prepareCandidateForReview(candidate){
  if(artworkUrl(candidate.coverImageUrl))return candidate;
  try{
    const probe={id:createId("comic_preview"),title:candidate.title,creator:candidate.creator||"",type:candidate.format||"manga",comicMeta:{format:candidate.format||"manga"}},payload=await discoverComicArtwork([probe]),result=(payload.results||[]).find(entry=>entry.itemId===probe.id&&entry.confidence!=="low");
    if(result?.imageUrl)return{...candidate,coverImageUrl:result.imageUrl,coverSourceUrl:result.pageUrl,coverSourceName:result.sourceName};
  }catch{}
  return candidate;
}

function candidateForm(candidate,manual=false){
  const format=FORMATS.has(candidate.format)?candidate.format:"manga",defaultUnit=format==="manga"?"chapters":format==="graphic_novel"?"simple":"issues",defaultLane=format==="manga"?"official_english_chapters":format==="graphic_novel"?"collected_editions":"comic_issues";
  const genres=(candidate.genres||[]).join(" · "),coverSource=safeUrl(candidate.coverSourceUrl),hasCover=Boolean(artworkUrl(candidate.coverImageUrl));
  return`<div class="comic-confirm-form">${manual?`<label>TITLE<input data-confirm-title value="${esc(candidate.title||"")}" required></label><label>CREATOR<input data-confirm-creator value="${esc(candidate.creator||"")}"></label>`:`<div class="comic-match-summary">${candidateCover(candidate,"comic-confirm-cover")}<div><span class="eyebrow">SEARCH MATCH // YOUR CONFIRMATION REQUIRED</span><h3>${esc(candidate.title)}</h3><p>${esc(candidate.creator||"Creator unknown")}${candidate.publisher?` · ${esc(candidate.publisher)}`:""}${candidate.startYear?` · ${candidate.startYear}`:""}</p>${genres?`<small>${esc(genres)}</small>`:""}<small>${esc(candidate.description||candidate.matchReason||"Review this record before adding it.")}</small><em>${hasCover?`PUBLISHED COVER · ${esc(candidate.coverSourceName||"VERIFIED SOURCE")}`:"NO CONFIDENT PUBLISHED COVER FOUND — TRY ANOTHER MATCH"}</em>${coverSource?`<a href="${esc(coverSource)}" target="_blank" rel="noreferrer">VIEW ARTWORK SOURCE</a>`:""}</div></div>`}<div class="comic-field-grid"><label>FORMAT<select data-confirm-format>${[["manga","MANGA"],["comic","COMIC"],["graphic_novel","GRAPHIC NOVEL"],["webcomic","WEBCOMIC"]].map(([value,label])=>`<option value="${value}" ${format===value?"selected":""}>${label}</option>`).join("")}</select></label><label>YOUR STATUS<select data-confirm-status>${["planned","reading","cooking","paused","completed","dropped"].map(value=>`<option value="${value}">${statusLabel(value)}</option>`).join("")}</select></label><label>PROGRESS UNIT<select data-confirm-unit>${["chapters","issues","volumes","editions","simple"].map(value=>`<option value="${value}" ${defaultUnit===value?"selected":""}>${value.toUpperCase()}</option>`).join("")}</select></label><label>READ THROUGH<input type="number" min="0" step="0.1" value="0" data-confirm-read></label><label>LATEST KNOWN<input type="number" min="0" step="0.1" value="${Number(candidate.totalUnits||0)}" data-confirm-latest></label><label>PUBLICATION<select data-confirm-publication>${["ongoing","hiatus","complete","cancelled","unknown"].map(value=>`<option value="${value}" ${(candidate.publicationStatus||"unknown")===value?"selected":""}>${publicationLabel(value)}</option>`).join("")}</select></label><label>RELEASE LANE<select data-confirm-lane>${[...LANES].map(value=>`<option value="${value}" ${defaultLane===value?"selected":""}>${laneLabel(value)}</option>`).join("")}</select></label></div>${!manual?`<label class="comic-check-label"><input type="checkbox" data-confirm-cover ${hasCover?"checked":""} ${hasCover?"":"disabled"}> ${hasCover?"USE THIS PUBLISHED COVER":"PUBLISHED COVER REQUIRED BEFORE SAVING"}</label>`:""}<label class="comic-check-label"><input type="checkbox" data-confirm-monitor checked> MONITOR FOR NEW RELEASES</label><label class="comic-check-label"><input type="checkbox" data-confirm-favorite> FAVORITE</label></div>`;
}
function openCandidateConfirmDialog(candidate,onAdded){openModal({title:"CONFIRM SERIES MATCH",body:candidateForm(candidate),actions:[{label:"ADD TO VAULT",primary:true,handler:async dialog=>{const useCover=Boolean(dialog.querySelector("[data-confirm-cover]")?.checked);if(!useCover)return toast("PUBLISHED COVER REQUIRED","Choose a result with recognizable artwork before saving.");const id=addConfirmedComic(candidate,dialog);closeModal();toast("SERIES ADDED","Saving the selected published cover…");await attachComicArtwork(id,{...candidate,allowGenerated:false});onAdded(id)}}]})}
function openManualComicDialog(onAdded){const candidate={title:"",creator:"",format:"manga",publicationStatus:"unknown",sourceName:"Manual record",sourceUrl:"",officialUrl:""};openModal({title:"ADD SERIES MANUALLY",body:candidateForm(candidate,true),actions:[{label:"FIND DETAILS + COVER",primary:true,handler:async dialog=>{const title=dialog.querySelector("[data-confirm-title]").value.trim();if(!title){toast("TITLE REQUIRED","Enter a series title before searching.");return}candidate.title=title;candidate.creator=dialog.querySelector("[data-confirm-creator]").value.trim();toast("SEARCHING SERIES","Finding a recognizable published cover before saving…");const prepared=await prepareCandidateForReview(candidate);if(!artworkUrl(prepared.coverImageUrl))return toast("NO PUBLISHED COVER FOUND","Try the normal title search or a more specific title.");closeModal();openCandidateConfirmDialog(prepared,onAdded)}}]})}
function addConfirmedComic(candidate,dialog){
  const format=dialog.querySelector("[data-confirm-format]").value,readingStatus=dialog.querySelector("[data-confirm-status]").value,progressUnit=dialog.querySelector("[data-confirm-unit]").value,readThrough=Math.max(0,Number(dialog.querySelector("[data-confirm-read]").value)||0),latestKnown=Math.max(readThrough,Number(dialog.querySelector("[data-confirm-latest]").value)||0),publicationStatus=dialog.querySelector("[data-confirm-publication]").value,releaseLane=dialog.querySelector("[data-confirm-lane]").value,monitoring=dialog.querySelector("[data-confirm-monitor]").checked,favorite=dialog.querySelector("[data-confirm-favorite]").checked,id=createId(format==="manga"?"manga":"comic"),addedAt=new Date().toISOString();
  update(save=>{save.items[id]={id,type:format==="manga"?"manga":"comic",wing:"manga",title:String(candidate.title).trim(),creator:String(candidate.creator||"").trim(),publisher:String(candidate.publisher||"").trim(),year:Number(candidate.startYear||0)||null,genres:[...new Set([format==="manga"?"Manga":"Comics",...(candidate.genres||[])])].slice(0,8),description:String(candidate.description||"").trim(),status:itemStatus(readingStatus),owned:false,favorite,addedAt,comicMeta:{format,readingStatus,publicationStatus,progressUnit,readThrough,latestKnown,releaseLane,monitoring,hidden:false,releases:[],sourceLedger:{primary:candidate.sourceUrl?{name:candidate.sourceName||"Online match",url:safeUrl(candidate.sourceUrl),checkedAt:addedAt}:null,officialUrl:safeUrl(candidate.officialUrl),externalId:String(candidate.externalId||"")},readingAccess:{kindleOwned:false,kindleUrl:"",webUrl:safeUrl(candidate.officialUrl||candidate.sourceUrl),preferred:"auto"},addedBy:candidate.sourceUrl?"ai_confirmed_search":"manual",importedAt:addedAt}}});
  ensureComicsMangaV2();emit("COMIC_SERIES_ADDED",{itemId:id,wing:"manga",meta:{title:candidate.title,format}});return id;
}

export async function attachComicArtwork(itemId,source={}){
  const item=getState().items[itemId];if(!item?.comicMeta)return{saved:false,error:"missing_record"};
  const localCandidate=artworkUrl(source.coverImageUrl||source.imageUrl);
  if(localCandidate.startsWith("./assets/artwork/")&&source.requireApproval){const approvalId=queueArtworkApproval({kind:"comic",itemId,target:"main",key:`comic:${itemId}:main`,title:item.title,subtitle:"Published cover candidate",path:localCandidate,sourceName:source.coverSourceName||source.sourceName||"Published cover",sourceUrl:safeUrl(source.coverSourceUrl||source.sourceUrl)});return{saved:Boolean(approvalId),queued:Boolean(approvalId),path:localCandidate,kind:"published"}}
  if(localCandidate.startsWith("./assets/artwork/")){const savedAt=new Date().toISOString();update(save=>{const record=save.items[itemId];if(!record?.comicMeta)return;record.artwork=localCandidate;record.comicMeta.artworkCredit=source.coverSourceName||source.sourceName||"Published cover";record.comicMeta.artworkKind="published";record.comicMeta.artworkPolicyVersion=3;record.comicMeta.artworkAddedAt=savedAt});return{saved:true,path:localCandidate,kind:"published"}}
  let imageUrl=safeUrl(source.coverImageUrl||source.imageUrl),pageUrl=safeUrl(source.coverSourceUrl||source.pageUrl||source.officialUrl||source.sourceUrl||item.comicMeta.sourceLedger?.officialUrl||item.comicMeta.sourceLedger?.primary?.url),artSource=source;
  const saveResult=(payload,credit,kind,url="")=>{if(source.requireApproval){const approvalId=queueArtworkApproval({kind:"comic",itemId,target:"main",key:`comic:${itemId}:main`,title:item.title,subtitle:"Published cover candidate",path:payload.path,sourceName:credit,sourceUrl:safeUrl(url)});return{saved:Boolean(approvalId),queued:Boolean(approvalId),path:payload.path,kind}}const savedAt=new Date().toISOString();update(save=>{const record=save.items[itemId];if(!record?.comicMeta)return;record.artwork=payload.path;record.comicMeta.artworkCredit=credit;record.comicMeta.artworkKind=kind;record.comicMeta.artworkPolicyVersion=3;record.comicMeta.artworkAddedAt=savedAt;record.comicMeta.sourceLedger||={};record.comicMeta.sourceLedger.artwork={name:credit,url:safeUrl(url),imageUrl:safeUrl(payload.sourceUrl),checkedAt:savedAt,kind}});emit("COMIC_ARTWORK_ADDED",{itemId,wing:"manga",meta:{title:item.title,source:credit,kind}});return{saved:true,path:payload.path,kind}};
  const tryPublished=async()=>{if(!imageUrl&&!pageUrl)return null;
    try{
      const response=await fetch("./__vault/comics/artwork/download",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-artwork-download"},body:JSON.stringify({itemId,imageUrl,pageUrl})});
      if(response.ok){const payload=await response.json(),credit=String(artSource.coverSourceName||artSource.sourceName||"Published cover source");return saveResult(payload,credit,"published",artSource.coverSourceUrl||artSource.pageUrl||artSource.officialUrl||artSource.sourceUrl||payload.sourceUrl)}
    }catch{}return null;
  };
  const direct=await tryPublished();if(direct)return direct;
  if(!source.discoveryComplete){try{const payload=await discoverComicArtwork([item]),result=(payload.results||[]).find(entry=>entry.itemId===itemId&&entry.confidence!=="low");if(result){artSource={...result,coverImageUrl:result.imageUrl,coverSourceUrl:result.pageUrl,coverSourceName:result.sourceName,discoveryComplete:true};imageUrl=safeUrl(result.imageUrl);pageUrl=safeUrl(result.pageUrl);const discovered=await tryPublished();if(discovered)return discovered}}catch{}
  }
  if(source.allowGenerated!==true)return{saved:false,error:"no_familiar_cover"};
  try{
    const response=await fetch("./__vault/comics/artwork/generate",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-artwork-generate"},body:JSON.stringify({itemId,title:item.title,creator:item.creator||"",format:metaFor(item).format||item.type||"manga"})});
    if(!response.ok)return{saved:false,error:"artwork_generation_unavailable"};
    const payload=await response.json(),credit=String(payload.credit||"Vault-generated archive cover");return saveResult(payload,credit,payload.kind||"vault_generated");
  }catch{return{saved:false,error:"artwork_service_unavailable"}}
}

export async function replaceComicArtwork(itemId){
  const item=getState().items[itemId];if(!item?.comicMeta)return{saved:false,error:"missing_record"};
  return attachComicArtwork(itemId,{allowGenerated:false,requireApproval:true});
}

export async function replaceLegacyGeneratedComicArtwork(){
  const generated=item=>{const meta=metaFor(item),kind=String(meta.artworkKind||meta.sourceLedger?.artwork?.kind||"").toLowerCase(),credit=String(meta.artworkCredit||meta.sourceLedger?.artwork?.name||"").toLowerCase();return["ai_generated","vault_generated"].includes(kind)||/\b(ai|vault)[ -]?generated\b/.test(credit)};
  const targets=allComics().filter(item=>generated(item)&&!metaFor(item).artworkOverride);let saved=0,failed=0;
  for(const item of targets){const result=await replaceComicArtwork(item.id);if(result.saved)saved++;else{failed++;update(save=>{if(save.items[item.id]?.comicMeta)save.items[item.id].comicMeta.legacyReplacementLastAttempt=new Date().toISOString()})}}
  return{total:targets.length,saved,failed};
}

async function discoverComicArtwork(series){
  const response=await fetch("./__vault/comics/artwork/discover",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-artwork-discover"},body:JSON.stringify({series:series.map(item=>({itemId:item.id,title:item.title,creator:item.creator||"",format:metaFor(item).format||item.type||"manga"}))})});
  if(!response.ok)throw new Error(response.status===429?"AI artwork search is busy. Try again in a moment.":"AI artwork discovery is unavailable.");return response.json();
}

export function autoFillComicArtwork({onProgress=()=>{},control=null}={}){
  if(artworkBackfillPromise)return artworkBackfillPromise;
  artworkBackfillPromise=(async()=>{
    const missing=allComics().filter(item=>!artFor(item)),total=missing.length;let processed=0,saved=0,failed=0;
    for(let index=0;index<missing.length;index+=8){
      await (control||globalThis.__vaultActiveJobControl)?.checkpoint?.();
      const batch=missing.slice(index,index+8);let payload={results:[]};try{payload=await discoverComicArtwork(batch)}catch{}
      const byId=new Map((payload.results||[]).map(result=>[result.itemId,result]));
      for(const item of batch){const result=byId.get(item.id),source=result&&result.confidence!=="low"?{...result,coverImageUrl:result.imageUrl,coverSourceUrl:result.pageUrl,coverSourceName:result.sourceName,requireApproval:true}:{requireApproval:true};const outcome=await attachComicArtwork(item.id,source);outcome.saved?saved++:failed++;processed++;onProgress({processed,total,saved,failed})}
    }
    return{processed,total,saved,failed,remaining:allComics().filter(item=>!artFor(item)).length};
  })().finally(()=>{artworkBackfillPromise=null});
  return artworkBackfillPromise;
}

export async function checkComicReleases({force=false}={}){
  if(releaseCheckPromise)return releaseCheckPromise;
  const state=getState(),stage=state.metadata.comicsManga||{},last=Date.parse(stage.lastCheckedAt||0);
  if(!force&&last&&Date.now()-last<6*60*60*1000)return{skipped:true,changed:[]};
  const monitored=allComics(state).filter(item=>comicMonitoringEligible(item)&&!metaFor(item).hidden).slice(0,24);
  if(!monitored.length)return{skipped:true,changed:[]};
  releaseCheckPromise=(async()=>{
    try{
      const response=await fetch("./__vault/comics/releases",{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":"comics-releases"},body:JSON.stringify({series:monitored.map(item=>({itemId:item.id,title:item.title,creator:item.creator||"",releaseLane:metaFor(item).releaseLane,latestKnown:Number(metaFor(item).latestKnown||0)}))})});
      if(!response.ok)throw new Error(`Release service returned ${response.status}.`);
      const payload=await response.json(),checkedAt=payload.checkedAt||new Date().toISOString(),changed=[];
      update(save=>{
        for(const result of payload.results||[]){const item=save.items[result.itemId],meta=item?.comicMeta;if(!meta)continue;const latest=Math.max(Number(meta.latestKnown||0),Number(result.latestNumber||0));if(latest>Number(meta.latestKnown||0)){meta.latestKnown=latest;changed.push({itemId:item.id,title:item.title,latest})}if(PUBLICATION.has(result.publicationStatus))meta.publicationStatus=result.publicationStatus;meta.lastCheckedAt=checkedAt;meta.lastReleaseLabel=String(result.latestLabel||"");if(result.sourceUrl)meta.sourceLedger.primary={name:String(result.sourceName||"Verified online source"),url:safeUrl(result.sourceUrl),checkedAt};if(result.officialUrl)meta.sourceLedger.officialUrl=safeUrl(result.officialUrl)}
        save.metadata.comicsManga.lastCheckedAt=checkedAt;save.metadata.comicsManga.lastCheckStatus="complete";
      });
      changed.forEach(entry=>emit("COMIC_RELEASE_FOUND",{itemId:entry.itemId,wing:"manga",meta:{title:entry.title,latest:entry.latest}}));return{checked:monitored.length,changed};
    }catch(error){update(save=>{save.metadata.comicsManga.lastCheckStatus="unavailable"});throw error}finally{releaseCheckPromise=null}
  })();return releaseCheckPromise;
}
