import { createId } from "../core/ids.js";
import { flushPersistence, getState, update } from "../core/store.js";
import { renderAtomicWingShell } from "../ui/atomicWingShell.js";
import { closeModal, openModal } from "../ui/modals.js";
import { toast } from "../ui/notifications.js";

const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const shows=(state=getState())=>Object.values(state.items||{}).filter(item=>item.wing==="podcasts"&&item.podcastMeta?.kind==="show"&&Number(item.podcastMeta?.spotifyHistoryListeningSeconds||60)>=60);
const post=async(path,name,body={})=>{const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-Vault-Request":name},body:JSON.stringify(body)}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Spotify podcast connection unavailable.");return payload};
export function ensurePodcastStyles(){if(document.querySelector("link[data-podcast-styles]"))return;const link=document.createElement("link");link.rel="stylesheet";link.href="./css/podcasts.css?v=20260905-v2";link.dataset.podcastStyles="";document.head.append(link)}
export function ensurePodcasts(){update(save=>{save.metadata.podcasts||={version:1,preferences:{scope:"tracked",sort:"newest"}}})}
export async function chooseSpotifyPodcasts(onChanged=()=>{}){let payload;try{payload=await post("./__vault/spotify/podcasts/shows","spotify-podcast-shows")}catch(error){toast("SPOTIFY PODCASTS NEED RECONNECTING","Reconnect Spotify once so The Vault can read saved shows and playback positions.",8000);throw error}const records=payload.shows||[];openModal({title:"CHOOSE SPOTIFY PODCASTS",body:`<div class="youtube-picker"><p>Only checked shows enter the Vault. The rest of your Spotify library stays out.</p><div class="youtube-picker-list">${records.map((show,index)=>`<label><input type="checkbox" data-podcast-choice value="${index}"><span><b>${esc(show.title)}</b><small>${esc(show.publisher||"")}</small></span></label>`).join("")||"<p>NO SAVED SPOTIFY SHOWS FOUND.</p>"}</div></div>`,actions:[{label:"ADD SELECTED",primary:true,handler:dialog=>{const selected=[...dialog.querySelectorAll("[data-podcast-choice]:checked")].map(box=>records[Number(box.value)]);update(save=>{for(const show of selected){let item=Object.values(save.items||{}).find(value=>value.wing==="podcasts"&&value.podcastMeta?.spotifyId===show.spotifyId);if(!item){const id=createId("podcast");item=save.items[id]={id,wing:"podcasts",type:"podcast",title:show.title,creator:show.publisher||"",artwork:show.artworkUrl||"",status:"in_progress",favorite:false,addedAt:new Date().toISOString(),podcastMeta:{kind:"show",spotifyId:show.spotifyId,externalUrl:show.externalUrl||"",trackingState:"tracked",trackingStartedAt:new Date().toISOString(),episodes:[],totalListeningSeconds:0}}}}});closeModal();onChanged();toast("PODCASTS ADDED",`${selected.length} shows are now tracked.`)}}]});return true}
export async function refreshPodcasts(onChanged=()=>{}){const tracked=shows().filter(item=>item.podcastMeta.trackingState==="tracked");if(!tracked.length)return{checked:0,newCount:0};const payload=await post("./__vault/spotify/podcasts/refresh","spotify-podcast-refresh",{shows:tracked.map(item=>({itemId:item.id,spotifyId:item.podcastMeta.spotifyId,baselineAt:item.podcastMeta.trackingStartedAt}))});let newCount=0;update(save=>{for(const result of payload.shows||[]){const item=save.items[result.itemId];if(!item?.podcastMeta)continue;const prior=new Map((item.podcastMeta.episodes||[]).map(ep=>[ep.spotifyId,ep]));item.podcastMeta.episodes=(result.episodes||[]).map(ep=>{const old=prior.get(ep.spotifyId),isNew=!old&&Date.parse(ep.releaseDate)>=Date.parse(item.podcastMeta.trackingStartedAt);if(isNew)newCount++;return{...ep,status:ep.fullyPlayed?"watched":old?.status||"new",firstSeenAt:old?.firstSeenAt||new Date().toISOString()}});item.podcastMeta.lastCheckedAt=payload.checkedAt;item.podcastMeta.totalListeningSeconds=item.podcastMeta.episodes.reduce((sum,ep)=>sum+Math.max(0,Number(ep.resumePositionMs||0))/1000,0)}});onChanged();return{checked:tracked.length,newCount}}
export function markPodcastEpisode(showId,episodeId){update(save=>{const episode=save.items[showId]?.podcastMeta?.episodes?.find(value=>value.spotifyId===episodeId);if(episode){episode.status=episode.status==="watched"?"new":"watched";episode.fullyPlayed=episode.status==="watched"}})}
export function openPodcastEpisode(showId,episodeId){const episode=getState().items[showId]?.podcastMeta?.episodes?.find(value=>value.spotifyId===episodeId);if(!episode?.externalUrl)return false;window.open(episode.externalUrl,"_blank","noopener,noreferrer");return true}
const card=item=>{const meta=item.podcastMeta,fresh=(meta.episodes||[]).filter(ep=>ep.status==="new").length;return`<article class="comic-card podcast-card"><button class="comic-card__open" data-podcast-open="${esc(item.id)}"><i class="comic-cover">${item.artwork?`<img src="${esc(item.artwork)}" alt="">`:"◉"}</i><span class="comic-card__copy"><b>${esc(item.title)}</b><small>${esc(item.creator||"PUBLISHER UNKNOWN")}</small><em>${fresh} NEW · ${meta.episodes?.length||0} RECENT EPISODES</em></span>${fresh?`<strong class="comic-new-count">${fresh} NEW</strong>`:""}</button><div class="comic-card-controls"><button data-vault-remove="${esc(item.id)}">×</button></div></article>`};
export function renderPodcastsWing(activeId=""){const all=shows(),active=all.find(item=>item.id===activeId),episodes=(active?.podcastMeta?.episodes||[]).slice().sort((a,b)=>Date.parse(b.releaseDate)-Date.parse(a.releaseDate));return`<div class="podcast-wing"><section class="podcast-command panel"><div><span class="eyebrow">SPOTIFY + CASTBOX + MANUAL SESSIONS</span><h2>PODCAST ARCHIVE</h2><p>Only shows you deliberately add are tracked. Spotify supplies saved-show choices, recent episodes, artwork, and playback positions.</p></div><aside><button class="button primary" data-podcast-choose>CHOOSE SPOTIFY SHOWS</button><button class="button" data-podcast-refresh>REFRESH PODCASTS</button></aside></section>${active?`<section class="podcast-episodes panel"><button class="button" data-podcast-back>← ALL PODCASTS</button><h2>${esc(active.title)}</h2><div>${episodes.map(ep=>`<article><img src="${esc(ep.artworkUrl||active.artwork||"")}" alt=""><span><b>${esc(ep.title)}</b><small>${esc(ep.releaseDate||"")} · ${Math.round(Number(ep.durationMs||0)/60000)} MIN</small><em>${ep.fullyPlayed||ep.status==="watched"?"WATCHED":ep.resumePositionMs?`${Math.round(ep.resumePositionMs/60000)} MIN IN`:"NEW"}</em></span><button data-podcast-play="${esc(ep.spotifyId)}" data-podcast-id="${esc(active.id)}">OPEN SPOTIFY</button><button data-podcast-watch="${esc(ep.spotifyId)}" data-podcast-id="${esc(active.id)}">${ep.status==="watched"?"MARK NEW":"MARK WATCHED"}</button></article>`).join("")||"<p>REFRESH TO LOAD THE LAST MONTH.</p>"}</div></section>`:`<section class="music-library panel"><header><h2>TRACKED PODCASTS</h2><span>${all.length} SHOWS</span></header><div class="music-artist-grid">${all.map(card).join("")||"<div class='empty'><b>YOUR PODCAST LIBRARY IS EMPTY.</b><p>Choose specific Spotify shows to begin.</p></div>"}</div></section>`}</div>`}
export function renderPodcastsShell(content,screen="catalog"){return renderAtomicWingShell({active:"podcasts",title:"PODCAST ARCHIVE",section:screen==="show"?"SHOW FILE":"TRACKED SHOWS",content,footer:"PODCASTS // DELIBERATE TRACKING"})}
export async function importAllPodcastHistory(onChanged=()=>{}){const payload=await post("./__vault/spotify/podcasts/history-import","spotify-podcast-history-import",{archivePath:"C:\\Users\\behem\\Downloads\\my_spotify_data (2).zip"}),stamp=payload.summary?.importedAt||new Date().toISOString();update(save=>{save.metadata||={};save.metadata.podcasts||={version:1,preferences:{scope:"tracked",sort:"newest"}};for(const source of payload.shows||[]){let item=Object.values(save.items||{}).find(value=>value.wing==="podcasts"&&String(value.title||"").trim().toLowerCase()===source.title.trim().toLowerCase());if(!item){const id=createId("podcast");save.items[id]={id,wing:"podcasts",type:"podcast",title:source.title,creator:source.publisher||"",artwork:source.artworkPath||"",status:"in_progress",favorite:false,addedAt:stamp,podcastMeta:{kind:"show",trackingState:"tracked",trackingStartedAt:stamp,episodes:[],spotifyHistoryListeningSeconds:0}};item=save.items[id]}item.creator=source.publisher||item.creator||"";item.artwork=source.artworkPath||item.artwork||"";item.podcastMeta={kind:"show",trackingState:"tracked",trackingStartedAt:item.podcastMeta?.trackingStartedAt||stamp,...(item.podcastMeta||{})};item.podcastMeta.spotifyId=source.spotifyId||item.podcastMeta.spotifyId||"";item.podcastMeta.externalUrl=source.externalUrl||item.podcastMeta.externalUrl||"";item.podcastMeta.episodes=source.episodes.map(ep=>({...ep,status:ep.fullyPlayed?"watched":"in_progress",externalUrl:ep.spotifyId?`https://open.spotify.com/episode/${ep.spotifyId}`:""}));item.podcastMeta.spotifyHistoryListeningSeconds=Math.round(source.totalListeningMs/1000);item.podcastMeta.historyImport={importedAt:stamp,firstPlayedAt:source.firstPlayedAt,lastPlayedAt:source.lastPlayedAt}}save.metadata.podcasts.lastHistoryImport=payload.summary});await flushPersistence();const visible=shows().length,withArtwork=shows().filter(item=>item.artwork).length;if(visible<(payload.summary?.shows||0))throw new Error(`Podcast verification failed: saved ${visible} of ${payload.summary.shows} shows.`);onChanged();return{...payload.summary,savedShows:visible,withArtwork}}
